### ISSUE TITLE
write code to insert P.Herc. texts into existing XML files

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#101]

**Comment by HolgerEssler** [comment]
It seems that the list provided by @paregorios contains the old transforms, not the new text which are intended to supersede them.

**Comment by cgajjar05** [comment]
Previous list provided by @paregorios  contains wrong URLs for xmls. So, correcting them :

* 59436: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/60/59436.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/60/59436.xml)
* 59450: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/60/59450.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/60/59450.xml)
* 59490: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/60/59490.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/60/59490.xml)
* 59492: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/60/59492.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/60/59492.xml)
* 59502: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/60/59502.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/60/59502.xml)
* 59503: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/60/59503.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/60/59503.xml)
* 59504: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/60/59504.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/60/59504.xml)
* 59505: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/60/59505.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/60/59505.xml)
* 59506: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/60/59506.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/60/59506.xml)
* 59761: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/60/59761.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/60/59761.xml)
* 62382: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/63/62382.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62382.xml)
* 62383: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/63/62383.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62383.xml)
* 62388: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/63/62388.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62388.xml)
* 62390: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/63/62390.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62390.xml)
* 62393: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/63/62393.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62393.xml)
* 62394: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/63/62394.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62394.xml)
* 62400: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/63/62400.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62400.xml)
* 62411: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/63/62411.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62411.xml)
* 62416: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/63/62416.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62416.xml)
* 62428: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/63/62428.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62428.xml)
* 62433: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/63/62433.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62433.xml)
* 62434: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/63/62434.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62434.xml)
* 62436: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/63/62436.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62436.xml)
* 62437: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/63/62437.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62437.xml)
* 62441: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/63/62441.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62441.xml)
* 62444: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/63/62444.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62444.xml)
* 62445: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/63/62445.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62445.xml)
* 62463: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/63/62463.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62463.xml)
* 62466: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/63/62466.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62466.xml)
* 62468: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/63/62468.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62468.xml)
* 62469: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/63/62469.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62469.xml)
* 62471: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/63/62471.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62471.xml)
* 62477: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/63/62477.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62477.xml)
* 62479: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/63/62479.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62479.xml)
* 62494: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/63/62494.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62494.xml)
* 62509: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/63/62509.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62509.xml)
* 62661: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/63/62661.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62661.xml)
* 65659: [transform](https://dclp.github.io/dclpxsltbox/output/dclp/66/65659.html)  [xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/66/65659.xml)

@HolgerEssler  : please review these again.

**Comment by HolgerEssler** [comment]
@cgajjar05
These appear to be still the same old files as before.
We have updated the link to the drop-box folder where the new ones are available:
https://www.dropbox.com/sh/2jhxa3qe7e2olry/AACmU4S2psra9bMqVlKARx--a?dl=0

**Comment by cgajjar05** [comment]
@paregorios  has updated html files. @HolgerEssler  : will you please check the transforms again.

**Comment by HolgerEssler** [comment]
Everything appears to be fine now.

**Comment by HolgerEssler** [comment]
Dear Chirag,
   many thanks. Everything appears to be fine now.
   Best,
Würzburg, 22. January 2015  Holger.

> @paregorios  has updated html files. @HolgerEssler  : will you  
> please check the transforms again.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/DCLP/dclpxsltbox/issues/101#issuecomment-70904734



------------------------------------
Dr. Holger Essler, AR
Institut für Klassische Philologie I
Residenzplatz 2 (Südflügel)
D-97070 Würzburg

Tel.:            +49-931-31-85632
email:           Holger.Essler@uni-wuerzburg.de
Institutsseite:  www.klassphil.uni-wuerzburg.de
Epikurzentrum:   www.epikur-wuerzburg.de

**Comment by paregorios** [comment]
Hooray! Closing...
