### ISSUE TITLE
review latest metadata for EpiDoc conformance and tasks

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#103]
Engage @Edelweiss  @jcowey  @cgajjar05  and members of the EpiDoc community (e.g., @hcayless @gabrielbodard) in reviewing all of the newly cross-walked data (through  idp.data commit: https://github.com/DCLP/idp.data/commit/a413b502a0925bc3042c617b5f2a7577798f984e) for XML validity, conformance to EpiDoc practice in other projects, and for any issues  that might need to be escalated to the EpiDoc or TEI change levels.

**Comment by paregorios** [comment]
@jcowey I'm inclined to close this old ticket and focus instead on working the individual encoding and validation questions that stil remain. What do you think?

**Comment by jcowey** [comment]
@paregorios I agree and am closing
