### ISSUE TITLE
missing information

### ISSUE THREAD

**Issue by rogerbagnall** [DCLP/dclpxsltbox#105]
If I take as an absolutely random example I landed on, http://dclp.github.io/dclpxsltbox/output/dclp/113/112364.html, the display omits the actual title of the piece as given in LDAB, as well as the actual reference to P.Oxy. 71 4809. The nome number has also vanished: U is there, but not 19. Are not these things we would want in the display?

**Comment by paregorios** [comment]
As @jcowey has assigned this ticket to me, I see one remaining analysis task for me: determine whether the LDAB title is missing from the XML as well as the HTML, or is just effectively suppressed by the XSL transform in the same manner as the "actual reference to P.Oxy. 71 4809). That will result in the creation of a new ticket, either for the renovation of the data crosswalk or for the enhancement of the XSTL, as appropriate.

And I have a question for @jcowey : do you intend to create a ticket of the Nome-related work? I don't think the title of present ticket is sufficiently specific to cover that issue.

**Comment by paregorios** [comment]
@rogerbagnall please clarify: when you wrote "the display omits the actual title of the piece as given in LDAB" did you mean that our version omits to include the string "P. Oxy. 71 4809 (Parsons, PeterJ.)" or some other component(s) of [the LDAB information as shown in its own web interface](http://www.trismegistos.org/text/112364)?

**Comment by rogerbagnall** [comment]
I think that when I looked at it (and this is now not so recent) I was 
thinking of "On Hellenistic Monarchs", the title given in the edition. 
That is the field "book" at 
http://www.trismegistos.org/ldab/text.php?tm=112364

-- 
Roger S. Bagnall
Leon Levy Director
Institute for the Study of the Ancient World
New York University

**Comment by paregorios** [comment]
So, in addition to the P.Oxy reference (which is *in* the XML), @rogerbagnall thinks we also should see the contents of the TM "book" field (which is NOT in the XML). Over to @jcowey @Edelweiss to confer with TM about how and whether to get this sort of info into the XML.

**Comment by rla2118** [comment]
It would be nice to get this from TM as a simple dump.  I am a bit wary of
using precious resources right now to structure it for bibl, especially
with other important tasks waiting to be tackled.

**Comment by paregorios** [comment]
I'm taking this ticket back to assess whether we've dealt fully with everything therin.

**Comment by paregorios** [comment]
Putting this ticket on the backlog and scheduling for discussion on 20 May 2015 as the question of the "book" field from TM does not seem to have been given a more descriptive ticket of its own. The P.Oxy. reference is now showing up in the HTML transform.

**Comment by paregorios** [comment]
"book" data from TM has been given its own ticket: #145. Closing this ticket as complete per discussion in weekly standup this morning.
