### ISSUE TITLE
Invalid XML <div type="figure">

### ISSUE THREAD

**Issue by Edelweiss** [DCLP/dclpxsltbox#106]
Value of attribute "type" is invalid; must be equal to "apparatus", "bibliography", "commentary", "edition", "textpart" or "translation"

e.g.

https://github.com/DCLP/idp.data/blob/dclp/DCLP/65/64120.xml

```XML
<div type="figure">
   <p>
      <figure>
         <graphic url="www.papyri.info/apis/michigan.apis.2353"/>
      </figure>
   </p>
</div>
```
could be changed into:

```XML
<div type="bibliography" subtype="figure">
   <p>
      <figure>
         <graphic url="www.papyri.info/apis/michigan.apis.2353"/>
      </figure>
   </p>
</div>
```

This also affects HGV, e.g.

https://github.com/DCLP/idp.data/blob/dclp/HGV_meta_EpiDoc/HGV111/110164.xml

**Comment by paregorios** [comment]
@hcayless can you comment on the above question?

**Comment by paregorios** [comment]
pinging @hcayless

**Comment by hcayless** [comment]
It looks like this was missed when EpiDoc removed div[@type='figure'] a
couple of years ago. Yes, you should be using tei:facsimile. And I have a
bunch of work to do. Sigh.

**Comment by paregorios** [comment]
So @Edelweiss @jcowey it looks to me like DCLP, for fullest EpiDoc conformance, should move to using tei:facsimile, with the expectation that legacy encodings already in papyri.info will follow suit at some stage. We thereby (meaning me) are signing up to verify and extend XSLT support to handle them. I'm assigning this ticket back to @Edelweiss to see if you concur. We can this discuss an implementation plan.

**Comment by paregorios** [comment]
I'm putting this ticket on the backlog pending a decision about when to implement and who should implement the fix across existing files. I will add it to list of issues to discuss 20 May 2015.

**Comment by paregorios** [comment]
keep track of what we did so we can share the recipe back to papyri.info where the old encoding still obtains.

**Comment by HolgerEssler** [comment]
I wonder whether we should try to unify these references to images and those within `<custEvent>´ in #128.

**Comment by paregorios** [comment]
I'm taking this ticket temporarily while I ponder @HolgerEssler's suggestion above.

**Comment by jcowey** [comment]
Example with absolute url:

```xml
<facsimile>
    <graphic url="http://beinecke.library.yale.edu/papyrus/oneSET.asp?pid=4514"/>
</facsimile>
```
Example with enumeration:

```xml
<facsimile>
    <graphic n="1" url="…"/>
    <graphic n="2" url="…"/>
    <graphic n="3" url="…"/>
</facsimile>
```

**Comment by Edelweiss** [comment]
Another possibility might be to collect all references to images - be it online or printed material - in one div

```XML
<div type="bibliography" subtype="illustrations">
    <p>
       <bibl type="illustration">ed. princ.</bibl>
       <figure>
          <graphic url="http://smb.museum/berlpap/index.php/01681/"/>
       </figure>
    </p>
 </div>

```

[TM No. 62107](https://github.com/DCLP/idp.data/blame/dclp/DCLP/63/62107.xml)

**Comment by Edelweiss** [comment]
Decision. All graphics contained within div type="figure" will be moved to facsimile section. Then the files will vaildate. If later we decide to change then all we have to do is reverse the commit or run another xslt change over it.

**Comment by HolgerEssler** [comment]
For Anagnosis we have inserted all references to images to <custEvent>, 
since it was at a specific moment in time when the image was taken - and 
this gives an easy way to attach name, date etc. to it.

**Comment by leoba** [comment]
I'm going to ask @paregorios to ping me here if he needs me to modify the xslt to handle the new facsimile section.

**Comment by jcowey** [comment]
As facsimile is completely new to the code, it seems to me to follow that the xslt will have to be modified.

**Comment by paregorios** [comment]
@leoba yes, I think this is one we need to do. I've shared a private repository (Campa Inscriptions) with you. It includes a fork of the EpiDoc stylesheets used to produce the HTML for the inscriptions that one sees here: http://isaw.nyu.edu/publications/inscriptions/campa/. It caters for facsimile, though perhaps not in the way we're doing it here.

Only reason the repos is private is because there are EFEO embargoed images therein (it's a todo to break that out). In any case, you should be able to see it if logged into github. 

You can find the relevant bits perhaps with a search like https://github.com/paregorios/Campa-Epigraphy/search?l=xslt&q=facsimile&utf8=%E2%9C%93

**Comment by jcowey** [comment]
Now committed:
https://github.com/DCLP/idp.data/commit/9a269087f33d228a12d17ad27051528ad9663935
and can be viewed on 
[https://github.com/DCLP/idp.data/tree/hd hd branch]

**Comment by paregorios** [comment]
I'm taking this ticket temporarily to have a look at the now-valid XML.

**Comment by jcowey** [comment]
possibly now tending to prefer the 

```XML
<div type="bibliography" subtype="illustrations">
    <p>
       <bibl type="illustration">ed. princ.</bibl>
       <figure>
          <graphic url="http://smb.museum/berlpap/index.php/01681/"/>
       </figure>
    </p>
 </div>

```
solution
because the urls are often .htm / .html sites
or 
jpgs 
not controlled or strictly speaking part of the project

**Comment by jcowey** [comment]
```
<div type="bibliography" subtype="illustrations">
   <listBibl>
      <bibl type="illustration">ed. princ.</bibl>
      <bibl><ptr target="http://bibd.uni-giessen.de/papyri/images/pbug-inv115recto.jpg"/></bibl>
   </listBibl>
</div>
```
is probably preferable.
Other possibilities would be
```
<div type="bibliography" subtype="illustrations">
   <p>
      <bibl type="illustration">ed. princ.</bibl>
      <bibl><ptr target="http://bibd.uni-giessen.de/papyri/images/pbug-inv115recto.jpg"/></bibl>
   </p>
</div>
```
OR

```
<div type="bibliography" subtype="illustrations">
   <p>
      <bibl type="illustration">ed. princ.</bibl>
      <ptr target="http://bibd.uni-giessen.de/papyri/images/pbug-inv115recto.jpg"/>
   </p>
</div>
```

I think ```bibl``` inside ```listBibl``` seems better. And ```ptr``` within ```bibl``` also better.

**Comment by paregorios** [comment]
What about something like:

```xml
<div type="bibliography" subtype="illustrations">
  <listBibl>
    <bibl type="illustration">ed. princ.
      <ptr target="http://bibd.uni-giessen.de/papyri/images/pbug-inv115recto.jpg"/></bibl>
  </listBibl>
</div>
```

The ```ptr``` is pointing to an illustration in the ed. princ., no? Therefore a single bibliographic reference, rather than two separate ones. Or am I confused?

**Comment by jcowey** [comment]
For the above reasons I like:

```XML
<div type="bibliography" subtype="illustrations">
   <listBibl>
      <bibl type="illustration">ed. princ.</bibl>
      <bibl><ptr target="http://bibd.uni-giessen.de/papyri/images/pbug-inv115recto.jpg"/></bibl>
   </listBibl>
</div>
```

**Comment by paregorios** [comment]
Right. That makes better sense. The only additional questions I have is whether there's existing data that could be used to:

 * link the "ed. princ." bibl to a full(er) bibliographic citation
 * describe the bibliograhic context of the ```target``` in the second ```bibl```, maybe linking it to a fuller bibliographic record as well (not for the individual image, but for the site in question, perhaps)

**Comment by jcowey** [comment]
* link the "ed. princ." bibl to a full(er) bibliographic citation: 
- almost certainly, yes! probably with a corresp to the main bibliographical entry (```div type="bibliography" subtype="publication"```)
 * describe the bibliograhic context of the ```target``` in the second ```bibl```: 
- would certainly be possible (more accurate), but low priority IMO

**Comment by paregorios** [comment]
I think we have a consensus here.

**Comment by paregorios** [comment]
@jcowey I think we should discuss status on this issue

**Comment by Edelweiss** [comment]
Currently we have a _tei:div_ with its attribute _@subtype_ set to ‘illustrations' which comprises two types of _tei:bibl_ elements, printed images and links to online resources.

Here an example:
https://github.com/DCLP/idp.data/blob/3b8d73b0f6c8571e4d6d5a188aa3bd09ff06f545/DCLP/63/62913.xml

While printed images are marked by having their _@type_ attribute set to ‘illustration’ there is no such _@type_ attribute for online images.

Today we discussed that it might make sense to have a type for both of these image resources, marking them as ‘printed’ and ‘online’ respectively.

The example above could look like this:
```xml
<div type="bibliography" subtype="illustrations">
    <listBibl>
        <bibl type="printed">P.Köln 7, pl.IXc and d</bibl>
        <bibl type="printed">BICS 22 (1975), pl.I-III</bibl>
        <bibl type="printed">ZPE 109 (1995), pl.IX</bibl>
        <bibl type="online">
            <ptr target="http://www.csad.ox.ac.uk/POxy/papyri/vol49/pages/3450.htm"/>
        </bibl>
        <bibl type="online">
            <ptr target="http://www.csad.ox.ac.uk/POxy/papyri/vol57/pages/3885.htm"/>
        </bibl>
        <bibl type="online">
            <ptr target="http://www.uni-koeln.de/phil-fak/ifa/NRWakademie/papyrologie/Karte/VII_304.html"/>
        </bibl>
        <bibl type="online">
            <ptr target="http://www.ville-ge.ch/fcgi-bin/fcgi-axn?launchpad&amp;/home/minfo/bge/papyrus/pgen257-ri.axs&amp;550&amp;550"/>
        </bibl>
        <bibl type="online">
            <ptr target="http://www.ville-ge.ch/fcgi-bin/fcgi-axn?launchpad&amp;/home/minfo/bge/papyrus/pgen257-vi.axs&amp;550&amp;550"/>
        </bibl>
    </listBibl>
</div>
```
This change would also ease the work on the editor because there is a clearer distinction between printed and online resources.

**Comment by Edelweiss** [comment]
[example file old](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62913.xml#L128)
```
/TEI/text/body/div[@type="figure"]/p/figure/graphic/@url
/TEI/text/body/div[@type="bibliography"][@subtype="illustrations"]/p/bibl[@type="illustration"]
```

[example file new](https://github.com/DCLP/idp.data/blob/hd/DCLP/63/62913.xml#L128)
```
/TEI/text/body/div[@type='bibliography'][@subtype='illustrations']/listBibl/bibl[@type='online']
/TEI/text/body/div[@type='bibliography'][@subtype='illustrations']/listBibl/bibl[@type='printed']/ptr/@target
```

**Comment by paregorios** [comment]
This has been addressed with commits up through [navigator/issue106/c899ae4](https://github.com/DCLP/navigator/commit/c899ae4615620c80929b5a97cea0677ad43f706d). Consider the following examples (NB: over half the links I tried clicking resulted in "not found" or other server errors, or DNS errors, but the HTML contains the URLs as encoded in the XML):

- [62913](http://dclp.github.io/dclpxsltbox/output/dclp/63/62913.html)
- [64120](http://dclp.github.io/dclpxsltbox/output/dclp/65/64120.html)

Over to @jcowey, @rla2118, and @HolgerEssler for review.

**Comment by paregorios** [comment]
Note also that there are thousands of ```bibl``` tags still with type="illustration" instead of "printed" or "online" scattered throughout the hd branch of idp.data. The code currently treats them the same as type="printed", passing them through as plain text, but it represents inconsistent encoding.
