### ISSUE TITLE
XSLT for principal edition information of the type P.Oxy. 71 4809

### ISSUE THREAD

**Issue by jcowey** [DCLP/dclpxsltbox#107]
In the case of https://github.com/DCLP/idp.data/blob/dclp/DCLP/113/112364.xml
at
https://github.com/DCLP/idp.data/blob/dclp/DCLP/113/112364.xml#l83
there is information about the place of edition. This should be displayed in Reference edition. There is I am sure a question here about 
div type="bibliography" subtype="referenceEdition"> as in 
https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62494.xml#l81
being treated in the same way as 
div type="bibliography" subtype="principalEdition">
https://github.com/DCLP/idp.data/blob/dclp/DCLP/113/112364.xml#l83
We may in the future want to use one subtype. principalEdition is built on the example of DDbDP_XML. referenceEdition was introduced through Herculaneum material. 
My plea for now would be to have XSLT treat them in the same way unless this is going to cause problems, which I cannot see at present.

**Comment by jcowey** [comment]
Carmen will make changes next week. Then Chirag can go ahead and write XSLT

**Comment by paregorios** [comment]
Reassigning to @Edelweiss

**Comment by Edelweiss** [comment]
https://github.com/DCLP/idp.data/commit/fd9e747afc9cf1e732b45c58c5b59d7833a18489
