### ISSUE TITLE
Invalid XML <publicationStmt>

### ISSUE THREAD

**Issue by Edelweiss** [DCLP/dclpxsltbox#108]
> element "idno" not allowed yet; expected element "ab", "authority", "distributor", "p" or "publisher"

```XML
<publicationStmt>
   <!-- ab, authority, distributor, p or publisher missing here -->
   <idno type="dclp">64119</idno>
   <idno type="TM">64119</idno>
   <idno type="LDAB">5337</idno>
   <idno type="filename">64119</idno>
</publicationStmt>
```
Perhaps we could state the project's name in an tei:authority tag or give the name of the original data source.

**Comment by paregorios** [comment]
I don't think this is quite exactly a duplicate for #34, which is specifically about copyright statement. We also need an authority statement. As these are clearly related issues, I'm going to accept this ticket and put it on the backlog for implementation.

**Comment by jcowey** [comment]
Global change to 
```<authority>Digital Corpus of Literary Papyri</authority>```

**Comment by Edelweiss** [comment]
[add authority (Digital Corpus of Literary Papyri) to publication statement](https://github.com/DCLP/idp.data/commit/3049456793f2758accc1306d478377e47d727668)

**Comment by jcowey** [comment]
Great. Finished for now.
