### ISSUE TITLE
handle principalEdition and referenceEdition bibliography in the same way

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#109]
At present, some of our data uses the value "principalEdition" in the "subtype" attribute on "div" elements with "type" attributes set to "bibliography". Other data makes use of "referenceEdition". There is a discussion underway about whether and how to normalize this practice and what form the corresponding markup would take (see #107, which grew out of #105). 

Meantime, please modify the XSLT to treat subtype="principalEdition" and subtype="referenceEdition" in the same way so that we can at least see the relevant data in the output, pending a resolution to the tickets above.

**Comment by cgajjar05** [comment]
Blocked for resolution of #107

**Comment by jcowey** [comment]
#107 is now closed. The commit that changed the subtypes is:
https://github.com/DCLP/idp.data/commit/2a66eb239ffaf5fbef7e760eb46ea84d0aba5ed4

**Comment by paregorios** [comment]
Hi @cgajjar05 please put this ticket back in your work queue.

**Comment by paregorios** [comment]
This ticket is superseded by #123 . Marking this won't fix and re-assigning to @jcowey to get his confirmation before closing.

**Comment by paregorios** [comment]
@jcowey ok if I close this one per discussion above?

**Comment by paregorios** [comment]
@jcowey ping ^^^^^

**Comment by jcowey** [comment]
Sorry that this got forgotten about. Yes it can be closed and I am doing so.
