### ISSUE TITLE
List of Greek text entry for existing DCLP files (match by TM number and insert text body section)

### ISSUE THREAD

**Issue by jcowey** [DCLP/dclpxsltbox#111]
Here is a list of links (copied out of a mail sent by Rodney to Tom and James). The texts should be extracted from the XML version in the editor and placed appropriately in the relevant DCLP file (matching by TM number)

 * Entered: SoSOL 2014 383: <http://papyri.info/editor/publications/43018/ddb_identifiers/97308/edit
 * Entered: SoSOL 2014 504: <http://papyri.info/editor/publications/42925/ddb_identifiers/97174/edit
 * Entered: SoSOL 2014 603: <http://papyri.info/editor/publications/40555/ddb_identifiers/92981/edit
 * Entered: SoSOL 2014 602: <http://papyri.info/editor/publications/40553/ddb_identifiers/92978/edit
 * Entered: SoSOL 2014 610: <http://papyri.info/editor/publications/40561/ddb_identifiers/92993/edit
 * Entered: SoSOL 2014 609: <http://papyri.info/editor/publications/40560/ddb_identifiers/92991/edit
 * Entered: SoSOL 2014 608: <http://papyri.info/editor/publications/40559/ddb_identifiers/92989/edit
 * Entered: SoSOL 2014 607: <http://papyri.info/editor/publications/40558/ddb_identifiers/92987/edit
 * Entered: SoSOL 2014 606: <http://papyri.info/editor/publications/40557/ddb_identifiers/92985/edit
 * Entered: SoSOL 2014 604: <http://papyri.info/editor/publications/40556/ddb_identifiers/92983/edit
 * Entered: SoSOL 2014 486: <http://papyri.info/editor/publications/38716/ddb_identifiers/88056/edit
 * Entered: SoSOL 2014 539: <http://papyri.info/editor/publications/39291/ddb_identifiers/89456/edit
 * Entered: SoSOL 2014 534: <http://papyri.info/editor/publications/39244/ddb_identifiers/89322/edit
 * Entered: SoSOL 2014 385: <http://papyri.info/editor/publications/38851/ddb_identifiers/88386/edit
 * Entered: SoSOL 2014 384: <http://papyri.info/editor/publications/38850/ddb_identifiers/88384/edit
 * Entered: SoSOL 2014 484: <http://papyri.info/editor/publications/38769/ddb_identifiers/88186/edit
 * Entered: SoSOL 2014 497: <http://papyri.info/editor/publications/38761/ddb_identifiers/88168/edit
 * Entered: SoSOL 2014 491: <http://papyri.info/editor/publications/38739/ddb_identifiers/88109/edit
 * Entered: SoSOL 2014 494: <http://papyri.info/editor/publications/38755/ddb_identifiers/88153/edit
 * Entered: SoSOL 2014 482: <http://papyri.info/editor/publications/38720/ddb_identifiers/88064/edit

"These duplicate files appear under "committed" and have different ddb_id's in URL (delete them?):"
- this section possibly needs clarification from Rodney, as to what is going on -
 * SoSOL 2014 504: <http://papyri.info/editor/publications/38771/ddb_identifiers/88192/edit
 * SoSOL 2014 539: <http://papyri.info/editor/publications/39290/ddb_identifiers/89454/edit
 * SoSOL 2014 534: <http://papyri.info/editor/publications/39243/ddb_identifiers/89320/edit
 * SoSOL 2014 604 (=  * SoSOL 2014 486 above): <http://papyri.info/editor/publications/40239/ddb_identifiers/92413/edit

**Comment by jcowey** [comment]
Have now asked Andrea Bernini to look after this task and get it done. He agreed.

**Comment by paregorios** [comment]
Great, thanks!

**Comment by jcowey** [comment]
Even better. All texts have now been entered. Ticket is being closed.
