### ISSUE TITLE
cannot insert <l> in <ab>

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#112]
Reported by @HolgerEssler who also said it seemed to be impossible to use <lg>.

**Comment by paregorios** [comment]
I have just tested with the EpiDoc schema at http://www.stoa.org/epidoc/schema/latest/tei-epidoc.rng and found that @HolgerEssler is correct the ```<l>``` is not valid inside ```<ab>```. This is consistent with [TEI documentation](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-l.html). 

Further testing demonstrates that the following construct, which is the one specified for [verse line markup in the EpiDoc Guidelines](http://www.stoa.org/epidoc/gl/latest/trans-verseline.html), is valid with the "latest" epidoc schema:

```xml
<div type="edition">
    <lg>
        <l></l>
    </lg>
</div>
```

Recommendation: replace ```ab``` with ```lg``` in verse texts and move forward.

**Comment by HolgerEssler** [comment]
@paregorios This seems to lead to the further problem that <lg> may not contain other crucial elements like <supplied> or <unclear>.

**Comment by paregorios** [comment]
@HolgerEssler can you provide a marked up example?

**Comment by HolgerEssler** [comment]
https://github.com/DCLP/idp.data/blob/dclp/DCLP/60/59920.xml#L108
There <ab> is replaced by <lg>. The potential problems pointed out by me 
above do not seem to occur.

**Comment by paregorios** [comment]
@HolgerEssler are you comfortable with closing this issue, or is there still a concern to be addressed?

**Comment by HolgerEssler** [comment]
This means that at the moment we have no Leiden+ solution for encoding verses, but can do it only in XML. I leave it to @rla2118 and @jcowey to decide, whether we should leave it like this and state the XML-solution in the guide-lines, or whether we should implement it completely. In any case I wonder, whether display is affected.

**Comment by paregorios** [comment]
per @rla2118 I will refactor this ticket to reflect the desire to add Leiden+ support for encoding verses.

**Comment by paregorios** [comment]
There are two tasks here:

- [ ] Figure out what the stylesheets currently do with verse markup (```<lg>```, ```<l>```, etc). Is an XSLT ticket needed?
- [ ] Refactor this ticket to focus on the need for Leiden+ support.

**Comment by paregorios** [comment]
See now #278 for the Leiden+ aspect.

**Comment by paregorios** [comment]
The EpiDoc stylesheets currently do include support for handling verse-related elements like ```<lg>``` and ```<l>``` (see [htm-teilgandl.xsl](https://github.com/DCLP/epidoc-xslt/blob/master/example-p5-xslt/htm-teilgandl.xsl) and [txt-teilgandl.xsl](https://github.com/DCLP/epidoc-xslt/blob/master/example-p5-xslt/txt-teilgandl.xsl), with other tests checking for their presence passim).  Closing this ticket as nothing further to do. 

Once we have some verse to look at in HTML, please open new tickets for any display problems.
