### ISSUE TITLE
Round brackets in the modern edition

### ISSUE THREAD

**Issue by andreabernini** [DCLP/dclpxsltbox#122]
I wrote *round-bracket* in the case of P.Oxy. 70.4763 (TM 92143) col. I, 17-18
https://github.com/DCLP/idp.data/blob/dclp/DCLP/93/92143.xml#l95
https://github.com/DCLP/idp.data/blob/dclp/DCLP/93/92143.xml#l96

**Comment by HolgerEssler** [comment]
Cf. #56
https://github.com/DCLP/dclpxsltbox/issues/56

------------------------------------
Dr. Holger Essler, AR
Institut für Klassische Philologie I
Residenzplatz 2 (Südflügel)
D-97070 Würzburg

Tel.:            +49-931-31-85632
email:           Holger.Essler@uni-wuerzburg.de
Institutsseite:  www.klassphil.uni-wuerzburg.de
Epikurzentrum:   www.epikur-wuerzburg.de

**Comment by paregorios** [comment]
I have copied the example information into the thread for issue #56. Recommend we close this issue as a now-duplicate. Do you have any objections @andreabernini or @HolgerEssler ?

**Comment by HolgerEssler** [comment]
No objections.

**Comment by andreabernini** [comment]
No problem.

**Comment by paregorios** [comment]
closing as duplicate for #56
