### ISSUE TITLE
Alternatives (and regularizations) involving also diaeresis

### ISSUE THREAD

**Issue by andreabernini** [DCLP/dclpxsltbox#124]
In https://github.com/DCLP/idp.data/tree/dclp/DCLP/114/113269.xml#l164 (P.Oxy. 72.4854 = TM 113269) the Leiden+ is displayed as follows (problems with the diaeresis):

```C.v.4. or του ι̣', or τουι̣(  ) (or τούτ̣(ων)), or τουι̣(ϊ) (or τουί̣(ϊ) (i.e. τουτουί̣(ϊ))) : τουίτουι̣' papyrus : ''τουϊ. papyrus : ''τουϊ. papyrus```

**Comment by paregorios** [comment]
What is the desired or intended output?

**Comment by andreabernini** [comment]
This is the Leiden+:

<:του ι̣(´)||alt||του <#ι̣'=10#>|<:(|τουι̣|)|alt|(τούτ̣(ων)):>|<:του ι̣(¨)|alt|<:τουτου ί̣(¨)|corr|του ί̣(¨):>:>:>

I wrote it three times, but it is displayed five times.

**Comment by andreabernini** [comment]
As far as the |reg|, in Pap. Colon. 28.18 (TM 65436) there are three cases:

line 3: https://github.com/DCLP/idp.data/blob/dclp/DCLP/66/65436.xml#l78
Leiden+: <:ἑξαπτέρυγα Σεραφίμ|reg|ε ι(¨)ξαπτερ ι(¨)κα ι(¨) σο ι(¨)ραφιν:>
displayed (apparatus): l. ἑξαπτέρυγα Σεραφίμ : εϊξαπτερϊκαϊ papyrus : εϊξαπτερϊκαϊ papyrus : εϊξαπτερϊκαϊ papyrus: ϊραφιν papyrus
expected (apparatus): l. ἑξαπτέρυγα Σεραφίμ : εϊξαπτερϊκαϊ papyrus : ϊραφιν papyrus 

line 4: https://github.com/DCLP/idp.data/blob/dclp/DCLP/66/65436.xml#l789 
Leiden+: <:ταῖς πτέρυξιν|reg|τες τερ ι(¨)ξ ι(¨)ν:>
displayed (apparatus): l. ταῖς πτέρυξιν : ϊξϊν papyrus : ϊξϊν papyrus
expected (apparatus): l. ταῖς πτέρυξιν : ϊξϊν papyrus

line 7: https://github.com/DCLP/idp.data/blob/dclp/DCLP/66/65436.xml#l82 
Leiden+: <:ἐπινίκιον|reg|επ ι(¨)ν ι(¨)τε ι(¨)[ον]:>
displayed (apparatus): l. ἐπινίκιον : επϊνϊτεϊ[ον] papyrus : επϊνϊτεϊ[ον] papyrus : επϊνϊτεϊ[ον] papyrus
expected (apparatus): l. ἐπινίκιον : επϊνϊτεϊ[ον] papyrus

**Comment by paregorios** [comment]
This smells like another case of ```<hi>``` not being handled properly in apparatus. Compare #126 and #130. I think we should solve #126 first (marking blocked for same).

**Comment by wsalesky** [comment]
I think this may be addressed by: 
https://github.com/DCLP/dclpxsltbox/issues/241

**Comment by paregorios** [comment]
Agree that the problems of repetition addressed here have been resolved with fixes for #241. Closing as resolved.
