### ISSUE TITLE
Vowel length 

### ISSUE THREAD

**Issue by andreabernini** [DCLP/dclpxsltbox#125]
The supralinear stroke indicating the vowel length (in the following cases used together with diacritical symbols) cannot be accepted by simply adding it above the vowel; see e.g. P.Oxy. 75.5028 (TM 128956)

https://github.com/DCLP/idp.data/blob/master/DCLP/129/128956.xml#L85 ἐ̣δίνεον (ln. 2)

https://github.com/DCLP/idp.data/blob/master/DCLP/129/128956.xml#L87 ὕληι (ln. 4)

**Comment by paregorios** [comment]
@andreabernini does the supra-linear stroke in question appear on the papyrus or is it an editorial intervention?

**Comment by rla2118** [comment]
@paregorios The supralinear stroke appears on the papyrus and is combined with a diacritical mark.

**Comment by paregorios** [comment]
Thanks @rla2118. 

It appears that @andreabernini's problem was that he couldn't enter it in the editor using Leiden+. I've inspected the encoding in the XML and there's no indication of the "supralinear stroke" in the XML at this point. Before we can address the Leiden+ question (and any attendant XSLT issues), we need to decide what encoding is wanted here. The baseline option would be to use the established ```<hi rend="supraline">```. Is that sufficient, or do we also need some way to encode the text-encoder's judgment that a macron(?) is indicated?

cc @jcowey @rogerbagnall @HolgerEssler

**Comment by rogerbagnall** [comment]
Supralinear strokes are indeed of different types, and if we want to preserve the ability to search in the XML for macrons as opposed to Coptic short vowel supralinear strokes, then we need the ability to say that this is a macron. This isn't in a sense any different from distinguishing an acute accent from a similar-shaped stroke of different meaning.

**Comment by paregorios** [comment]
Well, then, we're talking about ```<hi rend="longum">```, i.e., issue #165, yes?

**Comment by paregorios** [comment]
Closing as duplicate for #165.
