### ISSUE TITLE
linking to images in custodial events

### ISSUE THREAD

**Issue by HolgerEssler** [DCLP/dclpxsltbox#128]
At the moment inside custEvent we use the ptr-element
for encoding links to images. This should be replaced by the graphic-element:
So instead of
<ptr target="..." 
we should have:
<graphic url="..."

**Comment by paregorios** [comment]
@HolgerEssler should this be assigned to you?

**Comment by HolgerEssler** [comment]
Our IT-people are going to do the change in the Anagnosis branch and
then merge to DCLP.

**Comment by HolgerEssler** [comment]
There is now a pull request from our IT people:
https://github.com/DCLP/idp.data/pull/2

**Comment by HolgerEssler** [comment]
For our Anagnosis project it would be desirable to have the changes made by our IT people merged to the main branch in the June milestone.

**Comment by paregorios** [comment]
Concur, but probably can do even sooner; i.e., in May.. I'm taking ownership of this issue and moving to May milestone.

**Comment by HolgerEssler** [comment]
That would be great. Thank you. However, I should point out that our IT people have made the change only in the xml-documents. Thus after the merge the xPath in our XSLT will have to be adapted accordingly (from something like custEvent/ptr/@target to custEvent/graphic/@url ?).

**Comment by HolgerEssler** [comment]
Our IT people have now carried out the merge (it was a maior blocker to their work), if there are no other problems, the task now consists just in changig the xPath in our XSLT for display as describe above.

**Comment by paregorios** [comment]
@HolgerEssler pre-existing code wraps the entire ```custEvent``` content in a link to the URL. Do you want this behavior for the ```graphic``` URL as well, or would you prefer that we append the link to the end of the ```custEvent``` information, using a word like "graphic" or "illustration"?

**Comment by HolgerEssler** [comment]
Could it be wrapped around the type-attribute? E.g. in
"Sketched by Giuseppe Casanova (1802-1803)"
could the link be underlying "Sketched"?

**Comment by paregorios** [comment]
I'll undertake to do that.

**Comment by paregorios** [comment]
In work at https://github.com/DCLP/navigator/tree/issue128

**Comment by paregorios** [comment]
Results of transform using new code (DCLP/navigator/cb1208e0af90d1505c76150cf07743e50ca1c1ad) are presently up at http://dclp.github.io/dclpxsltbox/output/dclp/, e.g., http://dclp.github.io/dclpxsltbox/output/dclp/81/80754.html

@HolgerEssler if this is OK with you I will merge into primary branch and close this issue.

**Comment by HolgerEssler** [comment]
Perfect. Many thanks.

**Comment by paregorios** [comment]
Complete. Changes merged into dclpxsltbox/master and into idp.data/xslt-master
