### ISSUE TITLE
|subst| involving letters with breath

### ISSUE THREAD

**Issue by andreabernini** [DCLP/dclpxsltbox#130]
O.Claud. II 414 (TM 63423)

https://github.com/DCLP/idp.data/blob/dclp/DCLP/64/63423.xml#l82 

Leiden+: ```<:<# Α( ᾿)σμβ=1242#>|subst|<# Α( ᾿)σμγ=1243#>:>```

Displayed 
```corr. ex Α(ἀ)σμγ : ἀσμβ papyrus```

Expected  to see:
```corr. ex Ασμγ : ἀσμγ papyrus : ἀσμβ papyrus```

**Comment by paregorios** [comment]
relevant XML for this example is:

```xml
<subst><add place="inline"><num value="1242"><hi rend="lenis">Α</hi>σμβ</num></add><del rend="corrected"><num value="1243"><hi rend="lenis">Α</hi>σμγ</num></del></subst>
```

**Comment by paregorios** [comment]
There are two problems here, both apparently arising from the XSLT. 

The first seems to be a real bug, namely, that we should see "corr. ex Ασμγ" in the apparatus for line 5 of O. Claud. 2 414, but instead get "corr. ex Α(ἀ)σμγ". The introduction of ```<hi rend="lenis">``` is presumably confusing whatever code is trying to put together the relevant string based on the encoding.

Is the second a bug or a request for DCLP-differentiated usage? Namely, that we want to see both the original and the corrected text as found on the papyrus. Need to check EpiDoc guidance (if any) and papyri.info Leiden documentation to see if there are any leads. Also need to mine DDB for parallels to see if this is a consistent problem.

**Comment by paregorios** [comment]
My guess is that at least part of the problem here is proper handling of ```<hi>``` as we see in the case documented in #126. I think #126 should be addressed first.

**Comment by paregorios** [comment]
Block for #126

**Comment by wsalesky** [comment]
@paregorios Can I ask for clarification of the logic here? How should `t:hi` elements be rendered in the apparatus when they are children of `t:subst`?

Are the following also rendering incorrectly?
http://dclp.github.io/dclpxsltbox/output/dclp/129/128972.html#to-app-subst01

http://dclp.github.io/dclpxsltbox/output/dclp/155/154385.html#to-app-subst02

http://dclp.github.io/dclpxsltbox/output/dclp/63/62564.html#to-app-subst05

Thanks.

**Comment by paregorios** [comment]
@wsalesky I will have to get the papyrologists to weigh in on whether the indicated output is what they all want.

**Comment by paregorios** [comment]
further progress on this ticket is blocked for resolution of #282

**Comment by paregorios** [comment]
Per resolution of #282, "ancient lenis" should be suppressed (i.e., not entered by the user) in numeric figures. Therefore I am closing this ticket "won't fix."
