### ISSUE TITLE
How to render high corner brackets?

### ISSUE THREAD

**Issue by andreabernini** [DCLP/dclpxsltbox#131]
In Pap. Colon. 28.10 line 4 (TM 64920) https://github.com/DCLP/idp.data/blob/dclp/DCLP/65/64920.xml#l76 

there are high corner brackets above τ̣ῶ̣[ν, 

for low corner brackets see https://github.com/DCLP/dclpxsltbox/issues/120

**Comment by paregorios** [comment]
By "how to render" do you mean "how to encode in the XML"?

If so, what do these brackets look like and what do they signify? Are they addressed yet in either of the following google docs: 

 * [Symbol Sanity for DCLP](https://docs.google.com/a/nyu.edu/spreadsheets/d/15Lnu9THFkYpCCUJIfnq3_DCJw72ivjUhHu3GLJQWY1k/edit#gid=0)
 * [LitPapText](https://docs.google.com/a/nyu.edu/spreadsheets/d/1F6_Du8DIjixRD4mnvfpbkcn3E0H2_SfBIztCO6Vl6gQ/edit#gid=1879498412)

**Comment by andreabernini** [comment]
They can be used when the lacking of some letters is due to a damage in the papyrus. For instance, in Pap.Colon. 28.6 fr. III a/b recto, 14 λθα https://github.com/DCLP/idp.data/blob/dclp/DCLP/371/370029.xml#l78  
and 15: ] ὁ and, in the text added to the right, the π of περί 
https://github.com/DCLP/idp.data/blob/dclp/DCLP/371/370029.xml#l79

**Comment by andreabernini** [comment]
See also Pap.Colon. 28.16 verso, 12 (TM 65239)
https://github.com/DCLP/idp.data/blob/dclp/DCLP/66/65239.xml#l132 
the first letter of Χ̣ριστός

**Comment by HolgerEssler** [comment]
I am not sure, whether I have understood this meaning of the upper
square brackets correctly (and I do not have access to the edition at
the moment). However, if the letters are lost due to damage in the
papyrus would we not use "normal" square brackets (transforming to <gap
reason="lost" etc.)?
In the LitPapText spreadsheet, line 59
(https://docs.google.com/spreadsheets/d/1F6_Du8DIjixRD4mnvfpbkcn3E0H2_SfBIztCO6Vl6gQ/edit#gid=1879498412)
I requested U+23A1 and U+23A4 as markup for letters only preserved in
apographs (drawings in the case of Herculaneum Papyri).

**Comment by andreabernini** [comment]
The photo of Pap.Colon. 28.6 shows that the papyrus is preserved in correspondence of these letters, but it is bended on itself, so that they are not visible.

**Comment by HolgerEssler** [comment]
So it would mean that the letters are preserved, but not visible on the
photograph? If they became visible once the fibers were turned over
during restoration, I would encode them like any other letter.

**Comment by andreabernini** [comment]
This is what I understood. But encoding them 'normally' seems the best solution to me.

**Comment by paregorios** [comment]
So, do I understand correctly that, in a case such as Pap.Colon. 28.6 there will be no additional tagging around the letters that are in fact on the papyrus but not visible on the photo, even though the printed edition uses high corner brackets for this purpose? That's how I read the above discussion, and what I would expect for normal EpiDoc.

**Comment by HolgerEssler** [comment]
That was my understanding as well. Should I create a separate issue for
upper square brackets in Herculaneum texts as described above?

**Comment by paregorios** [comment]
@HolgerEssler if there is not already such a ticket, then yes please do.

**Comment by HolgerEssler** [comment]
Done as https://github.com/DCLP/dclpxsltbox/issues/138#.

**Comment by paregorios** [comment]
Since this issue is sorted, I recommend we close. OK @andreabernini and @HolgerEssler ?

**Comment by HolgerEssler** [comment]
ok

**Comment by andreabernini** [comment]
OK!

2015-05-12 21:31 GMT+02:00 HolgerEssler <notifications@github.com>:
