### ISSUE TITLE
handle biblScope type="pp" in bibliographic citations

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#132]
Via @jcowey in Skype. 

E.g., [TM 108908](https://github.com/DCLP/idp.data/blob/dclp/DCLP/109/108908.xml), which makes reference to [biblio 75990](https://github.com/DCLP/idp.data/blob/dclp/Biblio/76/75990.xml). In the XML for the latter, [pages are indicated at line 9](https://github.com/DCLP/idp.data/blob/dclp/Biblio/76/75990.xml#L9), but not expressed in [the HTML output](https://github.com/DCLP/dclpxsltbox/blob/b3be6d1f128db2698ae77bec0b7f327aab10648d/output/dclp/109/108908.html).

It looks like [the place to intervene in code is here...](https://github.com/DCLP/navigator/blob/master/pn-xslt/htm-teibibl.xsl#L100), though I wonder if @hcayless has any thoughts about that, e.g., whether we should insulate the other collections from experiencing this change, or let this be a change that would easily roll through all collections, not just dclp.

**Comment by cgajjar05** [comment]
Resolved this issue.
