### ISSUE TITLE
ordering of bibl output

### ISSUE THREAD

**Issue by rla2118** [DCLP/dclpxsltbox#135]
In connection with the ordering of bibl output, Tom asks, "Would some other model be preferred in the HTML output, e.g., by date or grouped by type then sorted by date) see also e.g., TM 59749 (Epicurus, De natura; Herculaneum)?"  

My inclination is to group by type sorted by date, with types perhaps arranged thus:

Principal Edition
Reference Edition
Partial Edition
Previous Edition
Readings    

Rodney

**Comment by paregorios** [comment]
@rla2118 should we check with other papyrologists on this before implementing, or just go ahead?

**Comment by HolgerEssler** [comment]
I agree with Rodney's suggestion, but would group "readings" before
"previous edition", because "readings" contain textual notes published
after the "reference edition" (and therefore not taken into account
there) whereas every "previous edition" has been superseeded by the
"reference edition".
The order of the groups would be thus:

Principal Edition
Reference Edition

Partial Edition

Readings

Previous Edition

Holger

**Comment by rla2118** [comment]
I'm fine with Holger's suggestion and think you can go ahead and implement
it, Tom.  Nevertheless, I still don't quite understand what is meant by
*reference edition and how it differs from *principal edition.

Rodney

**Comment by rogerbagnall** [comment]
I suppose that a principal edition might be what we tend to call editio 
princeps in the trade. Supposing a papyrus were published with very full 
commentary that remains useful, but with some significant problems of 
reading. A subsequent edition corrects these readings and is used for 
citation. I think, for example, on the documentary front of something 
published in a journal article, which one might think of as a principal 
edition, and in SB, which is the reference edition.

But perhaps someone else meant something entirely different by this!

On 5/2/15 3:35 PM, rla2118 wrote:
> I'm fine with Holger's suggestion and think you can go ahead and implement
> it, Tom. Nevertheless, I still don't quite understand what is meant by
> *reference edition and how it differs from *principal edition.
>
> Rodney
>
> On Fri, May 1, 2015 at 8:00 PM, HolgerEssler <notifications@github.com>
> wrote:
>
> > I agree with Rodney's suggestion, but would group "readings" before
> > "previous edition", because "readings" contain textual notes published
> > after the "reference edition" (and therefore not taken into account
> > there) whereas every "previous edition" has been superseeded by the
> > "reference edition".
> > The order of the groups would be thus:
> >
> > Principal Edition
> > Reference Edition
> >
> > Partial Edition
> >
> > Readings
> >
> > Previous Edition
> >
> > Holger
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/DCLP/dclpxsltbox/issues/135#issuecomment-98188594>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DCLP/dclpxsltbox/issues/135#issuecomment-98353637>.
>

-- 
Roger S. Bagnall
Leon Levy Director and Professor of Ancient History
Institute for the Study of the Ancient World
New York University
15 East 84th St.
New York, NY  10028
1-212-992-7833

**Comment by paregorios** [comment]
In work in branch https://github.com/DCLP/navigator/tree/issue135

**Comment by paregorios** [comment]
As of [this commit](https://github.com/DCLP/navigator/commit/888ec28bdff5d942850fc0a709463e30879ae38d) we're successfully grouping by type and handling header and content output properly. Next steps: ordering the groups and sorting within groups.

**Comment by paregorios** [comment]
The working branch for this issue was merged into the branch for #156 with commit https://github.com/DCLP/navigator/commit/095cbfbe6a0993dff3a83bc8185a40afa2401018, which was subsequently merged into other branches (including those for #106 and #185) and ultimately incorporated into master with commit https://github.com/DCLP/navigator/commit/7ff95f39c422c952852ed06e4039e9e6baa4c389.

Now the question is: are we seeing what we want in output?

**Comment by paregorios** [comment]
Inspection of HTML output demonstrates that references of like type are grouped together, but these groups are not presented in the order specified above. Moreover, I think it would be good to display references of a given type in an unordered list under a single edition-type rubric.

So, two tasks remain:

- [ ] Emit each edition-type group in the order [specified above](https://github.com/DCLP/dclpxsltbox/issues/135#issuecomment-98188594) by @HolgerEssler 
- [ ] Group citations within each edition-type under a single heading, just like we've done when we encounter multiple works (see #104)

**Comment by paregorios** [comment]
I have deleted the old, previously merged branch for this ticket and I have created and pushed [a new branch (issue135-bis)](https://github.com/DCLP/navigator/tree/issue135-bis) for the additional work outlined above.

**Comment by wsalesky** [comment]
@paregorios Is there a group of TEI records that you have been using to test this sort feature on?

**Comment by paregorios** [comment]
@wsalesky These have principal edition, reference edition, and previous edition together:

 - 59137
 - 63306
 - 63976
 - 64757
 - 64896

These have everything except principal edition:

 - 59468
 - 59749
 - 59754
 - 62390
 - 62393
 - 62394
 - 62400
 - 62402
 - 62411
 - 62419
 - 62429
 - 62433
 - 62436
 - 62437
 - 62439
 - 62445
 - 62448
 - 62460
 - 62471
 - 62474
 - 62476
 - 62477
 - 62478
 - 62511
 - 65542

**Comment by wsalesky** [comment]
@paregorios 
Just to clarify, we want a single heading with each item in the group in a `<ul>` and sorted by date? Or just output in document order?

**Comment by wsalesky** [comment]
**XSLT changed:** `pn-xslt/metadata-dclp.xsl` and `pn-xslt/pi-functions.xsl`
I added grouping, sorting groups using a new function  `pn-xslt/pi-functions.xsl`  in `pi:bibl-type-order()` to follow the order requested above, and then sorting within each group by date. 

**Branch** 
`https://github.com/DCLP/navigator/tree/issue135-bis`

**Sample diff:**
```
diff --git a/output/dclp/108/107918.html b/output/dclp/108/107918.html
index 0aa60a86ef..d13ef18eec 100644
--- a/output/dclp/108/107918.html
+++ b/output/dclp/108/107918.html
@@ -57,11 +57,12 @@
                                  </tr>
                                  <tr>
                                     <th>Principal Edition</th>
-                                    <td>BKU 1 165</td>
-                                 </tr>
-                                 <tr>
-                                    <th>Principal Edition</th>
-                                    <td>BKU 1 166</td>
+                                    <td>
+                                       <ul class="biblList">
+                                          <li> - BKU 1 165</li>
+                                          <li> - BKU 1 166</li>
+                                       </ul>
+                                    </td>
                                  </tr>
diff --git a/output/dclp/110/109375.html b/output/dclp/110/109375.html
index 0b9d2ddec4..d939e3cae1 100644
--- a/output/dclp/110/109375.html
+++ b/output/dclp/110/109375.html
@@ -56,13 +56,13 @@
                                     <td>Chrysippus; peri ton stoicheion ton legomenon, with end title</td>
                                  </tr>
                                  <tr>
-                                    <th>Partial Edition</th>
-                                    <td>Gianluca Del Mastro, <i>Un'opera logica di Crisippo nel PHerc. 1380</i>, (Helsinki 2007). 
+                                    <th>Reference Edition</th>
+                                    <td><b>83418. </b>Gianluca Del Mastro, "Il PHerc. 1380: Crisippo, Opera logica," <i><a href="/biblio/184/">Cronache Ercolanesi</a></i>, 35 (2005), pp. 61-70. [leer]
                                     </td>
                                  </tr>
                                  <tr>
-                                    <th>Reference Edition</th>
-                                    <td><b>83418. </b>Gianluca Del Mastro, "Il PHerc. 1380: Crisippo, Opera logica," <i><a href="/biblio/184/">Cronache Ercolanesi</a></i>, 35 (2005), pp. 61-70. [leer]
+                                    <th>Partial Edition</th>
+                                    <td>Gianluca Del Mastro, <i>Un'opera logica di Crisippo nel PHerc. 1380</i>, (Helsinki 2007). 
                                     </td>
                                  </tr>
```

@paregorios ready for review.

**Comment by paregorios** [comment]
resolved and merged
