### ISSUE TITLE
Upper square brackets for marking up readings from apographs

### ISSUE THREAD

**Issue by HolgerEssler** [DCLP/dclpxsltbox#138]
Cf. the LitPapText spreadsheet, line 59
(https://docs.google.com/spreadsheets/d/1F6_Du8DIjixRD4mnvfpbkcn3E0H2_SfBIztCO6Vl6gQ/edit#gid=1879498412)
U+23A1 and U+23A4 should be introduced as markup for letters only preserved in
apographs (drawings in the case of Herculaneum Papyri), but now lost in the original papyrus.
Leiden+ and Display should read:
ταὐτ⌈ὸ⌉
corresponding xml:
ταὐτ< supplied reason="undefined" evidence="apograph">ὸ< /supplied>

**Comment by wsalesky** [comment]
It looks like there is currently only one file marked up with `<supplied reason="undefined" evidence="apograph">`

xml: `/dclp/63/62433.xml`

XSLT: 
Added a new template for `t:supplied[@evidence='apograph']` in `epidoc-xslt/teisupplied.xsl`

HTML:
A few examples in the html: 
```
diff --git a/output/dclp/63/62433.html b/output/dclp/63/62433.html
index a5133c6e1..b7f4ddbca 100644
--- a/output/dclp/63/62433.html
+++ b/output/dclp/63/62433.html
@@ -270,7 +270,7 @@

- id="a2-l17">ὑπάρχον
+ id="a2-l17">⌈ὑ⌉πάρχον

- id="a2-l18">εἶναι δὲ
+ id="a2-l18">⌈εἶν⌉αι ⌈δὲ⌉ 

- id="a2-l22">δαῖον
+ id="a2-l22">⌈δα⌉ῖον

- id="a2-l23">ὁ μὲν ἄνθρω
+ id="a2-l23">⌈ὁ⌉ ⌈μὲν⌉ ⌈ἄνθρω⌉

- id="a2-l24">π[ρ]ὸς οὐδεμ̣ίαν
+ id="a2-l24">⌈π⌉[ρ]⌈ὸς⌉ ⌈οὐδεμ̣ίαν⌉

```

@paregorios  this one is ready for review.
