### ISSUE TITLE
Text visible to previous editor, but now lost

### ISSUE THREAD

**Issue by HolgerEssler** [DCLP/dclpxsltbox#139]
According to the documentation (e.g. Cheatsheet by G. Bodard) Leiden+ offers a way to mark up text that was visible to previous editors, but is now lost in the original.
Leiden+:
-[asd]-
XML:
< supplied reason="undefined" evidence="previouseditor">αβγ< /supplied>
The xml is valid, 
required: add above to Leiden+(XSugar) 
add way of displaying (one solution might be underlining the letters concerned in html output)

**Comment by wsalesky** [comment]
There are currently no records with this encoding. I'm will hold off on XSLT changes until there are some records to test on.

**Comment by paregorios** [comment]
@HolgerEssler @rla2118 @rogerbagnall @jcowey if we want this feature worked on, we're going to need an example text with appropriate encoding added to the master branch on DCLP/idp.data.

**Comment by paregorios** [comment]
per discussion assigning to @jcowey to resolve ambiguities about encoding and examples

**Comment by paregorios** [comment]
/me to add comments and resolution here based on outcome of conversation today with @jcowey

**Comment by paregorios** [comment]
There are mechanisms in place for constructing apparatus entries with lemmata and readings and for associating those readings with particular editions. Such constructs are sufficient, and probably to be preferred to this method. Won't fix.
