### ISSUE TITLE
Leiden+: clear, but incomprehensible letters

### ISSUE THREAD

**Issue by HolgerEssler** [DCLP/dclpxsltbox#141]
This is listed on G. Bodards cheatsheet, valid xml, but not implemented in Leiden+ converter and not displayed.
a) Desired display:
ABC
b) Suggested Leiden+:
G. Bodard suggests =abc=, but to the papyri.info editor documentation, the equals sign indication is not for `<orig>` but for letters both underlined and overlined: =εὐτύχει=. 
I wonder whether we should change Leiden+ for "underlined and overlined" to a combination of the single tags supraline + underline, i.e. ¯_ εὐτύχει _¯, and use the equals sign in the way G. Bodard suggests. Alternatively I propose `< :|abc:>` in analogy to other apparatus entries like `<:abc|reg|cba:>` where the `< orig>` element is used in combination with others.

c) XML (valid):
`< orig>abc</orig>`

**Comment by leoba** [comment]
@paregorios has an official decision been made about this suggestion?

**Comment by rla2118** [comment]
Ι would be fine following Gabby on this and changing underlined/overlined,
but combining supraline+underline would be difficult on most keyboards, I
fear.  What about something like ¯abc_?  James, what do you think?

**Comment by paregorios** [comment]
@jcowey please see query from @rla2118 immediately above.

**Comment by leoba** [comment]
@paregorios @jcowey checking again to see if there's a change to make yet to the XSLT.

**Comment by paregorios** [comment]
@jcowey?

**Comment by paregorios** [comment]
pinging @jcowey for comments so that we can queue this item for work

**Comment by paregorios** [comment]
We cannot work on this ticket until the following issues are resolved:

 1. What display do we want to see in HTML for e.g., ```<orig>φες</orig>```? The options are:

    a. ```φες``` -- this is current behavior, as in TM63138, fragment 10, line 11: 
```<lb n="11" break="no"/><orig>ν</orig></w> <w n="1000010000011001" lemma="ὁ">τὸ</w> <w n="1000010000011002" type="incomplete"><orig>συλ</orig><gap n="9000010000011001" reason="lost" quantity="1" unit="character"/><orig>φες</orig></w>```
 in XML yields 
```ν τὸ συλ[  ̣]φες``` in HTML

    b. ```ΦΕΣ``` -- this is the convention in most epigraphic Greek and Latin EpiDoc projects. 

    c. something else (what?)

2. What Leiden+ should be implemented to facilitate markup like this? A couple of suggestions have been made by @HolgerEssler and @rla2118 above, and a question (as yet unanswered) posed to @jcowey. 

We need a papyrological member of the team to make a decision on what to do about both the HTML rendering and the Leiden+ convention before any work can be done on this item.

**Comment by HolgerEssler** [comment]
From the above I think that @rla2118 and I agree to use b. ΦΕΣ for HTML-display and to have =φες= as the corresponding Leiden+.
The only question is about how to change Leiden+ for "underlined and overlined". I have no problems with the suggestion by @rla2118 to use something like ¯abc_ , except that it is not symmetric. My suggestion of a combination of the single tags supraline + underline, i.e. ¯ and _  was intended to use one after the other, i.e. ¯_abc_¯, but I think this is not crucial and I am happy with any solution @rla2118   or @jcowey prefer.

**Comment by paregorios** [comment]
per discussion @rla2118 and @jcowey I will take charge of this ticket to split for XSLT and Leiden+ concerns and to make a suggestion about resolving the latter.

**Comment by paregorios** [comment]
Now that #243 has been split out to address the XSLT aspects of this matter, this ticket (#141) remains the locus for discussing Leiden+ modifications related to "clear but incomprehensible letters"

**Comment by paregorios** [comment]
The task now on this ticket is to look at what's already spoken for in terms of characters in Leiden+ and suggest something intuitive for this purpose.

**Comment by paregorios** [comment]
What about ```!abc!```?

**Comment by paregorios** [comment]
This now works in the editor at litpap.info.
