### ISSUE TITLE
Duplicate Reference Edition

### ISSUE THREAD

**Issue by rla2118** [DCLP/dclpxsltbox#143]
The reference edition, # 83376, is being duplicated at https://dclp.github.io/dclpxsltbox/output/dclp/62/61438.html

**Comment by paregorios** [comment]
This appears to be an XML problem; the bibliographic entry for reference edition appears twice in the XML:

https://github.com/DCLP/idp.data/blob/dclp/DCLP/62/61438.xml#L188

**Comment by paregorios** [comment]
@jcowey how best to fix?

**Comment by paregorios** [comment]
@jcowey what should the priority for this task be and to whom should it be assigned? Does it really belong in the April 2017 milestone, or should it be moved to the backlog and higher priority items addressed first (i.e., those that affect many files instead of a single file)?

**Comment by paregorios** [comment]
per @jcowey this is an issue for @HolgerEssler to check and resolve

**Comment by HolgerEssler** [comment]
XML corrected. Suggest closing.
