### ISSUE TITLE
add TM "book" field data to XML

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#145]
[As identified in discussion on issue 105](https://github.com/DCLP/dclpxsltbox/issues/105#issuecomment-68785314), @rogerbagnall @rla2118 et al. would like to see this data added.

**Comment by jcowey** [comment]
Probably find a place for this information in:
```
<profileDesc>
         <textClass>
            <keywords>
               <term>prose</term>
               <term>gospel</term>
               <term type="culture">literature</term>
               <term type="religion">christian</term>
            </keywords>
         </textClass>
      </profileDesc>

```

**Comment by jcowey** [comment]
XSLT will have to be modified in order to display this information.

**Comment by paregorios** [comment]
@jcowey has this data been added to the XML files yet? If not, then nothing should be done about XSLT in my opinion until we have actual data upon which to operate and test.

**Comment by jcowey** [comment]
see comment from 20 May on where to get the relevant information to add to the files

**Comment by jcowey** [comment]
This has now be added to the XML through commit:
https://github.com/DCLP/idp.data/commit/3eb60d7ec831ef02f03c548c61d0bd2a9aa23337

**Comment by jcowey** [comment]
The XML now looks like this:

https://github.com/DCLP/idp.data/blob/dclp/DCLP/106/105709.xml#L61-L71
```

```

**Comment by jcowey** [comment]
```
      <profileDesc>
         <textClass>
            <keywords>
               <term>hymn</term>
               <term>prayer</term>
               <term>litany</term>
               <term type="culture">religion</term>
               <term type="culture">literature</term>
               <term type="religion">classical</term>
               <term type="religion">Egyptian</term>
               <term type="overview">hymns to Sobek-Re and Hathor</term>
            </keywords>
         </textClass>
</profileDesc>
```

**Comment by jcowey** [comment]
The XSLT will have to retrieve and display the content of
https://github.com/DCLP/idp.data/blob/dclp/DCLP/1/555.xml#L78

`<term type="overview">hymns to Sobek-Re and Hathor</term>`

**Comment by jcowey** [comment]
Here is an example.
http://litpap.info/dclp/62823
Display is:
```
DCLP/LDAB Data [xml]
  Work 	        Theognis, Elegiae
  Fragments 	Berlin, Ägyptisches Museum P. 12310
```

**Comment by paregorios** [comment]
Right, so once someone decides what the rubric should be, we can undertake to implement this.

**Comment by jcowey** [comment]
exactly I have to talk to Rodney and Holger then I can let you know what we would like to have done

**Comment by rla2118** [comment]
I'm fine with "content" as the rubric.

**Comment by HolgerEssler** [comment]
I agree with Rodney and James' suggestion of how to proceed.

**Comment by jcowey** [comment]
Tom, would you please go ahead and make the relevant XSLT change to display the data.

**Comment by jcowey** [comment]
Rubric `Content` is filled with the content of the tag `<term type="overview">`
`Content` comes after `Work` if Work is present, otherwise `Content` takes first position.

**Comment by paregorios** [comment]
Rock and roll big daddy!

**Comment by paregorios** [comment]
I will undertake to make the XSLT work accordingly.

**Comment by paregorios** [comment]
@jcowey @HolgerEssler @rla2118 does the output now available for review at http://dclp.github.io/dclpxsltbox/output/dclp/ reflect, in your view, the changes we were seeking above? Some examples (but has been applied throughout):

 - http://dclp.github.io/dclpxsltbox/output/dclp/1/555.html
 - http://dclp.github.io/dclpxsltbox/output/dclp/100/99548.html
 - http://dclp.github.io/dclpxsltbox/output/dclp/218/217927.html
 - http://dclp.github.io/dclpxsltbox/output/dclp/99/98082.html

**Comment by HolgerEssler** [comment]
I have checked a random sample and the results look fine to me.

**Comment by jcowey** [comment]
http://dclp.github.io/dclpxsltbox/output/dclp/100/99548.html
Principal Edition 	514 P. Lond. Copt.
should be 
Principal Edition 	P. Lond. Copt. 514

https://github.com/DCLP/idp.data/blob/dclp/DCLP/100/99548.xml#L88-L92

has changed because the biblio id

https://github.com/DCLP/idp.data/blob/dclp/DCLP/100/99548.xml#L89

has been added instead of

<title level="s" type="abbreviated">P. Lond. Copt.</title>

but the information is available from the file at

https://github.com/DCLP/idp.data/blob/dclp/DCLP/100/99548.xml#L92

Sorry. mea culpa. not transferring news about change to XML which has knock on effects for XSLT.

Would you please change the XSLT accordingly. That is read out 
content of 
https://github.com/DCLP/idp.data/blob/dclp/DCLP/100/99548.xml#L91-L93
<title level="s" type="abbreviated">.+</title>
before reading out content of 
https://github.com/DCLP/idp.data/blob/dclp/DCLP/100/99548.xml#L90
biblScope unit="number" etc

Otherwise these are looking good

**Comment by paregorios** [comment]
What @jcowey has identified [here](https://github.com/DCLP/dclpxsltbox/issues/145#issuecomment-267089950) is, to my mind, an issue separate from that of displaying the "overview" terms as "content", which is the point of the present thread. OK if I go ahead and create a new issue for it?

**Comment by rla2118** [comment]
I agree with Tom that this is a different topic requiring a new issue.

The sample files I checked seem fine for 'content'.

**Comment by paregorios** [comment]
I will merge the code changes for this issue to the appropriate branch for production. Meanwhile, I have created a new issue (#191) for the problem with order in principal edition components [as identified above](https://github.com/DCLP/dclpxsltbox/issues/145#issuecomment-267089950) by @jcowey .

**Comment by jcowey** [comment]
This issue was about adding the data from the tag
```<term type="overview">...</term>```
to what we call ```content```in the display.
That has been done fine. We are satisfied, so I would suggest closing this issue. We now have #191 to work on.

**Comment by paregorios** [comment]
I would like to keep this issue open until the code has been merged for deployment.

**Comment by jcowey** [comment]
OK fine

**Comment by paregorios** [comment]
This was deployed to production stream with [navigator XSLT commit 880fcec](https://github.com/DCLP/navigator/commit/880fcecf8078ba516893502238bec0de9e6a8831). To see these changes at http://litpap.info/, the navigator XSLT will need to be updated to at least the above-referenced commit.

Updated XSLT review files were pushed to http://dclp.github.io/dclpxsltbox/output/dclp/ with dclpxslt gh-pages commit ded7ff934e70c5145d6bedd2fa0c5fc22194d5b6.

Reassigning ticket to @jcowey for disposition on deployment of updated code to http://litpap.info/

**Comment by paregorios** [comment]
This code is clearly on production and producing output as expected, so closing ticket.
