### ISSUE TITLE
whitespace and formatting issues in bibliographic dates and page numbers

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#146]
This should be a minor XSLT intervention. There's whitespace inside parentheses around years on journal articles and no whitespace (nor punctuation) between page numbers and the preceding parts of the citations.

**Comment by leoba** [comment]
I'd like to work on this, but when I grep level="j" on idp.data/DCLP I get nothing (although I do get many hits on level="m" and level="s") - it looks like there aren't any citations to journal articles (although the htm-teibibl.xsl file has references to level="j", so it's expecting them to be there). I'm in the dclp branch of idp.data. Should I be using another branch?

**Comment by jcowey** [comment]
Is this where you are?
https://github.com/DCLP/idp.data/tree/dclp/Biblio

**Comment by jcowey** [comment]
I am a bit puzzled that you are not getting results for ```<title level="j"```
Or I am misunderstanding something

**Comment by leoba** [comment]
I was just coming back to say that I was, in fact, looking in DCLP, not in Biblio - which would explain my confusion. I hadn't looked in Biblio yet - still very new here and working out where things are.

**Comment by jcowey** [comment]
No problem! Glad to have pushed you in the right direction. :)

**Comment by paregorios** [comment]
DCLP has a lot of fun with cross-references...

**Comment by jcowey** [comment]
:)

**Comment by leoba** [comment]
@paregorios if you can add an example pointing to a specific file that would be very helpful.

**Comment by leoba** [comment]
@paregorios I've been trying to find an example of this and I can't. I am however finding other issues:

In Bibl files, if page numbers for journal articles are only in @from and @to values on biblScope and not in the content of biblScope, they do not display. Compare:

https://github.com/DCLP/idp.data/blob/master/Biblio/81/80929.xml#L7 (HTML: https://github.com/DCLP/dclpxsltbox/blob/master/output/dclp/65/64713.html#L46)

with

https://github.com/DCLP/idp.data/blob/master/Biblio/66/65876.xml#L13
(HTML: https://github.com/DCLP/dclpxsltbox/blob/master/output/dclp/101/100149.html#L46)

Is this an XSLT issue or an XML issue?

Also, there is something going on here; the date displays twice (once in parenthesis, once out) and although there are page numbers indicated they are not displaying (there is an empty "pp. ." instead):

https://github.com/DCLP/idp.data/blob/master/Biblio/79/78209.xml#L12-L23 (HTML: https://github.com/DCLP/dclpxsltbox/blob/master/output/dclp/101/100062.html#L46)

I will need to look into this more to see what is going on.

Should these be separate issues? I haven't checked to see if these have already been caught but they don't look familiar to me.

**Comment by paregorios** [comment]
@leoba I think we should break each of the concerns [you've identified above](https://github.com/DCLP/dclpxsltbox/issues/146#issuecomment-177643786) out as separate tickets.

I am looking for a whitespace example for you.

**Comment by paregorios** [comment]
Original ticket is actually two separate issues, so I'm going to split them out along with the two new ones identified by @leoba

**Comment by paregorios** [comment]
closing this ticket as all separate issues herein have been broken out as separate issue tickets.
