### ISSUE TITLE
Text added above the line (within another tag)

### ISSUE THREAD

**Issue by andreabernini** [DCLP/dclpxsltbox#147]
P.Oxy. 71.4808 (TM 112363) col. II 31-33
https://github.com/DCLP/idp.data/blob/dclp/DCLP/113/112363.xml#l158
https://github.com/DCLP/idp.data/blob/dclp/DCLP/113/112363.xml#l159
https://github.com/DCLP/idp.data/blob/dclp/DCLP/113/112363.xml#l160

Leiden+

```
<:κ[αὶ πᾶν τὸ]
32. πολυμαθὲς δ[ιαφαίνε]
33.- τ̣[αι] μὴ μόνα \ε/ἰ[ς τὴν]=W. Luppe, ZPE 163 (2007) 40|ed|κ[ca.8]32. πολυμαθὲς δ[ca.9]33. .1[.1]μ̣ημονα\ε/.1[ca.9]:>
```

Displayed in the apparatus

```
W. Luppe, ZPE 163 (2007) 40 : κ[- ca.8 -] | πολυμαθὲς δ[- ca.9 -] |   ̣[  ̣]μ̣ημονα\ε (  ̣[- ca.9 -]ε corr. ex )  ̣[- ca.9 -] prev. ed.
```

Expected

```
W. Luppe, ZPE 163 (2007) 40 : κ[- ca.8 -] | πολυμαθὲς δ[- ca.9 -] |   ̣[  ̣]μ̣ημονα\ε/  ̣[- ca.9 -] prev. ed.
```

**Comment by andreabernini** [comment]
P.Oxy. 75.5045,14 (TM 128972)
https://github.com/DCLP/idp.data/blob/dclp/DCLP/129/128972.xml#l91

Leiden+
<:ποδῶν|subst|π\ α(´)/α\ο/δων:>

Displayed in the apparatus:
corr. ex π\α(ά) (α\ο (δωνο corr. ex )δωνα(ά) corr. ex )α\ο (δωνο corr. ex )δων

Expected:
corr. ex π\α/\ο/δων : (ά) papyrus

**Comment by andreabernini** [comment]
P.Oxy. 75.5023 (TM 128952) part A, 8
https://github.com/DCLP/idp.data/blob/dclp/DCLP/129/128952.xml#l97 

Leiden+: <:\δ̣/ έ(´)ξῃ|corr|\δ̣/ ή(´)ξι:>

Displayed in the apparatus: l. \δ̣ (έξῃδ̣ corr. ex )έ(έ)ξῃ (corr) : ήξι papyrus

Expected: l. \δ̣/έξῃ (corr.) : ήξι papyrus

**Comment by wsalesky** [comment]
@paregorios @andreabernini 
I have checked the listed records and this seems to have been resolved. Would you mind double checking for me? 

See: 
http://dclp.github.io/dclpxsltbox/output/dclp/129/128952.html
http://dclp.github.io/dclpxsltbox/output/dclp/129/128972.html
http://dclp.github.io/dclpxsltbox/output/dclp/113/112363.html

If it has been resolved we can close the ticket, if not, can we add some new example data that illustrates the remaining issue? 

Thanks!

**Comment by paregorios** [comment]
@rla2118 @jcowey @HolgerEssler would one of you please have a look at the 3 links provided above by @wsalesky, as well as any other examples you know of and care to check ... are you happy with the results of the transform as far as "text added above the line" is concerned?

**Comment by HolgerEssler** [comment]
The examles look fine to me. Suggest closing.

**Comment by paregorios** [comment]
Thanks @HolgerEssler

**Comment by wsalesky** [comment]
Thanks @HolgerEssler and @paregorios
