### ISSUE TITLE
Superfluous displaying of square brackets

### ISSUE THREAD

**Issue by andreabernini** [DCLP/dclpxsltbox#148]
In P.Oxy. 71.4808 (TM 112363), within the tag `|alt|`, square brackets superfluously appear in this way: `[]`

https://github.com/DCLP/idp.data/blob/dclp/DCLP/113/112363.xml#l129
https://github.com/DCLP/idp.data/blob/dclp/DCLP/113/112363.xml#l130
https://github.com/DCLP/idp.data/blob/dclp/DCLP/113/112363.xml#l131

Leiden+

```
<:[ca.12]
4. τωι γὰρ συν[ca.10] [Ἀ]
5.- λεξάνδρου .1[ca.10]|alt|<:[ἐπὶ τού]4.- τωι γὰρ συν[έγραψε τὰς Ἀ]5.- λεξάνδρου π̣[ράξεις] [ca.4]=C. Pelling, see Chr. S. Chrysanthou, ZPE 193 (2015) 30|ed|[Ἀλεξάνδρωι, Κλει]4.- τῶι γὰρ συν[ῆν τῶι ἀδελφῶι Ἀ]5.- λεξάνδρου, .1[ca.6]:>:>
```

Displayed

```
[- ca.12 -]
4 τωι γὰρ συν[- ca.10 - Ἀ-]
5 λεξάνδρου   ̣[- ca.10 -](*)[]
```

Expected

```
4 τωι γὰρ συν[- ca.10 - Ἀ-]
5 λεξάνδρου   ̣[- ca.10 -](*)
```

**Comment by paregorios** [comment]
[This is still happening in current transforms (column ii, ll. 4-5)](http://dclp.github.io/dclpxsltbox/output/dclp/113/112363.html).

**Comment by wsalesky** [comment]
@paregorios 
I think I could use a little regex help here. I have tracked the problem down:

The current rule to suppress preceding adjacent gap of the same kind.  
`<xsl:if test="not(preceding::node()[1][self::text()][normalize-space(.)=''][preceding-sibling::node()[1][self::t:gap[@reason='lost']]]) and not(preceding::node()[1][self::t:gap[@reason='lost']])">`

This rule perhaps inadvertently also suppresses `t:gap` elements with no preceding siblings. 
See (second `t:app`, first descendant `t:gap` is causing the empty brackets):
  ```
<app type="alternative">
        <lem>
            <gap reason="lost" quantity="12" unit="character" precision="low"/>
            <lb n="4"/>τωι γὰρ συν
            <gap reason="lost" quantity="10" unit="character" precision="low"/> 
            <supplied reason="lost">Ἀ</supplied>
            <lb n="5" break="no"/>λεξάνδρου 
            <gap reason="illegible" quantity="1" unit="character"/>
            <gap reason="lost" quantity="10" unit="character" precision="low"/>
        </lem>
        <rdg>
            <app type="editorial">
                <lem resp="C. Pelling, see Chr. S. Chrysanthou, ZPE 193 (2015) 30">
                <supplied reason="lost">ἐπὶ τού</supplied>
                    <lb n="4" break="no"/>τωι γὰρ συν<supplied reason="lost">έγραψε τὰς Ἀ</supplied>
                    <lb n="5" break="no"/>λεξάνδρου 
                    <unclear>π</unclear>
                    <supplied reason="lost">ράξεις</supplied> 
                    <gap reason="lost" quantity="4" unit="character" precision="low"/>
                </lem>
                <rdg>
                    <supplied reason="lost">Ἀλεξάνδρωι, Κλει</supplied>
                    <lb n="4" break="no"/>τῶι γὰρ συν
                    <supplied reason="lost">ῆν τῶι ἀδελφῶι Ἀ</supplied>
                    <lb n="5" break="no"/>λεξάνδρου, 
                    <gap reason="illegible" quantity="1" unit="character"/>
                    <gap reason="lost" quantity="6" unit="character" precision="low"/>
                </rdg>
            </app>
        </rdg>
    </app>
    <app type="alternative">
        <lem>
            <gap reason="lost" quantity="9" unit="character" precision="low"/>
            <lb n="6"/>τε καὶ εἴκοσ<unclear>ι</unclear> 
            <gap reason="lost" quantity="10" unit="character" precision="low"/>
            <lb n="7"/>των παρε
            <gap reason="lost" quantity="13" unit="character" precision="low"/>
        </lem>
        <rdg>
            <num value="25">
                <supplied reason="lost">πέν</supplied>
                <lb n="6" break="no"/>τε καὶ εἴκοσ
                <unclear>ι</unclear>
            </num>
            <supplied reason="lost">γενόμενος ἐ</supplied>
            <lb n="7" break="no"/>τῶν παρ’ Ε
            <supplied reason="lost">ὐμένει</supplied> 
            <gap reason="lost" quantity="4" unit="character" precision="low"/>
        </rdg>
    </app>

```
When I added an additional XPath to include this use case, we ended up with some unintended duplicates:
see: [113/112364.xml](https://github.com/DCLP/idp.data/blob/master/DCLP/113/112364.xml#L100)

Which outputs: 

`  ̣ων̣[ -ca.?- -ca.?- ]`

The suppression of duplicates only compares siblings. We could strip the duplicate out via regex, (epic-xslt/htm-tpl-sqbrackets.xsl) but I may need some help writing the regex.

**Comment by wsalesky** [comment]
@paregorios 
Never mind, I figured it out. 
Changes are on:
http://svn.code.sf.net/p/epidoc/code/branches/dclp-issue148-b

Let me know how it looks. I did run a git diff, and there were a large number of changed files, the 10 or so I checked looked okay.

**Comment by paregorios** [comment]
I am working on checking this, being slow and careful to hunt for unexpected side-effects ...

**Comment by paregorios** [comment]
@wsalesky I attempted to rebase this against ```/branches/dclp/example-p5-stylesheets``` and ran into a conflict in ```teigap.xsl``` that would appear to be due to modifications made by @leoba for issue #55. Would you please have a look at what's going on there and attempt to resolve the conflict in a way that doesn't undermine the current behavior for #55?

**Comment by wsalesky** [comment]
I will take a look today.

**Comment by wsalesky** [comment]
I think #55 resolves this issue. So we can just delete this branch and close this ticket if you agree.
