### ISSUE TITLE
text added above the line not properly handled in apparatus generation

### ISSUE THREAD

**Issue by andreabernini** [DCLP/dclpxsltbox#150]
P.Oxy. 67.4555,814 (= TM 68628)

https://github.com/DCLP/idp.data/blob/master/DCLP/69/68628.xml

Leiden+: ```<:με̣\τ/α[λγεῖ]|subst|με̣.1\τ/α[λγεῖ]:>```

XML: ```<subst><add place="inline">μ<unclear>ε</unclear><add place="above">τ</add>α<supplied reason="lost">λγεῖ</supplied></add><del rend="corrected">μ<unclear>ε</unclear><gap reason="illegible" quantity="1" unit="character"/><add place="above">τ</add>α<supplied reason="lost">λγεῖ</supplied></del></subst>```

Displayed in the apparatus: ```corr. ex με̣  ̣\τ (α[λγεῖ]τ corr. ex )α[λγεῖ]```

Expected in the apparatus: ```corr. ex με̣  ̣\τ/α[λγεῖ]```

**Comment by wsalesky** [comment]
@andreabernini is this still an issue? It appears to be displaying as expected here:
http://dclp.github.io/dclpxsltbox/output/dclp/69/68628.html

**Comment by paregorios** [comment]
@rla2118 @jcowey @HolgerEssler could you please see [the request for confirmation from @wsalesky, above](https://github.com/DCLP/dclpxsltbox/issues/150#issuecomment-290947155), and reply accordingly?

**Comment by rla2118** [comment]
Yes, this does seem to be the expected display.  I suggest closing this ticket.
