### ISSUE TITLE
Displaying the tag “inverse”

### ISSUE THREAD

**Issue by andreabernini** [DCLP/dclpxsltbox#152]
It is accepted by the system, but not displayed: in P.Oxy. 75.5023 (TM 128952) part. C, 1 (and ff.), I would expect something like “(turned 180°)”
https://github.com/DCLP/idp.data/blob/master/DCLP/129/128952.xml#L164

Leiden+: 

```(1, inverse) (ἦ\χ/(ος)) <#β=2#> ```

XML:

```xml
<lb n="1" rend="inverse"/> <expan>ἦ<add place="above">χ</add><ex>ος</ex></expan> <num value="2">β</num>
```

[Displayed](http://dclp.github.io/dclpxsltbox/output/dclp/129/128952.html): 

```ἦ\χ/(ος) β```

(see now #251 for incorrect placement of hyphen; comments previously here have been moved there).

**Comment by paregorios** [comment]
@rla2118 @jcowey what do you want to see when a line is marked as inverse?

**Comment by rla2118** [comment]
I'm not sure how to display this.  A marginal note saying that text in the indicated lines is inverted? @HolgerEssler ?

**Comment by paregorios** [comment]
Per discussion with @jcowey and @rla2118, we probably need to address this in context with related indicators, which probably are not comprehensively or consistently addressed at this time in the XSLT. So, the following steps:

 - conduct a census of existing data to determine all values currently in use of the "rend" attribute on ```<lb>```
 - look at how (if at all) those values are addressed by the XSLT
 - propose a comprehensive solution that also takes in the question of inverse lines

**Comment by jcowey** [comment]
Here are the values from papyri.info
rend="perpendicular"
rend="inverse"

same values + break="no"
rend="perpendicular" break="no"
rend="inverse" break="no"

same values + xml:id
rend="perpendicular" xml:id="div1-lb21"
rend="inverse" xml:id="lb14"

and another one
rend="msup"

**Comment by paregorios** [comment]
per @jcowey "msup" may mean "manuscript superior" but we should ask Sosin. Also need to check full DCLP for these or other values.

**Comment by paregorios** [comment]
@wsalesky can you do a census of all files in idp.data (not just idp.data/DCLP) to see what all values appear in the "rend" attribute on ```<lb```?

**Comment by wsalesky** [comment]
I ran a distinct values on `//tei:lb/@rend` over all the data in idp.data the results are:

- eisthesis
- ekthesis
- inverse
- minf
- perpendicular
- msup

**Comment by paregorios** [comment]
@wsalesky thanks, can you give us a link to an example of each? That will allow @jcowey, @rla2118, @HolgerEssler, and @rogerbagnall to see how each is currently handled in HTML output, so that they can decide whether that's ok or whether something else should be done. If you get me the xml file links, I'll add links to the navigator HTML results.

**Comment by wsalesky** [comment]
Here you go:
eisthesis : https://github.com/DCLP/idp.data/blob/master/DCLP/120/119317.xml#L125
`<lb n="33" rend="eisthesis"/>`

ekthesis : https://github.com/DCLP/idp.data/blob/master/DCLP/120/119322.xml#L93
`<lb  n="3" rend="ekthesis"/>`

inverse : https://github.com/DCLP/idp.data/blob/master/DCLP/129/128952.xml#L164
`<lb n="1" rend="inverse"/>`

minf : https://github.com/DCLP/idp.data/blob/master/DCLP/65/64598.xml#L114
`<lb n="10" rend="minf" xml:id="div1-div2-lb11"/>`

perpendicular  :  https://github.com/DCLP/idp.data/blob/master/DDB_EpiDoc_XML/bgu/bgu.1/bgu.1.248.xml#L133
`<lb n="40,ms" rend="perpendicular"/>`

msup : https://github.com/DCLP/idp.data/blob/master/DDB_EpiDoc_XML/o.did/o.did.350.xml#L59
`<lb n="12" rend="msup"/>`

**Comment by wsalesky** [comment]
I can move forward with XSLT changes if I can get some examples of desired HML displays. Note: for a previous issue (#93 and #90) I added a class attribute to all `tei:lb` elements with a rend attribute, so all we need to do is add the appropriate CSS styles for each of the rend types listed above. 

Thanks.

**Comment by paregorios** [comment]
@jcowey @HolgerEssler @rla2118 @rogerbagnall we need a decision on what you want to see in the HTML when a line is marked as "inverse" in XML (see @wsalesky's request for same, above). Until we get that answer, we cannot resolve this ticket. Thanks.

**Comment by rla2118** [comment]
I'm not sure what to do.  I suggest above that we add a marginal note saying that text in the indicated lines is inverted. Other suggestions welcome!

**Comment by paregorios** [comment]
OK, I propose that we leave this ticket open for a day or two to see if there are any other suggestions, then we'll go ahead with what @rla2118 suggests. Meantime, adding an emoji "thumbs up" reaction to @rla2118's suggestion constitutes a "vote for" it (there's also a "thumbs down" option). Some indication by the other papyrologists that you concur, don't care, or demur (with alternate suggestion) will help things move along. Thanks.

**Comment by rogerbagnall** [comment]
I would agree that noting the position of the text in question is adequate. It's hard to think of any better way of handling it.

**Comment by HolgerEssler** [comment]
I agree with @rla2118  and @rogerbagnall on the note. Since the whole text fragment is upside down (cf. http://163.1.169.40/gsdl/collect/POxy/index/assoc/HASH0161/19c34a69.dir/POxy.v0075.n5023.b.01.hires.jpg), we should perhaps have a single note (referring to the whole `<div>`?) instead of marking each line separately.

**Comment by paregorios** [comment]
@wsalesky let's proceed with the following:

 - For ```<lb rend="inverse"```, output: "(inverse)" at the beginning of the line.
 - For ```<lb rend="perpendicular"```, output: "(perpendicular)" at the beginning of the line.

I will undertake to create separate tickets for "mimf" and "msup".

**Comment by wsalesky** [comment]
**XSLT Changed:**  `epidoc-xslt/example-p5-xslt/htm-teilb.xsl`
Added xsl:choose for rend='inverse' and rend='perpendicular'

**Branch:** 
`https://github.com/DCLP/epidoc-xslt/tree/issue152`

**HTML Changed:** 
`modified:   output/dclp/129/128952.html`

**HTML diff:**
```
diff --git a/output/dclp/129/128952.html b/output/dclp/129/128952.html
index f6e0e59ea9..f8fb7ccbe1 100644
--- a/output/dclp/129/128952.html
+++ b/output/dclp/129/128952.html
@@ -150,7 +150,7 @@
                                  <!--0--></a><span title="number: 71">οα̣</span><a href="#to-app-subst01" id="from-app-subst01">(*)</a><br id="aB-l5"><span class="linenumber">5</span>κ(αὶ) καταβήσετε<a href="#to-app-choice20" id="from-app-choice20">(*)</a><br id="aB-l6">ὡς ἱετὸς<a href="#to-app-choice21" id="from-app-choice21">(*)</a> ἐπὶ ((mese-stigme)) &lt;πὸκον&gt;<br id="aB-l7">κ(αὶ) ὡσὶ<a href="#to-app-choice22" id="from-app-choice22">(*)</a> ε̣ταγό-<br id="aB-l8">νες<a href="#to-app-choice23" id="from-app-choice23">(*)</a> τάζουσι(ν)<a href="#to-app-choice24" id="from-app-choice24">(*)</a><br id="aB-l9">ἐπὶ τὴν γῆν <br>————————<br id="aB-l10"><span class="linenumber">10</span><span title="number: 79">οθ</span><br id="aB-l11">ἐ̣ξ̣έ̣γερο̣ν<a href="#to-app-choice25" id="from-app-choice25">(*)</a> τὴν δυ<a href="#to-app-choice26" id="from-app-choice26">(*)</a><br id="aB-l12">σου κ̣(αὶ) ἐλ̣θὲ ε̣ἰ̣ς̣ τ̣ὸ̣ σ̣ῶ̣σ̣α̣ι̣ ἡ̣μ̣-<br id="aB-l13">ᾶ̣ς ὁ θ(εὸ)ς ἐπίστρεψ̣ο̣ν̣ &lt;ἡμᾶς&gt;<br id="aB-l14"><span title="number: 44">μ̣δ</span><br id="aB-l15"><span class="linenumber">15</span>ὅτι̣ ἐπεθύμ̣η̣σ̣ε̣(ν)<br id="aB-l16">ὁ β̣ασιλεις<a href="#to-app-choice27" id="from-app-choice27">(*)</a> τὸ κ̣ά̣λ̣-<br id="aB-l17">λ̣ο̣ς̣ σ̣ο̣υ̣ ὅ̣τ̣ι̣ αὐ̣τό̣ς ἐστιν̣<br id="aB-l18">ὁ̣ κ̣(ύριό)ς̣ σ̣ο̣υ̣. 
                            </div>  <span class="textpartnumber" id="abC">C</span><br>  
                            <div class="textpart"><a id="aC-l1">
-                                 <!--0--></a> ἦ\χ/(ος) <span title="number: 2">β</span><br id="aC-l2"><span class="lb inverse"></span> ἐπεσκ(αί)ψατο<a href="#to-app-choice28" id="from-app-choice28">(*)</a><br id="aC-l3"><span class="lb inverse"></span> ἡμᾶς ((mese-stigme)) ἀνατο̣-<br id="aC-l4"><span class="lb inverse"></span>λὴ ἐξ ὕψους ((mese-stigme)) <br id="aC-l5"><span class="lb inverse"></span><span class="linenumber">5</span> τοῦ προδρόμ\ο/(υ)<br id="aC-l6"><span class="lb inverse"></span> γὰρ γ̣εννήσει<br id="aC-l7"><span class="lb inverse"></span> βασιλαία<a href="#to-app-choice29" id="from-app-choice29">(*)</a> κ̣&nbsp;&nbsp;̣<br id="aC-l8"><span class="lb inverse"></span> εν&nbsp;&nbsp;̣&nbsp;&nbsp;̣&nbsp;&nbsp;̣&nbsp;&nbsp;̣&nbsp;&nbsp;̣<br id="aC-l8"><span class="lb inverse"></span> [ca.5 lines missing]<br id="aC-l14"><span class="lb inverse"></span><span class="linenumber">14</span> λλ<br id="aC-l15"><span class="lb inverse"></span><span class="linenumber">15</span> οτησδ<br id="aC-l16"><span class="lb inverse"></span> &nbsp;&nbsp;̣&nbsp;&nbsp;̣&nbsp;&nbsp;̣ Χ(ριστό)ς 
+                                 <!--0--></a> ἦ\χ/(ος) <span title="number: 2">β</span><br id="aC-l2"><span class="lb inverse">(inverse) </span> ἐπεσκ(αί)ψατο<a href="#to-app-choice28" id="from-app-choice28">(*)</a><br id="aC-l3"><span class="lb inverse">(inverse) </span> ἡμᾶς ((mese-stigme)) ἀνατο̣-<br id="aC-l4"><span class="lb inverse">(inverse) </span>λὴ ἐξ ὕψους ((mese-stigme)) <br id="aC-l5"><span class="lb inverse">(inverse) </span><span class="linenumber">5</span> τοῦ προδρόμ\ο/(υ)<br id="aC-l6"><span class="lb inverse">(inverse) </span> γὰρ γ̣εννήσει<br id="aC-l7"><span class="lb inverse">(inverse) </span> βασιλαία<a href="#to-app-choice29" id="from-app-choice29">(*)</a> κ̣&nbsp;&nbsp;̣<br id="aC-l8"><span class="lb inverse">(inverse) </span> εν&nbsp;&nbsp;̣&nbsp;&nbsp;̣&nbsp;&nbsp;̣&nbsp;&nbsp;̣&nbsp;&nbsp;̣<br id="aC-l8"><span class="lb inverse">(inverse) </span> [ca.5 lines missing]<br id="aC-l14"><span class="lb inverse">(inverse) </span><span class="linenumber">14</span> λλ<br id="aC-l15"><span class="lb inverse">(inverse) </span><span class="linenumber">15</span> οτησδ<br id="aC-l16"><span class="lb inverse">(inverse) </span> &nbsp;&nbsp;̣&nbsp;&nbsp;̣&nbsp;&nbsp;̣ Χ(ριστό)ς 
```
    
Ready for review. @paregorios

**Comment by paregorios** [comment]
The new code makes the desired change by adding the string (inverse) to the text node inside ```<span class="lb inverse">```. Unfortunately, [there is a rule in master.css](https://github.com/DCLP/navigator/blob/master/pn-site/css/master.css#L383) that sets the display value for this element to "none", so the user doesn't see the effect of this change:

```.lb {display:none;}```

@wsalesky: maybe recommend ([on the model of "indent" and "outdent"](https://github.com/DCLP/navigator/blame/master/pn-site/css/master.css#L381-L382)) the addition of a more specific css rule for ```.lb.inverse``` to supersede the more general rule that is currently hiding the ```<span>```.

**Comment by wsalesky** [comment]
Okay I added additional styles to the css. 
See branches:
https://github.com/DCLP/dclpxsltbox/tree/issue152 
https://github.com/DCLP/navigator/tree/issue152

**Comment by paregorios** [comment]
This is for me to review.

**Comment by paregorios** [comment]
The CSS problem is fixed, but we seem to have one more edge case that needs addressing. When the first line in a ```<div type="textpart">``` begins with ```<lb ... rend="inverse"/>```, the expected HTML is not generated. Our example from above (TM128952) exhibits this problem when transformed with the code in the "issue152" branch on epidoc-xslt and displayed with the code in the "issue152" branches on "navigator" and "dclpxsltbox".

XML:
```xml
<div n="C" type="textpart">
    <ab>
        <lb n="1" rend="inverse"/> <expan>ἦ<add place="above">χ</add><ex>ος</ex></expan> <num value="2">β</num>
        <lb n="2" rend="inverse"/> <choice><reg>ἐπεσκέψατο</reg><orig><expan>ἐπεσκ<ex>αί</ex>ψατο</expan></orig></choice>
        <lb n="3" rend="inverse"/> ἡμᾶς<g type="mese-stigme"/> ἀνατ<unclear>ο</unclear>
        <lb n="4" rend="inverse" break="no"/>λὴ ἐξ ὕψους<g type="mese-stigme"/>
        <lb n="5" rend="inverse"/> τοῦ <expan>προδρόμ<add place="above">ο</add><ex>υ</ex></expan>
        <lb n="6" rend="inverse"/> γὰρ <unclear>γ</unclear>εννήσει
        <lb n="7" rend="inverse"/> <choice><reg>βασιλέα</reg><orig>βασιλαία</orig></choice> <unclear>κ</unclear><gap reason="illegible" quantity="1" unit="character"/>
        <lb n="8" rend="inverse"/> εν<gap reason="illegible" quantity="5" unit="character"/>
        <lb n="8" rend="inverse"/> <gap reason="lost" quantity="5" unit="line" precision="low"/>
        <lb n="14" rend="inverse"/> λλ
        <lb n="15" rend="inverse"/> οτησδ
        <lb n="16" rend="inverse"/> <gap reason="illegible" quantity="3" unit="character"/> <expan>Χ<ex>ριστό</ex>ς</expan>
    </ab>
</div>
```

HTML output:
```
C

    ἦ\χ/(ος) β
    (inverse) ἐπεσκ(αί)ψατο(*)
    (inverse) ἡμᾶς ((mese-stigme)) ἀνατο̣-
    (inverse) λὴ ἐξ ὕψους ((mese-stigme)) 
⋮
```

What we want to see is:

```
C

    (inverse) ἦ\χ/(ος) β
    (inverse) ἐπεσκ(αί)ψατο(*)
    (inverse) ἡμᾶς ((mese-stigme)) ἀνατο̣-
    (inverse) λὴ ἐξ ὕψους ((mese-stigme)) 
⋮
```

**Comment by paregorios** [comment]
@wsalesky NB that I have pushed changes (master merges) to all of the associated branches.

**Comment by wsalesky** [comment]
The XSLT was set up to handle first `tei:lb` differently. I have added the xsl:choose for rend='inverse' and rend='perpendicular' to this section of the `tei:lb` template. 

XSLT changed: `epidoc-xslt/htm-teilb.xsl`
Branch: https://github.com/DCLP/epidoc-xslt/compare/issue152
HTML output: 
```
C
(inverse) ἦ\χ/(ος) β
(inverse) ἐπεσκ(αί)ψατο(*)
(inverse) ἡμᾶς ((mese-stigme)) ἀνατο̣-
(inverse) λὴ ἐξ ὕψους ((mese-stigme)) 
(inverse) 5 τοῦ προδρόμ\ο/(υ)
(inverse) γὰρ γ̣εννήσει
(inverse) βασιλαία(*) κ̣  ̣
(inverse) εν  ̣  ̣  ̣  ̣  ̣
(inverse) [ca.5 lines missing]
(inverse) 14 λλ
(inverse) 15 οτησδ
(inverse)   ̣  ̣  ̣ Χ(ριστό)ς
```

@paregorios back to you for review.

**Comment by paregorios** [comment]
@jcowey @rla2118 display of "inverse" is now fixed. To see it on production, it will be necessary for @m-k-r to pull the latest master code from the epidoc-xslt *and* navigator repositories, and to re-run mapping/indexing/generation.
