### ISSUE TITLE
Keywords copied into XML file check

### ISSUE THREAD

**Issue by jcowey** [DCLP/dclpxsltbox#154]
https://github.com/DCLP/idp.data/blob/dclp/DCLP/120/119324.xml#L66-L72

check that this works

**Comment by margheritacent** [comment]
Dear James,
it works!
Thank you indeed,
Margherita

2015-09-10 12:47 GMT+02:00 James M.S. Cowey <notifications@github.com>:

**Comment by jcowey** [comment]
http://dclp.github.io/dclpxsltbox/output/dclp/120/119324.html

They are displayed. Still not sure whether we want to differentiate between
https://github.com/DCLP/idp.data/blob/dclp/DCLP/120/119324.xml#L66-L72
(these come from HGV style entry through the editor - then copied into the XML files)
and
https://github.com/DCLP/idp.data/blob/dclp/DCLP/120/119324.xml#L73-L75
(these come from LDAB)
In display the are all joined together

**Comment by rla2118** [comment]
I see no reason to differentiate between the two.  They can be displayed together.

**Comment by jcowey** [comment]
Changed by:
https://github.com/DCLP/idp.data/commit/fa3437467c158f74f6a8a0dc6a27d6cc04d73856

**Comment by jcowey** [comment]
See now at:
https://github.com/DCLP/idp.data/blob/dclp/DCLP/120/119324.xml#L66-L73

so closing this issue
