### ISSUE TITLE
Does the editor really allow us to specify which page in an article was the page on which the text was presented?

### ISSUE THREAD

**Issue by rla2118** [DCLP/dclpxsltbox#160]
If you look at http://dclp.github.io/dclpxsltbox/output/dclp/131/130167.html you will see that the page on which the edition appears is not included (it's also not in the XML).  With a lengthy article containing many editions this makes it difficult to find the text in question.  Where should this information go and is it already somewhere in the LDAB data?

**Comment by jcowey** [comment]
Pretty sure that this will be something that the editor will be able to handle. I reckon that this is the type of information that we did not try to parse from the LDAB information. We said that it would have to wait until the editor could manage it.

**Comment by Edelweiss** [comment]
I have the feeling that all of these tickets are somehow related

- add Book and Line to Editor #253 
- SoSOL Meta Editor: Edition & Bibliography: generic passages #227
- Does the editor really allow us to specify which page in an article was the page on which the text was presented? #160

all to do with what values we allow for TEI:biblScope/@unit (in modern bibliography and ancient works)
