### ISSUE TITLE
Incomplete MSI image content in PHerc

### ISSUE THREAD

**Issue by rla2118** [DCLP/dclpxsltbox#162]
https://dclp.github.io/dclpxsltbox/output/dclp/60/59754.html

If you look at this record you'll see that there are 4 image links.  They lead to two distinct photos.  Photos of the other fragments are missing.  Is this because we never got these image links from Chartes, or is there a problem with the linking?

**Comment by HolgerEssler** [comment]
The reason is that for each inventory number there is only one image on 
chartes. Thus we got links to all the images there, but these images 
cover just a small percentage of the fragments.

**Comment by HolgerEssler** [comment]
Since there is no additional image data available, I suggest closing this issue, but leave the decision to @rla2118.

**Comment by paregorios** [comment]
@rla2118 please indicate whether you concur with, or demur from, @HolgerEssler above. cc @rogerbagnall @jcowey

**Comment by paregorios** [comment]
@rla2118 please see above. Do you concur with closing this issue?

**Comment by rla2118** [comment]
Yes, I concur.
