### ISSUE TITLE
Credit BYU for MSI

### ISSUE THREAD

**Issue by HolgerEssler** [DCLP/dclpxsltbox#164]
In order to credit the team from BYU for the MSI of Herculaneum papyri,
their name should be added to all `<custEvent type="MSI">`, by
inserting `<surname>CPART, Brigham Young University</surname>`.
Example after:
https://github.com/DCLP/idp.data/blob/dclp/DCLP/60/59752.xml#L150
`<surname>CPART, Brigham Young University</surname>` should be added, in analogy to the indication of the responsible in
https://github.com/DCLP/idp.data/blob/dclp/DCLP/60/59752.xml#L159

**Comment by paregorios** [comment]
I'm looking at impact if we use ```<name>``` instead of ```<surname>```.

**Comment by paregorios** [comment]
@jcowey we should discuss

**Comment by paregorios** [comment]
The [proper XML encoding](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-orgName.html) for this would be:

```xml
<orgName>CPART, Brigham Young University</orgName>
```

rather than using ```<surname>```. 

Once we have some files with such markup in them, we'll need to test XSLT behavior.

@HolgerEssler is the scripted change to the XML files something your team can take on, or should it be a Heidelberg responsibility?

**Comment by paregorios** [comment]
per @rla2118 I will email @HolgerEssler about this

**Comment by paregorios** [comment]
per discussion @HolgerEssler to undertake when possible

**Comment by HolgerEssler** [comment]
The additional data should be added with
https://github.com/DCLP/idp.data/commit/d523da3a1fb7e0bad08bd1a1eafa0b971c4cfcf3
However, it does not seem to have been merged since.

**Comment by paregorios** [comment]
@HolgerEssler what do you mean "it does not seem to have been merged since?"

I see the relevant lines in the XML files in the master branch, e.g. https://github.com/DCLP/idp.data/blob/master/DCLP/110/109360.xml#L83

**Comment by HolgerEssler** [comment]
I did not see them before, but if the relevant lines are in the master branch now, I suggest closing this issue.
