### ISSUE TITLE
missing whitespace between "pp." or "pl." and the number(s) in some bibliographic citations

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#167]
This ticket was split out from #146.

Examples showing the problem (TM108441):

> MPER 22, pl. 3, 5-6; Orientalia 67 (1998), `pl.6`; H. Froschauer - C. Römer, Spätantike Bibliotheken, Bilus 14, Vienna 2008, Kat. 5 (`pp.97-98`)

Example where there is no problem (TM59494):

> Enzo Puglia, "Nuove letture nei PHerc. 1012 e 1786 (Demetrii Laconis opera incerta)," Cronache Ercolanesi, 10 (1980), `pp. 25-53`.

A search like this in `dclpxsltbox/output/dclp` turns up relevant examples:

```
find . -name "*.html" -exec grep -u "p[^\s\.]\.\d" {} \;
```

The main question, it seems to me, is to determine whether this is creeping in in processing structured XML bibliography (i.e., an XSLT whitespace management issue) or if these are just strings containing unstructured bibliographic citations in the XML. In the latter case, this is likely a "won't fix" ticket.

**Comment by leoba** [comment]
I looked up several (by no means all) examples that come up from the search in Tom's previous comment, and all I looked at are in t:bibl[@type='illustration'], which is not structured ([for example](https://github.com/DCLP/idp.data/blob/dclp/DCLP/109/108104.xml#L78)). I can keep looking for it appears to be a "won't fix" ticket.

**Comment by leoba** [comment]
We might consider adding "Tweak XML Encoding" here if we want to to through and change the unstructured instances of "pp.xx" or "pl.xx" to include spaces, or to otherwise add structure to those entries.

**Comment by jcowey** [comment]
Needs XML fixing which is not a small undertaking. Not in the scope of the project at present
