### ISSUE TITLE
whitespace inside parentheses around years in bibliographic citations

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#168]
split out from #146 

examples can be found with:

```
find . -name "*.html" -exec grep -ulE "\(\s+\d\d\d\d" {} \;
```

e.g. TM109360:

> ( 1979)

**Comment by paregorios** [comment]
see also the apparently co-occurring #169

**Comment by leoba** [comment]
I have updated htm-teibibl.xsl to fix both this issue and issue #169. 

There was a [slash missing in this line](https://github.com/DCLP/navigator/blob/master/pn-xslt/htm-teibibl.xsl#L106), and a space needed to be added between xsl:if statements on the same line.

This seems to fix both.

**Comment by paregorios** [comment]
@leoba can you point me to the code commit for this fix? Thank you.

**Comment by leoba** [comment]
Unable to commit, have emailed @paregorios to check on permissions (not sure why it wasn't committed back in April but will get the code in asap)

**Comment by leoba** [comment]
I have just committed the code (in navigator/pn-xslt/htm-teibibl.xsl) on the master branch.

**Comment by paregorios** [comment]
I'll take a look at this.

**Comment by paregorios** [comment]
commit is here: https://github.com/DCLP/navigator/commit/c905a78f4c36dce3bcce80c419f4707167cbfea9

**Comment by leoba** [comment]
This should have fixed issue 168 too, so you can check and then close that issue too.

**Comment by paregorios** [comment]
done, thanks!
