### ISSUE TITLE
no whitespace in bibliographic citations between parentheses and page numbers

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#169]
seems to occur in many of the same citations that are affected by #168:

e.g., TM109360:

> ( 1979)191-197

found with:

```
find . -name "*.html" -exec grep -uEH "\d\d\d\d\)\d" {} \;
```

**Comment by leoba** [comment]
It appears that this is a problem specifically with Biblio files containing `bibl@subtype='book'`, so that's a start.

**Comment by leoba** [comment]
See comment at https://github.com/DCLP/dclpxsltbox/issues/168#issuecomment-205009509

**Comment by leoba** [comment]
This should have been closed after issue 169 was closed, so I am closing it now.
