### ISSUE TITLE
inconsistencies in biblScope markup not handled by XSLT

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#170]
found by @leoba and split out from #146:

In Bibl files, if page numbers for journal articles are only in @from and @to values on biblScope and not in the content of biblScope, they do not display. Compare:

https://github.com/DCLP/idp.data/blob/master/Biblio/81/80929.xml#L7 (HTML: https://github.com/DCLP/dclpxsltbox/blob/master/output/dclp/65/64713.html#L46)
http://litpap.info/dclp/64713

with

https://github.com/DCLP/idp.data/blob/master/Biblio/66/65876.xml#L13
(HTML: https://github.com/DCLP/dclpxsltbox/blob/master/output/dclp/101/100149.html#L46)
http://litpap.info/dclp/100149

Is this an XSLT issue or an XML issue?

**Comment by paregorios** [comment]
So this is perhaps a question for @jcowey: should we undertake to fix/standardize all the XML, or should we paper it over by making the XSLT fault tolerant? Or both?

**Comment by jcowey** [comment]
I think it would be better to change the XML. It would neither hard nor particularly time consuming to do. I think that the XML would then also be "better" XML, don't you think?

**Comment by paregorios** [comment]
@jcowey I would agree with you 100%. That said, I did put some fallback into the XSLT behaviors that got built a couple of weeks ago.

**Comment by jcowey** [comment]
The XML will be changed by Carmen.

**Comment by Edelweiss** [comment]
Pushed results to papyri’s [biblio](https://github.com/papyri/idp.data/commit/ac7d0672131c7971d4619edcc8f901dea49e279d) branch

**Comment by jcowey** [comment]
Super, thanks @Edelweiss. I reckon that this can now be closed @paregorios. If you do too the please close. I suppose you may have to do some tweaking to the XSLT.

**Comment by paregorios** [comment]
I will merge down from papyri to DCLP and then test prior to closing.

**Comment by paregorios** [comment]
verified good and latest transforms are up with https://github.com/DCLP/dclpxsltbox/commit/7063b0338dd319459901d88276384227fbe37646
