### ISSUE TITLE
Add urn:cts numbers to ancient authors where they are missing

### ISSUE THREAD

**Issue by jcowey** [DCLP/dclpxsltbox#176]
On the basis of the spreadsheet DCLP Biblio
https://docs.google.com/spreadsheets/d/1zS8D859XVja4XaI-2G-5BDe3t63cJ_N4ldjUHDCkoTc/edit#gid=0

add the relevant urn:cts numbers to the relevant place in the DCLP files.

**Comment by Edelweiss** [comment]
- Antiphanes	0410
- Aristodemus	2148
- Eusebius	2018
- Hecataeus of Miletus	0538
- Hieronymus of Rhodus	1430
- Manetho	2583
- Menander	0541
- Palladius of Galatia	2111
- Philemon	0487
- Philiscus	0491
- Satyrus of Callatis	0608

**Comment by Edelweiss** [comment]
There’s a phi number for Gaius, who at the same time is flagged as »nicht eindeutig identifizierbar«

- Gaius, nicht eindeutig identifizierbar, http://data.perseus.org/catalog/urn:cts:latinLit:phi1251

Should this url be added, nontheless?

**Comment by Edelweiss** [comment]
```xml
<author>Antiphanes</author>
<author>Aristodemus</author>
<author>Eusebius</author>
<author ref="http://data.perseus.org/catalog/urn:cts:greekLit:tlg0538">Hecataeus of Miletus</author>
<!-- Hieronymus of Rhodus -->
<author>Manetho</author>
<author>Menander</author>
<!-- Palladius of Galatia -->
<author>Philemon</author>
<author>Philiscus</author>
<!-- Satyrus of Callatis -->
```

**Comment by Edelweiss** [comment]
https://github.com/DCLP/idp.data/commit/09353a45274e581f7bfd74ad076eb60b1033a19a

**Comment by Edelweiss** [comment]
@HolgerEssler, please review that this is correct

**Comment by HolgerEssler** [comment]
@Edelweiss I am not sure what I shoud review - the spreadsheet or the single DCLP files.

**Comment by jcowey** [comment]
@HolgerEssler - this is going to have to wait. I shall get back to you after the merge of DCLP and papyri.info has taken place. 
The task is probably not too big but I need to have a look at the state of play first. That is not going to happen in the next ten days.

**Comment by Edelweiss** [comment]
@HolgerEssler  please click on the following link to review the additions:

https://github.com/DCLP/idp.data/commit/09353a45274e581f7bfd74ad076eb60b1033a19a

they should now be fine.
