### ISSUE TITLE
Invalid DCLP EpiDoc files: element "q" not allowed here (3 cases / text part)

### ISSUE THREAD

**Issue by Edelweiss** [DCLP/dclpxsltbox#178]
- [62460](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62460.xml#L1714) (expected the element end-tag, text or element "abbr", "add", "addSpan", "am", "anchor", "app", "c", "cb", "certainty", "choice", "corr", "damage", "del", "delSpan", "ex", "expan", "figure", "fw", "g", "gap", "gb", "handShift", "hi", "index", "interp", "interpGrp", "join", "lb", "link", "linkGrp", "listTranspose", "m", "metamark", "milestone", "mod", "notatedMusic", "note", "orig", "pb", "pc", "precision", "redo", "reg", "retrace", "secl", "seg", "sic", "space", "subst", "substJoin", "supplied", "surplus", "unclear", "undo" or "w")
- [62448](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62448.xml) (expected the element end-tag, text or element "abbr", "add", "addSpan", "am", "anchor", "app", "c", "cb", "certainty", "choice", "corr", "damage", "del", "delSpan", "ex", "expan", "figure", "fw", "g", "gap", "gb", "handShift", "hi", "index", "interp", "interpGrp", "join", "lb", "link", "linkGrp", "listTranspose", "m", "metamark", "milestone", "mod", "notatedMusic", "note", "orig", "pb", "pc", "precision", "redo", "reg", "retrace", "secl", "seg", "sic", "space", "subst", "substJoin", "supplied", "surplus", "unclear", "undo" or "w")
- [62391](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62391.xml) (expected the element end-tag, text or element "abbr", "add", "addSpan", "am", "anchor", "app", "c", "cb", "certainty", "choice", "corr", "damage", "del", "delSpan", "ex", "expan", "figure", "fw", "g", "gap", "gb", "handShift", "hi", "index", "interp", "interpGrp", "join", "lb", "link", "linkGrp", "listTranspose", "m", "metamark", "milestone", "mod", "notatedMusic", "note", "orig", "pb", "pc", "precision", "redo", "reg", "retrace", "secl", "seg", "sic", "space", "subst", "substJoin", "supplied", "surplus", "unclear", "undo" or "w")

**Comment by Edelweiss** [comment]
see ticket #181

**Comment by HolgerEssler** [comment]
XML corrected. Suggest closing.
