### ISSUE TITLE
Invalid DCLP EpiDoc files: value of attribute "cert" is invalid (2 cases / text part)

### ISSUE THREAD

**Issue by Edelweiss** [DCLP/dclpxsltbox#179]
- [59754](https://github.com/DCLP/idp.data/blob/dclp/DCLP/60/59754.xml#L845) (must be a floating-point number or must be equal to "high", "low", "medium" or "unknown")
- [62450](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62450.xml#L343) (must be a floating-point number or must be equal to "high", "low", "medium" or "unknown")

**Comment by HolgerEssler** [comment]
XML-Corrected in pull-request #6

**Comment by HolgerEssler** [comment]
I suggest closing this issue, but perhaps @Edelweiss wants to check validity first.

**Comment by paregorios** [comment]
They are valid.
