### ISSUE TITLE
Invalid DCLP EpiDoc files: element "orig" not allowed here (2 cases / text part)

### ISSUE THREAD

**Issue by Edelweiss** [DCLP/dclpxsltbox#180]
- [59754](https://github.com/DCLP/idp.data/blob/dclp/DCLP/60/59754.xml#L845) (expected the element end-tag or element "lem", "note", "rdg", "rdgGrp" or "wit")
- [62450](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62450.xml#L343) (expected the element end-tag or element "lem", "note", "rdg", "rdgGrp" or "wit")

**Comment by HolgerEssler** [comment]
I suspect that this has been resolved through recent xml-updates. Could you check @Edelweiss?

**Comment by paregorios** [comment]
The example files now validate against EpiDoc schema 8.23.
