### ISSUE TITLE
Invalid DCLP EpiDoc files: element "num" not allowed here (2 cases / text part)

### ISSUE THREAD

**Issue by Edelweiss** [DCLP/dclpxsltbox#181]
- [62460](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62460.xml) (expected the element end-tag, text or element "abbr", "add", "addSpan", "am", "anchor", "app", "c", "cb", "certainty", "choice", "corr", "damage", "del", "delSpan", "ex", "expan", "figure", "fw", "g", "gap", "gb", "handShift", "hi", "index", "interp", "interpGrp", "join", "lb", "link", "linkGrp", "listTranspose", "m", "metamark", "milestone", "mod", "notatedMusic", "note", "orig", "pb", "pc", "precision", "redo", "reg", "retrace", "secl", "seg", "sic", "space", "subst", "substJoin", "supplied", "surplus", "unclear", "undo" or "w")
- [62391](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62391.xml) (expected the element end-tag, text or element "abbr", "add", "addSpan", "am", "anchor", "app", "c", "cb", "certainty", "choice", "corr", "damage", "del", "delSpan", "ex", "expan", "figure", "fw", "g", "gap", "gb", "handShift", "hi", "index", "interp", "interpGrp", "join", "lb", "link", "linkGrp", "listTranspose", "m", "metamark", "milestone", "mod", "notatedMusic", "note", "orig", "pb", "pc", "precision", "redo", "reg", "retrace", "secl", "seg", "sic", "space", "subst", "substJoin", "supplied", "surplus", "unclear", "undo" or "w")

**Comment by Edelweiss** [comment]
Vorgeschlagene Lösung von Holger Essler zur Lösung von Tickets #178, #179 und #181:

> Ein besonderes Problem stellen aber die von Daniel Riano eingeführten
> <w>-Tags dar, die sich teilweise mit anderen Elementen überlappen und
> so ein gültiges XML unmöglich machen. Aus Gründen der Einheitlichkeit
> und Übersichtlichkeit würden wir daher gerne alle <w>-Tags
> einschließlich ihrer Attribute aus den Textdateien herausnehmen bzw.
> löschen und nur die jeweiligen Inhalte der Elemente (also die
> eigentlichen griechischen Wörter) behalten. Betroffen sein sollten nur
> die herkulanischen Texte.

**Comment by HolgerEssler** [comment]
XML corrected. Suggest closing.
