### ISSUE TITLE
Invalid DCLP EpiDoc files: value of attribute of type ID contained multiple tokens (17 cases / custEvent)

### ISSUE THREAD

**Issue by Edelweiss** [DCLP/dclpxsltbox#183]
- [59749](https://github.com/DCLP/idp.data/blob/dclp/DCLP/60/59749.xml#L631) (example with line number)
- [59506](https://github.com/DCLP/idp.data/blob/dclp/DCLP/60/59506.xml)
- [59436](https://github.com/DCLP/idp.data/blob/dclp/DCLP/60/59436.xml)
- [62500](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62500.xml)
- [62499](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62499.xml)
- [62477](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62477.xml)
- [62445](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62445.xml)
- [62437](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62437.xml)
- [62433](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62433.xml)
- [62428](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62428.xml)
- [62419](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62419.xml)
- [62411](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62411.xml)
 *　https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62411.xml#L1210
- [62405](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62405.xml)
- [62400](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62400.xml)
- [62394](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62394.xml)
- [62393](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62393.xml)
- [62388](https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62388.xml)

**Comment by Edelweiss** [comment]
Please look at these two examples. If
```xml
<custEvent type="engraved"
                                   corresp="#FR3286 #FR4599"
                                   xml:id="GR3286 #FR4599.02">
                           <forename>Domenico</forename>
                           <surname>Casanova</surname>
                           <graphic url="http://www.epikur-wuerzburg.de/vh2/VH2_07_160.jpg"/>
</custEvent>
```
could become

```xml
<custEvent type="engraved"
                                   corresp="#FR3286"
                                   xml:id="GR3286">
                           <forename>Domenico</forename>
                           <surname>Casanova</surname>
                           <graphic url="http://www.epikur-wuerzburg.de/vh2/VH2_07_160.jpg"/>
</custEvent>

<custEvent type="engraved"
                                   corresp="#FR4599"
                                   xml:id="#FR4599.02">
                           <forename>Domenico</forename>
                           <surname>Casanova</surname>
                           <graphic url="http://www.epikur-wuerzburg.de/vh2/VH2_07_160.jpg"/>
</custEvent>

```
or perhaps this would be preferable 

```xml
<custEvent type="engraved"
                                   corresp="#FR3286 #FR4599"
                                   xml:id="GR3286_FR4599.02">
                           <forename>Domenico</forename>
                           <surname>Casanova</surname>
                           <graphic url="http://www.epikur-wuerzburg.de/vh2/VH2_07_160.jpg"/>
</custEvent>
```


without busting any of your possible XSLTs 
or if it still makes sense

then that would make these files validate

Can you please let us know.

**Comment by HolgerEssler** [comment]
I would opt for the second solution, i.e. having only one, combined xml:id:

```xml
<custEvent type="engraved"
                                    corresp="#FR3286 #FR4599"
                                    xml:id="GR3286_FR4599.02">
                            <forename>Domenico</forename>
                            <surname>Casanova</surname>
                            <graphic
url="http://www.epikur-wuerzburg.de/vh2/VH2_07_160.jpg"/>
</custEvent>
```

------------------------------------
Dr. Holger Essler, AR
Institut für Klassische Philologie I
Residenzplatz 2 (Südflügel)
D-97070 Würzburg

Tel.:            +49-931-31-85632
email:           Holger.Essler@uni-wuerzburg.de
Institutsseite:  www.klassphil.uni-wuerzburg.de
Epikurzentrum:   www.epikur-wuerzburg.de

**Comment by paregorios** [comment]
I will undertake to have a look at the XSLT files to see if there are any consequences.

**Comment by paregorios** [comment]
Having looked at the XSLT, I do not see any reason why [the change proposed above by @HolgerEssler](https://github.com/DCLP/dclpxsltbox/issues/183#issuecomment-264441250) would break things. I suggest that @Edelweiss proceed with implementation in the XML, then we can test.

**Comment by Edelweiss** [comment]
ok → [github](https://github.com/DCLP/idp.data/commit/623676c4f2ce2495047a2a4e1d15f6c974e117d8)

**Comment by paregorios** [comment]
@paregorios to review and post new transforms

**Comment by paregorios** [comment]
Confirm these validate, are in DCLP/idp.data master branch, and current review transforms have been generated and posted from same.
