### ISSUE TITLE
corresp choking x-sugar

### ISSUE THREAD

**Issue by rla2118** [DCLP/dclpxsltbox#184]
The presence of corresp numbers seems to choke up x-sugar.  Here is an example:

http://litpap.info/editor/publications/1/dclp_text_identifiers/2/edit

**Comment by jcowey** [comment]
This is very similar to #177.

**Comment by paregorios** [comment]
@jcowey and/or @rla2118 can we set up a time for me to watch you dealing with this in the editor using screen sharing?

**Comment by paregorios** [comment]
Per discussion with @jcowey and @rla2118 this is a duplicate for #177, so closing this one.
