### ISSUE TITLE
image links missing from custodial events

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#186]
Per @HolgerEssler: when a custodial event is of type "imaged" and contains a `<graphic>` element, the output HTML must include a link to that image. Presently (recently) they don't. Consider, for example, [62931](http://dclp.github.io/dclpxsltbox/output/dclp/63/62931.html).

**Comment by paregorios** [comment]
@HolgerEssler see latest comments on #187 

cc @rla2118 @jcowey

**Comment by HolgerEssler** [comment]
To me the problem seems to be solved thanks to #187. Suggest closing.
