### ISSUE TITLE
repetitive, indistinguishable custodial events

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#187]
Consider [62931](http://dclp.github.io/dclpxsltbox/output/dclp/63/62931.html), concerning which @HolgerEssler has written:

> I have the impression that this repetition is caused by column 1 being without text (and without any corresp). For some reason in this case the XSLT seems to attach every custEvent to it, but it should attach none.

**Comment by paregorios** [comment]
@HolgerEssler please have a look at the latest posted files ([62931](http://dclp.github.io/dclpxsltbox/output/dclp/63/62931.html) and some others of your choice!) and see what you think. 

cc @rla2118 @jcowey

**Comment by HolgerEssler** [comment]
TM 62931 (and other examples) looks great. I have come across only 
one problem:
In TM 62400:
http://dclp.github.io/dclpxsltbox/output/dclp/63/62400.html
   the other entries of custEvent ("Sketched", "Engraved") seem to be 
distributed correctly, but there are no underlying links for these.
   Could these be added?

**Comment by paregorios** [comment]
@HolgerEssler I'll see if I can change the logic that it uses to decide whether or not to make a link

**Comment by paregorios** [comment]
@HolgerEssler how is it now?

**Comment by paregorios** [comment]
note now also e.g. http://dclp.github.io/dclpxsltbox/output/dclp/60/59744.html (at "fragment 46" etc).

**Comment by HolgerEssler** [comment]
I looked at several examples and all seem to be correct now. Suggest closing the issue.

**Comment by paregorios** [comment]
Thanks @HolgerEssler

**Comment by rla2118** [comment]
It looks like the links are being distributed correctly.  I see, though, that the image links next to individual fragments at http://dclp.github.io/dclpxsltbox/output/dclp/63/62931.html are broken.  Is this a problem on our end or on Berlin's?

**Comment by jcowey** [comment]
Closing with reference to #189.
