### ISSUE TITLE
SoSOL Metadata Editor: save open tabs

### ISSUE THREAD

**Issue by Edelweiss** [DCLP/dclpxsltbox#193]
When using the editor to save metadata, the entry mask should remember all tabs that are currently open and reopen them after saving

Available tabs are:
* Editions & Bibliography
* Author & Work
* Physical Description (Collection, Dimension, Layout, Material)
* General Notes
* Date
* Mentioned Dates
* Provenance

**Comment by Edelweiss** [comment]
this [commit](https://github.com/DCLP/sosol/commit/4d896d32be88ed7451387aecd1f6b92fd4310850) should see to that

**Comment by jcowey** [comment]
Not yet tested as such but probably fine now
