### ISSUE TITLE
SoSOL Metadata Editor: DCLP drop down menu opens behind Janrain login panel

### ISSUE THREAD

**Issue by Edelweiss** [DCLP/dclpxsltbox#194]
change CSS style of DCLP browse menu

**Comment by Edelweiss** [comment]
[blind fix](https://github.com/DCLP/sosol/commit/84fed2bd331906de0241176da0fa30fae011e059), because janrain is not working on my machine

@m-k-r, please deploy for testing

**Comment by m-k-r** [comment]
is working
