### ISSUE TITLE
SoSOL Metadata Editor: link to DCLP doesn’t work »View in PN«

### ISSUE THREAD

**Issue by Edelweiss** [DCLP/dclpxsltbox#195]
»View in PN« button doesn’t work for DCLP files

**Comment by Edelweiss** [comment]
Changed the way dclp identifiers (meta and text) assemble their links

Meta:
[app/models/dclp_meta_identifier.rb](https://github.com/DCLP/sosol/blob/development/app/models/dclp_meta_identifier.rb#L61)

Text:
[app/models/dclp_text_identifier.rb](https://github.com/DCLP/sosol/blob/development/app/models/dclp_text_identifier.rb#L16)

Displayed in file
[app/views/identifiers/_pn_link.haml](https://github.com/DCLP/sosol/blob/development/app/views/identifiers/_pn_link.haml#L4)

**Comment by Edelweiss** [comment]
https://github.com/DCLP/sosol/commit/747a7fec0a2c046154951a01084945be7016b678

**Comment by Edelweiss** [comment]
@jcowey, @rla2118, @HolgerEssler, please test

**Comment by rla2118** [comment]
This now works. I'm closing the ticket.
