### ISSUE TITLE
XSLT display in editor preview is wonky

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#199]
e.g., crosses replacing underdots

**Comment by paregorios** [comment]
cc @m-k-r , @ryanfb , @hcayless , @rla2118 , @jcowey

**Comment by paregorios** [comment]
@m-k-r please indicate in a comment which repository, branch, and commit number of the SOSOL code is being run on the editor instance that is causing problems. In particular, I want to be able to check the exact contents of the following files and directories:

 - /config/externals.yml
 - /app/views
 - /app/models

**Comment by paregorios** [comment]
Confirmed oddities after looking at test instance. Have requested via email to @m-k-r pointers to code (as above) and access to the running instance so I can further diagnose. Here's what I think I see at this point: 

 - The metadata editor "preview" links are using a bespoke XSLT, rather than the XSLT we developed for the navigator.
 - The text editor "preview" is invoking the baseline EpiDoc stylesheets without passing the proper parameters.

**Comment by jcowey** [comment]
Dealing with a similar problem #197 is also important.

**Comment by paregorios** [comment]
This is resolved, yes? @jcowey @Edelweiss

**Comment by rla2118** [comment]
@jcowey Is this problem resolved?

**Comment by paregorios** [comment]
waiting for a reply from @jcowey to query from @rla2118 above

**Comment by paregorios** [comment]
Closing. Superseded by #283
