### ISSUE TITLE
Remove repeated info from Custodial Events

### ISSUE THREAD

**Issue by rla2118** [DCLP/dclpxsltbox#20]
In some records, info is repeated multiple times, both in custodial events and (still) under 'fragments', see https://dclp.github.io/dclpxsltbox/output/dclp/221/220478.html.  Can this be weeded out?

Rodney

**Comment by paregorios** [comment]
I'm scheduling this ticket for discussion 20 May 2015, meanwhile assigning to backlog.

**Comment by paregorios** [comment]
@HolgerEssler thinks these issues are resolved, per discussion 20 May 2015. @rla2118 points out that #51 still needs to be addressed (HTML view).
