### ISSUE TITLE
March Workshop in Wuerzburg 08-10.03.2017

### ISSUE THREAD

**Issue by jcowey** [DCLP/dclpxsltbox#200]
Entry of texts in litpap.info.
08-10 March 2017

**Comment by jcowey** [comment]
Everything marked with the Label Wuerzburg is marked as high priority for this meeting.

**Comment by paregorios** [comment]
@jcowey does this issue now serve any purpose, or can it be closed?

**Comment by jcowey** [comment]
Closing it now
