### ISSUE TITLE
make finalization work

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#201]
per @rla2118

**Comment by paregorios** [comment]
@jcowey why have you assigned this to me?

**Comment by jcowey** [comment]
simply to keep you in the loop about this, that was all, unassign yourself if you prefer

**Comment by paregorios** [comment]
@jcowey thanks; since I"m a previous correspondent on the issue thread, github will continue to alert me about updates without my being assigned.

**Comment by jcowey** [comment]
Pretty sure that we can call this closed now
