### ISSUE TITLE
empty parentheses in some bibliographic citations

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#205]
See, for example: 

TM109360:

> 83603. Adele Tepedino Guerra, "Il PHerc. 200: Metrodoro, Sulla ricchezza" in Actes du XVe Congrès International de Papyrologie. III, (Bruxelles 1979) 191-197. _Actes du XVe Congrès International de Papyrologie. III_, ().

There are others.

**Comment by jcowey** [comment]
Can you point me, please, to the XSLT that is used to transform this, preferably with the lines highlighted if it is not too much bother

**Comment by paregorios** [comment]
@jcowey when I get a chance to hunt for it, I will. First updating the biblio data we're using for transforms to make sure it really is a problem (viz #170)

**Comment by jcowey** [comment]
@paregorios OK thanks

**Comment by paregorios** [comment]
Looking at [the bibliographic XML in question here](https://github.com/DCLP/idp.data/blob/dclp/Biblio/84/83603.xml), I bet what's happening is when the XSLT processes the bibliographic entry for the article (83603) it's trying also to resolve and process the parent bibliography content (9202) via the ```<ptr target="http://papyri.info/biblio/9202"/>```, which is not necessary. So we'll need to intervene in the logic that's involved. Now to find said logic ...

**Comment by paregorios** [comment]
The template that's called to process the bibliographic item starts at https://github.com/DCLP/navigator/blob/xslt-master/pn-xslt/htm-teibibl.xsl#L45

It's called from inside this splendid template: https://github.com/DCLP/navigator/blob/xslt-master/pn-xslt/metadata-dclp.xsl#L192

which, in this case, is getting invoked here: https://github.com/DCLP/navigator/blob/xslt-master/pn-xslt/metadata-dclp.xsl#L160

**Comment by paregorios** [comment]
New transforms are up, reflecting fixed code. Examples of papyri with principal edition citations that have been fixed by this change include:

 - [TM59435](http://dclp.github.io/dclpxsltbox/output/dclp/60/59435.html)
 - [TM109360](http://dclp.github.io/dclpxsltbox/output/dclp/110/109360.html)

In all, HTML views for 903 DCLP papyri are affected by this change.

Turning over to @jcowey and @rla2118 for review. When review passes, I'll merge the code changes in to the xslt-master branch on "navigator", as they are currently still in an "issue205" branch.

**Comment by paregorios** [comment]
I have seen no objections to this from those to whom it was assigned for review, so I will be merging it to master shortly.
