### ISSUE TITLE
use "material" tag in <supportDesc><support>

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#207]
[In February 2016](https://github.com/DCLP/dclpxsltbox/issues/173), it was thought important to highlight the use of the ```<material>``` element in the support description. 

Display of the ```<material>``` tag [had been suppressed in 2014](https://github.com/DCLP/dclpxsltbox/issues/47) at direction of @rla2118 because it was judged to be redundant in the HTML transform. Said transform presents the entire textual contents of the ```<support>``` element (within which ```<material>``` appears) as a single string under the rubric "Support/Dimensions". 

If the current display of material information in HTML as described above is acceptable, then no further XSLT work is required.

If the editor currently supports the insertion of ```<material>``` into XML files, then no further coding work is required.

If no further work is required, this ticket should be closed.

If work is required, then this ticket should be properly labeled, prioritized, and if necessary, added to an appropriate milestone.

Over to @rla2118 @HolgerEssler and/or @jcowey to make said determinations.

**Comment by rla2118** [comment]
I don't fully understand this.  Support/dimensions is displaying, as here
http://litpap.info/dclp/62823 and here http://litpap.info/dclp/61910. Are
we talking about repeating information about the material or surfacing
something else?
