### ISSUE TITLE
Information about writing style (handDesc)

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#208]
[Per discussions in February 2016](https://github.com/DCLP/dclpxsltbox/issues/173), ```<handDesc>``` has been employed in the ```<physDesc>``` and may now be found in a large number of DCLP XML files. For example, consider [TM107852](https://github.com/DCLP/idp.data/blob/dclp/DCLP/108/107852.xml#L44):

```xml
<physDesc>
   <handDesc>
      <p>
         <term>Alexandrian majuscule unimodular</term>
      </p>
   </handDesc>
</physDesc>
```

The HTML transform does not yet cater for this additional information ([viz](http://dclp.github.io/dclpxsltbox/output/dclp/108/107852.html)). We should add it, immediately after the "Form and Layout" line. I suggest the rubric "Writing Style".

@rla2118 @HolgerEssler @jcowey is that OK with you? And what should be the priority on this work? Part of the WbW milestone?

**Comment by HolgerEssler** [comment]
OK with adding, suggest after WbW.

**Comment by jcowey** [comment]
Fine by me to leave adding it until after WbW

**Comment by rla2118** [comment]
I'd like to see it added but there's no pre-WbW urgency.

**Comment by leoba** [comment]
@paregorios: Requested mods have been made, see branch issue208 in navigator. There don't appear to be any instances of more than one handDesc in a file, but in case I included a feature to put ';' between multiple values.

**Comment by paregorios** [comment]
@rla2118 recently opened #257 and I did not catch the fact that it was a duplicate for this ticket until now. Although the specific implementation committed by @wsalesky at @5f67454d149f80152e73acfe81d273873b316048 is different from that introduced here, the functionality appears to be the same. Therefore I'm closing this ticket, with apologies for the duplicated work, without merging the change. If I've missed something, please let me know.
