### ISSUE TITLE
Provenance: Editing existing data or adding new data throws error 404

### ISSUE THREAD

**Issue by jcowey** [DCLP/dclpxsltbox#210]
TM 59148

Instead of "U" under "nome" I tried changing "U" to "Oxyrhynchites"

**Comment by Edelweiss** [comment]
ok, [github](https://github.com/DCLP/sosol/commit/9028205924f29a7f2d1f5d69f4560c49a36d72af)

@m-k-r, can you please make this change available for testing.

**Comment by m-k-r** [comment]
It was tested and it seems to work

**Comment by jcowey** [comment]
I tested it for existing provenance data and can confirm that it worked. So I will close this issue in the hope that it does not have to re-appear
