### ISSUE TITLE
fatal error with latest EpiDoc XSLT 

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#211]
per @m-k-r

**Comment by paregorios** [comment]
I have done a complete run of transforms. 

 - I see the "ambiguous rule match" error reported by @m-k-r and have opened a separate ticket for it: #213.
 - I do not see any fatal errors. 

@m-k-r please provide more details, like the text of the full error message, referenced files, etc. Also, please verify repositories and branches used and provide that detail as well.

**Comment by m-k-r** [comment]
At the last indexing I didn't get any fatal error. I think we can close this ticket.
