### ISSUE TITLE
We're sorry but something went wrong

### ISSUE THREAD

**Issue by rla2118** [DCLP/dclpxsltbox#214]
I opened this metadata file and tried saving it without making any changes. This generated a white page with the familiar "We're sorry but something went wrong" error 

http://147.142.225.248/editor/publications/39

**Comment by Edelweiss** [comment]
@rla2118, can you please tell me the TM number of the respective record so that I can try reproduce this error in my development environment?

**Comment by rla2118** [comment]
TM 61818.  The link I sent directs to it.

**Comment by Edelweiss** [comment]
Ah, I wasn’t aware that I can view the publications in your account. I just tried again, and once I created a new account, I was able to see them. Thanks!

**Comment by Edelweiss** [comment]
This file works fine for me. Might have been related to issue #210. I’m closing this ticket. Please re-open it if the error keeps occurring after the latest editor changes haven been deployed to our test server.

**Comment by rla2118** [comment]
When will the changes be deployed to the test server?

**Comment by m-k-r** [comment]
Probably next monday. At the weekend I will work on the indexing.
