### ISSUE TITLE
SoSOL Text Editor: undefined method `force_encoding' for nil:NilClass

### ISSUE THREAD

**Issue by Edelweiss** [DCLP/dclpxsltbox#215]
error occurs for dclp file with TM number _59922_ in _sosol/app/views/dclp_text_identifiers/edit.haml_ where on line #162

**Comment by Edelweiss** [comment]
Xsugar conversion is unable to produce Leiden+ from given xml.

Error message I get on our development server:

> Transform has timed out - system will automatically try again in 10 seconds - try# 3

**Comment by Edelweiss** [comment]
Is there something wrong with the text?

```xml
<div xml:lang="grc" type="edition" xml:space="preserve"> 
<div n="1" subtype="column" type="textpart" corresp="#FR7834"><ab>
<lb n="1"/><supplied reason="lost">νῦν μὲν</supplied> <unclear>γ</unclear>ὰρ ἡ προδοῦσα <unclear>λ</unclear><supplied reason="lost">έκτρ᾽ ἐμοῦ πατρὸς</supplied> 
<lb n="2"/><supplied reason="lost">τέθνηκε</supplied>ν· εἰ δὲ δὴ κατακτ<unclear>ε</unclear><supplied reason="lost">νεῖτ᾽ ἐμέ,</supplied> 
<lb n="3"/><supplied reason="lost">ὁ νόμος ἀ</supplied><unclear>νε</unclear>ῖται, καὶ οὐ φθάν<unclear>ο</unclear><supplied reason="lost">ι θνῄισκων τις ἄν·</supplied>
<lb n="4"/><supplied reason="lost">ὡς τῆς γε</supplied> τόλμης οὐ σπάν<unclear>ι</unclear><supplied reason="lost">ς γενήσεται.</supplied> 
<lb n="5"/><supplied reason="lost">ἀλλ᾽ οὐκ ἔ</supplied>πειθε ὅμιλον, εὖ δ<supplied reason="lost">οκῶν λέγειν.</supplied> 
<lb n="6"/><supplied reason="lost">νικᾶι δ᾽ ἐκε</supplied><unclear>ῖ</unclear>νος ὁ κακὸς ἐν <unclear>π</unclear><supplied reason="lost">λήθει λέγων,</supplied> 
<lb n="7"/><supplied reason="lost">ὃς <expan>ἠγόρευ<ex>σ</ex>ε</expan></supplied> <unclear>σ</unclear>ύγγονον σέ τ<supplied reason="lost">ε κτανεῖν.</supplied> 
<lb n="8"/><supplied reason="lost">μόλις δ᾽ ἔπε</supplied><unclear>ισ</unclear>ε μὴ πετρ<supplied reason="lost">ούμενος θανεῖν</supplied> 
<lb n="9"/><supplied reason="lost">τλήμων Ὀρέσ</supplied>της· αὐτό<unclear>χε</unclear><supplied reason="lost">ιρι δὲ σφαγῆι</supplied> 
<lb n="10"/><supplied reason="lost">ὑπέσχετ᾽ ἐ</supplied>ν τῆιδ᾽ ἡμέρ<supplied reason="lost">αι λείψειν βίον</supplied> 
<lb n="11"/><supplied reason="lost">σὺν σοί. πορεύε</supplied>ι δ᾽ αὐτ<supplied reason="lost">ὸ</supplied>ν ἐ<unclear>κ</unclear><supplied reason="lost">κλήτων ἄπο</supplied> 
<lb n="12"/><supplied reason="lost">Πυλάδης δα</supplied><unclear>κ</unclear>ρύων· σὺ<unclear>ν</unclear> <supplied reason="lost">δ᾽ ὁμαρτοῦσιν φίλοι</supplied> 
<lb n="13"/><supplied reason="lost">κλαίοντες, οἰκτ</supplied>είροντ<supplied reason="lost">ες· ἔρχεται δέ σοι</supplied> 
<lb n="14"/><supplied reason="lost">πικρὸν θέαμ</supplied><unclear>α</unclear> <unclear>κ</unclear>αὶ πρ<supplied reason="lost">όσοψις ἀθλία.</supplied>
<lb n="15"/><supplied reason="lost">ἀλλ᾽ εὐτρέπιζ</supplied><unclear>ε</unclear> φάσγα<unclear>ν</unclear>᾽ <supplied reason="lost">ἢ βρόχον δέρηι·</supplied> 
<lb n="16"/><supplied reason="lost">ὡς δεῖ λιπεῖν σε φέ</supplied><unclear>γ</unclear>γος· <unclear>ἡ</unclear> <supplied reason="lost">εὐγένεια δὲ</supplied>
</ab></div>
      </div>
```

**Comment by Edelweiss** [comment]
Can anyone make sense of this strange behaviour?

**Comment by jcowey** [comment]
Leiden+ cannot deal with corresps, as far as I know.
`<div n="1" subtype="column" type="textpart" corresp="#FR7834">`

**Comment by Edelweiss** [comment]
@jcowey, thank you very much, your hint put me on the right track. After getting rid of the [corresp](https://github.com/DCLP/idp.data/blob/master/DCLP/60/59922.xml#L101) and deleting the [surplus text div](https://github.com/DCLP/idp.data/blob/master/DCLP/60/59922.xml#L132), the file can now be opened in the editor.

**Comment by Edelweiss** [comment]
These corresp attributes appear in 175 files.

**Comment by paregorios** [comment]
blocked for #177

**Comment by paregorios** [comment]
@jcowey @rla2118 is this ticket truly a requirement for the Wb milestone? If so, then we'll need to bump priority on #177 and hope we can pull that off.

**Comment by jcowey** [comment]
You are right Tom. I am pretty sure we said that we would avoid calling up such texts. @HolgerEssler that is correct, is it not? (they are Herculaneum texts)

**Comment by HolgerEssler** [comment]
All Herculaneum papyri should have corresp-attributes, but also some dozens of other texts we entered. There should still be enough other material to avoid calling up these.

**Comment by paregorios** [comment]
Thanks @jcowey and @HolgerEssler. I'm changing the milestone for this ticket to April.

**Comment by paregorios** [comment]
I don't think we can plan for addressing this issue until #177 is resolved, therefore I am removing assignments (but leaving in the April Milestone for now).

**Comment by paregorios** [comment]
per discussion @HolgerEssler to test, report back here, and reassign ticket thereafter to me

**Comment by HolgerEssler** [comment]
The example above (i.e. TM number 59922) works fine and I tested some other files. In general the ``@correps`` seems to be catered for, but in some files there were still other problems that prevented opening them in Leiden+.

**Comment by paregorios** [comment]
thanks @HolgerEssler I'm going to close this ticket. Please open new tickets for any other problems you see, unless they are already addressed by open tickets.
