### ISSUE TITLE
Make sure that canonical URI is correct

### ISSUE THREAD

**Issue by jcowey** [DCLP/dclpxsltbox#216]
http://litpap.info/dclp/62823
offers the canonical URI as 
`Canonical URI: http://papyri.info/dclp/62823`

**Comment by Edelweiss** [comment]
The canonical URI is determined by the parameter ‘selfUrl’

parameter definition
https://github.com/DCLP/navigator/blob/development/pn-xslt/MakeHTML.xsl#L82

HTML output for canonical URI
https://github.com/DCLP/navigator/blob/development/pn-xslt/MakeHTML.xsl#L293

**Comment by Edelweiss** [comment]
https://github.com/DCLP/navigator/commit/8b84f76e10bb9868d7a2159d0617b0908881aa2e

**Comment by Edelweiss** [comment]
@jcowey, @rla2118, @HolgerEssler, please review

**Comment by rla2118** [comment]
This appears to be resolved. I'm closing the issue.
