### ISSUE TITLE
On saving make sure that new data is in the "right" XML order

### ISSUE THREAD

**Issue by jcowey** [DCLP/dclpxsltbox#217]
Example file is
http://litpap.info/editor/publications/45/dclp_meta_identifiers/90/edit
For TM 63804
Under General Notes 
MP3 I added 2364.
Saved and everything was fine. This saves an idno.
If one looks at the XML
http://litpap.info/editor/publications/45/dclp_meta_identifiers/90/editxml
one finds
```xml
        <publicationStmt>
            <authority>Digital Corpus of Literary Papyri</authority>
            <idno type="dclp">63804</idno>
            <idno type="TM">63804</idno>
            <idno type="LDAB">5017</idno>
            <idno type="filename">63804</idno>
            <idno type="dclp-hybrid">psi;3;252</idno>
            <availability>
               <p>
            © Digital Corpus of Literary Papyri. This work is licensed under a
            <ref type="license" target="http://creativecommons.org/licenses/by/3.0/">Creative Commons Attribution 3.0 License</ref>
            .
          </p>
            </availability>
            <idno type="MP3">2364</idno>
         </publicationStmt>
```

The `<idno type="MP3">2364</idno>` should be ordered in front of availability along with the other idnos

**Comment by Edelweiss** [comment]
DCLP elements in TEI:publicationStmt:

- authority
- idno
- availability

HGV elements in TEI:publicationStmt

- authority
- idno

```xquery
for $item in fn:distinct-values(collection('/data/idp.data/dclp/DCLP?select=*.xml;recurse=yes')//tei:publicationStmt/*/name())
                return string($item)
```

**Comment by Edelweiss** [comment]
https://github.com/DCLP/sosol/commit/77926b9cf3f172bb17fb36871c433d4ed32e2e5f

**Comment by Edelweiss** [comment]
@jcowey, @rla2118, @HolgerEssler, please test

Test scenario: add an MP3 number to an already existing DCLP file. The idno should save alongside the other idnos in the XML.

**Comment by rla2118** [comment]
@Edelweiss This works for me.  I added an MP3 number to http://litpap.info/editor/publications/91/dclp_meta_identifiers/183/editxml and it saved to the XML.

**Comment by jcowey** [comment]
Works now for me. I am closing.
