### ISSUE TITLE
SoSOL Editor: Overview Tab

### ISSUE THREAD

**Issue by Edelweiss** [DCLP/dclpxsltbox#220]
The overview tab doesn’t seem to work on this file

http://www.litpap.info/editor/publications/146/dclp_text_identifiers/294/edit

**Comment by m-k-r** [comment]
The links for overview and finalize are still in the html-sourcecode. It is working in master. 
I checked the files changed in development and as soon as [editor.css](https://github.com/DCLP/sosol/blob/development/public/stylesheets/editor.css) from development is used the tabs aren't working.

**Comment by Edelweiss** [comment]
@rla2118, yes, any geistesblitz will be most welcome but the issue relates to the DCLP version of the editor, which added a hierarchy level to the menu bar. I think it’s just like m-k-r said, we need to tweak the css.

**Comment by Edelweiss** [comment]
This could be a solution. I cannot test it, though.

https://github.com/DCLP/sosol/commit/dde4dac773c41c54be7d21493efdab8c79038568

@m-k-r, can be you please test it?

**Comment by m-k-r** [comment]
Tested on dclp-test and litpap. Overview is working again and the dclp dropdown menu is in front of janrain.
@rla2118  @jcowey , can you test finalization?

**Comment by jcowey** [comment]
http://litpap.info/editor/publications/169

was finalized

**Comment by jcowey** [comment]
There seems to be regression on this. When one uses the "x" to delete the field `overview` and then clicks save, the field does not disappear. The same applies when one deletes in the XML.

**Comment by jcowey** [comment]
Is 
DCLP/sosol@dde4dac
included in the XSLT that we are using at present, @m-k-r ?

**Comment by paregorios** [comment]
I can confirm that the CSS change made above is indeed in DCLP/sosol master branch, so as long as that is what's running at litpap.info, the CSS change should be in place.

@jcowey can you please check to see if this is now working on litpap?

**Comment by jcowey** [comment]
The XML functions properly, but the "Legacy Display Name" field does not disappear.

**Comment by paregorios** [comment]
@jcowey can you provide a screen capture of where the problem is?

**Comment by jcowey** [comment]
I have spoken to Carmen about this. It is not a big thing and Carmen will sort it out.

**Comment by Edelweiss** [comment]
https://github.com/DCLP/sosol/commit/a12e33b29c21b33e4cbcf93ebc5d41f28d73e8ee
