### ISSUE TITLE
DCLP HTML files: no volume or text number under Principal Edition

### ISSUE THREAD

**Issue by Edelweiss** [DCLP/dclpxsltbox#221]
With this file, there is no volume or text number under Principal Edition. 

http://www.litpap.info/dclp/64001

**Comment by jcowey** [comment]
This is basically a duplicate of #191.

**Comment by Edelweiss** [comment]
Then let’s close this one, it’s referenced in ticket #191

**Comment by paregorios** [comment]
Actually a duplicate for #212
