### ISSUE TITLE
DCLP html pages: XML links don’t work

### ISSUE THREAD

**Issue by Edelweiss** [DCLP/dclpxsltbox#222]
Example:

http://www.litpap.info/dclp/64001

the XML links don’t seem to work

**Comment by jcowey** [comment]
because of the changes to the DCLP branches

**Comment by m-k-r** [comment]
I made a [commit](https://github.com/DCLP/navigator/commit/1402c93e05573c1449e53931d474080836a82496) to development which should fix that but for some reason it didn't change the link.

**Comment by paregorios** [comment]
@m-k-r did you re-run generation of the HTML?

**Comment by m-k-r** [comment]
I used lein run in navigator/pn-indexer/ and stopped after html and texts were generated

**Comment by paregorios** [comment]
I'm going co-assign myself to this ticket so I can run this transform in our test harness and see if we get the problem with statically-generated HTML outside the navigator framework.

**Comment by m-k-r** [comment]
The XML links are working [now](https://github.com/DCLP/navigator/commit/0b663a12cf3075559516a670d9076f0e11ea62df).

**Comment by jcowey** [comment]
They are indeed. That is fantastic. Many thanks. I am now closing this issue.
