### ISSUE TITLE
Paptrac manual for DCLP servers

### ISSUE THREAD

**Issue by Edelweiss** [DCLP/dclpxsltbox#224]
#####################
#####################

/srv/data/papyri.info/
	- corpusoverview	# generates dclp-dropdown
	- git
		- navigator-new
			- pn-dispatcher	# creates dispatcher
			- pn-indexer	# indexing
			- pn-mapping	# mapping
			- pn-site	# apache root
			- pn-solr	# structure for solr
			- pn-sync	# creates sync
			- pn-xslt	# used in indexing
		- navigator-old(only dclp-test)
		- papyXillio	# git repository
	- idp.data	# git repository
	- jena	# numberserver
	- pn
		- docs	# site-docs
		- idp.html	#	html and txt files
	- solr	# solr-files
	- sosol
		- editor	# git repository
		- repo	# git repositories for canonical, boards and users
		- repo-development	# git repositories for development environment (uses canonical.git from repo)
		- shared
		- xsugar	# git repository
		- xsugar.log

/usr/local/
	- exist-db
	- jena
	- tomcat-solr
	- tomcat-sosol
	- tomcat-sync(only dclp-test)

/etc/httpd/
	- sites-available	# vhosts available
	- sites-enabled	# vhosts activated

####################
####################

## all services start at startup

# Start/Stop/Restart papyri.info/
service papyri.info
	start | stop | restart	# controls tc, solr, jena, xs
	start-tc | stop-tc	# sosol
	start-solr | stop-solr | restart-solr	# solr, dispatcher
	start-jena | stop-jena	# numberserver
	start-xs | stop-xs	# xsugar

# other services
service eXist-db start | stop | restart
service httpd start | stop | restart
service sshd start | stop | restart

##########################
##########################

# sync github, idp.data and canonical.git (as tomcat)
cd /srv/data/papyri.info/idp.data/ && git pull github && git pull canonical && git push canonical && git push github

# mapping:
service papyri.info stop-jena
rm -rf /srv/data/papyri.info/jena/*
cd /srv/data/papyri.info/git/navigator/pn-mapping/ && lein run map-all
service papyri.info start-jena

# indexing:
service papyri.info stop-solr
rm -rf /srv/data/papyri.info/solr/* && rm -rf /srv/data/papyri.info/pn/idp.html
rsync -avP /srv/data/papyri.info/git/navigator/pn-solr/* /srv/data/papyri.info/solr/
cd /srv/data/papyri.info/git/navigator/pn-indexer/ && lein run
service papyri.info start-solr

# dispatcher:
service papyri.info stop-solr
cd /srv/data/papyri.info/git/navigator/pn-dispatcher/ && mvn clean package
rm -rf /usr/local/tomcat-solr/webapps/dispatc*
rsync -avP /srv/data/papyri.info/git/navigator/pn-dispatcher/target/dispatch.war /usr/local/tomcat-solr/webapps/
service papyri.info start-solr

# sync:
cd /srv/data/papyri.info/git/navigator/pn-sync/ && mvn clean package

# editor
service papyri.info stop-tc
cd /srv/data/papyri.info/sosol/editor/ && bundle exec warble war
rm -rf /usr/local/tomcat-sosol/webapps/edito*
rsync -avP /srv/data/papyri.info/sosol/editor/editor.war /usr/local/tomcat-sosol/webapps/
service papyri.info start-tc

# webrick
/srv/data/papyri.info/sosol/editor/ && rbenv shell jruby-1.7.12 && bundle exec rails server

# generate new dropdown html
cd /srv/data/papyri.info/corpusoverview/ && java -Xms512m -Xmx1536m net.sf.saxon.Transform -o:fix047_generateCorpusOverview.html -it:HTML -xsl:fix047_generateCorpusOverview.xsl
rsync -avP dclp*.html /srv/data/papyri.info/git/navigator/pn-site/

# something isn't working
# --> restart service (how is described in services)
# --> if it's still not working look at the logs
tail /usr/local/tomcat-sosol/logs/catalina.out
tail /usr/local/tomcat-solr/logs/catalina.out
tail /usr/local/tomcat-solr/logs/catalina.out
tail /srv/data/papyri.info/sosol/xsugar.out
tail /usr/local/jena/jena.log
tail /usr/local/exist-db/tools/wrapper/logs/wrapper.log
tail /var/log/httpd/error_log
# --> still no solution? --> restart
# --> problem still exists? --> how old is your last snapshot?

**Comment by Edelweiss** [comment]
DCLP Server in [PapTrac](http://147.142.225.252/paptrac/wiki/dclpServer)

**Comment by jcowey** [comment]
I am closing this as I am pretty sure that all the info is now in paptrac as stated above
