### ISSUE TITLE
ensure XSLTs work with new dimensions markup

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#225]
Editor support for new, more detailed markup on dimensions was added with completion of issue #192. Now we need to check to see if the XSLTs handle that well and, if not, upgrade them to do so.

Adding to Würzburg workshop milestone since #192 was assigned in that milestone.

**Comment by paregorios** [comment]
There seems to be only one XML file in idp.data/DCLP (master) that makes use of this markup at present: TM143318.

**Comment by paregorios** [comment]
TM143318 has markup like:

```xml
<physDesc>
   <objectDesc form="sheet">
      <supportDesc>
         <support>
            <material>ostracon; pottery</material>
            <dimensions>
               <width unit="cm">13 cm</width>
               <height unit="cm">23.3 cm</height>
            </dimensions>
         </support>
```

The current XSLTs produce:

![support-dimensions](https://cloud.githubusercontent.com/assets/263285/23710050/05b7562e-03e1-11e7-837e-4c956821c6ab.png)

The question for @rla2118 now is, what do you want to see for dimensions? Would you like to keep it all on one line (as now), but perhaps add something helpful so you get something like:

```
Support/Dimensions:	ostracon; pottery (13 cm x 23.3 cm)
```

or 

```
Support/Dimensions:	ostracon; pottery (13 cm wide x 23.3 cm high)
```

Alternatively, we could break everything out on separate lines like this:

```
Support material: ostracon; pottery
Support dimensions: 13 cm wide x 23.3 cm wide
```

Or other variations on one of the above themes.

Preference? (cc @jcowey @HolgerEssler)

**Comment by rla2118** [comment]
I would opt for 
Support material: ostracon; pottery
Support dimensions: 13 cm wide x 23.3 cm high
It's important to be explicit about the axis (width and height) that the measures describe.

**Comment by paregorios** [comment]
OK, we'll undertake to make that happen.

**Comment by paregorios** [comment]
Reassigning to @rla2118 for review. 

New transform results look like: http://dclp.github.io/dclpxsltbox/output/dclp/144/143318.html

Note that files without ```<dimensions>``` included are handled gracefully, e.g., http://dclp.github.io/dclpxsltbox/output/dclp/144/143337.html

**Comment by rla2118** [comment]
Dimensions looks fine.  I see, however, that "title", https://github.com/DCLP/idp.data/blob/master/DCLP/144/143318.xml#L7, is not displaying.

**Comment by paregorios** [comment]
@rla2118 the contents of the ```<title>``` element are not displayed in the page header because #206 has not yet been implemented per previous prioritization discussion, q.v.

The content "Dactylic octameters on Pallas Athena" is not anywhere on the HTML review page  now because [three days ago you removed it from the ```<term type="overview">``` element and moved it to the ```<titleStmt><title>```](https://github.com/DCLP/idp.data/commit/e806a1623cf5ec5df5fca577a273d5f9ce8357c1). That's why the "Contents" rubric is now empty ([it depends on ```<term type="overview">```](https://github.com/DCLP/navigator/blob/master/pn-xslt/metadata.xsl#L340)). Note that for the review transforms I am using the latest rev of idp.data ([@799aa485](https://github.com/DCLP/idp.data/commit/799aa4858d0f4979bfcbda7f49a406388af6ecf7)); litpap.info at the moment seems to be behind.

Recommend we proceed to merge the code relevant to ```<dimensions>``` into master and take further discussion about ```<title>``` and the "Contents" rubric etc. to #206.

OK?

**Comment by rla2118** [comment]
OK. We do not plan to populate "Contents" going forward. Right, @jcowey?

**Comment by paregorios** [comment]
@rla2118 I moved your query to @jcowey to #206; @jcowey please answer there

**Comment by paregorios** [comment]
I'm taking this ticket to merge ```<dimensions>``` code change into master.

**Comment by paregorios** [comment]
This code is now in master on navigator at [@3f7091b](https://github.com/DCLP/navigator/commit/3f7091bb94b1c32128e530ec5116c392250e3e89)
