### ISSUE TITLE
SoSOL Meta Editor: CWKB numbers are not saved

### ISSUE THREAD

**Issue by Edelweiss** [DCLP/dclpxsltbox#226]
make sure URL is assembled correctly

**Comment by Edelweiss** [comment]
URL patterns for authors

- tlg (Greek)
  - http://data.perseus.org/catalog/urn:cts:greekLit:tlg2200
- phi (Latin)
  - http://data.perseus.org/catalog/urn:cts:latinLit:phi2200
- stoa (Latin)
  - http://catalog.perseus.org/catalog/urn:cts:latinLit:stoa0040
- cwkb
  - http://cwkb.org/author/id/2402/rdf

URL patterns for works

- tm
  - http://www.trismegistos.org/authorwork/1146
- tlg (Greek)
  - http://catalog.perseus.org/catalog/urn:cts:greekLit:tlg0059.tlg018
- stoa (Latin)
  - http://catalog.perseus.org/catalog/urn:cts:latinLit:stoa0040.stoa016
- cwkb
  - http://cwkb.org/work/id/1411/rdf

**Comment by Edelweiss** [comment]
[ generate refs for TLG, TM, STOA, PHI and CWKB (Ticket #226, SoSOL Meta Editor: CWKB numbers are not saved)](https://github.com/DCLP/sosol/commit/ea46b26fd4ed50832097d3c04a2af702e14e6d24)

**Comment by Edelweiss** [comment]
@jcowey, @rla2118, @HolgerEssler, please test

**Comment by jcowey** [comment]
Works for me, when going through an old entry (entered in March workshop in Würzburg) to the editorial board.

**Comment by jcowey** [comment]
Also works for me at entry level.

**Comment by jcowey** [comment]
Closing

**Comment by paregorios** [comment]
Where (repos and branch) were the relevant changes committed and have they been pushed to github?

**Comment by jcowey** [comment]
Related to https://github.com/DCLP/dclpxsltbox/issues/273, where the commits are listed.

**Comment by Edelweiss** [comment]
Plus the one mentioned above

[ generate refs for TLG, TM, STOA, PHI and CWKB (Ticket #226, SoSOL Meta Editor: CWKB numbers are not saved)](https://github.com/DCLP/sosol/commit/ea46b26fd4ed50832097d3c04a2af702e14e6d24)

**Comment by jcowey** [comment]
CWKB numbers are now being saved as expected (most recently in January 2018)
