### ISSUE TITLE
SoSOL Meta Editor: sign in text

### ISSUE THREAD

**Issue by Edelweiss** [DCLP/dclpxsltbox#228]
When signing in for the first time, you’re prompted to use your papyri.info account. Should read »litpap.info« of course.

**Comment by Edelweiss** [comment]
Does that solve the problem?

[papyri.info -> litpap.info ](https://github.com/DCLP/sosol/commit/6e40ab19d9d8eee790c6036d8437121ef2730784)

The e-mail button has Hugh Cayless as a receiver, though.

Furthermore I noticed that the footer mentions papyri.info as responsible for the site and Hugh Cayless as contact for feedback:

![bildschirmfoto 2017-04-07 um 10 00 18](https://cloud.githubusercontent.com/assets/612862/24791206/954786e2-1b79-11e7-89f7-f3726a921471.png)

**Comment by Edelweiss** [comment]
Instead of Hugh Cayless use Rodney’s e-mail address

Rodney Ast <ast@uni-heidelberg.de>

**Comment by Edelweiss** [comment]
Produced by

The Duke Collaboratory for Classics Computing
& the Institute for the Study of the Ancient World
& the Institute of Papyrology Heidelberg

**Comment by Edelweiss** [comment]
About:
    BP
    Trismegistos
    HGV
    DDbDP
    APIS
    Papyri.info -> Litpap.info

**Comment by Edelweiss** [comment]
can be tested with the next updates of the [navigator](https://github.com/DCLP/navigator/commit/1b30216b1040458aeb46c5112ecb7c7ae93ddbf8) and [sosol](https://github.com/DCLP/sosol/commit/9d89f58286889582eac8fed7f7b313a000170f4f)

**Comment by jcowey** [comment]
This is now as desired. I am closing it.
