### ISSUE TITLE
Display "Ancient Archive" with Link in HTML

### ISSUE THREAD

**Issue by Edelweiss** [DCLP/dclpxsltbox#229]
Make the archive name clickable so that it takes you to the website of the archive

**Comment by paregorios** [comment]
@Edelweiss is this for the navigator HTML?

**Comment by Edelweiss** [comment]
Yes, the information is already displayed in the preview of the metadata editor:

https://github.com/DCLP/sosol/blob/master/app/views/hgv_meta_identifiers/preview.haml#L136

The data can be scooped from these xpaths:

archiveName
/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msIdentifier/collection[@type='ancient']

archiveLink
/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msIdentifier/collection[@type='ancient']/@ref

But as far as I can see there is no data yet in DCLP’s idp.data repository.

**Comment by paregorios** [comment]
@Edelweiss thanks. I've added the "tweak XSLT" label. I think we need to leave this issue on the backlog until there is actual data. Do you agree @jcowey ?

**Comment by jcowey** [comment]
Yes I agree @paregorios

**Comment by paregorios** [comment]
Shall we un-assign from @Edelweiss for the time being?

**Comment by jcowey** [comment]
Yes unassign @Edelweiss

**Comment by paregorios** [comment]
It appears that there is now corresponding data in idp.data/DCLP, i.e., [TM 59946](https://github.com/DCLP/idp.data/blob/master/DCLP/60/59946.xml#L28), so we can move forward to implementation.

To restate the ask:

When ```<collection type="ancient">``` appears in ```<msIdentifier>```, emit a new "Archive" rubric in the DCLP metadata area (immediately before "Fragments") and populate it with the content of ```<collection type="ancient">```. If ```<collection type="ancient">``` also has a ```ref``` attribute, wrap that output in ```<a href="{@ref}">```.

**Comment by paregorios** [comment]
There's a problem with the data in ```@ref``` on this document. I've created a new ticket for that issue: #244

**Comment by wsalesky** [comment]
I can make this change independent of the data issues.

**Comment by wsalesky** [comment]
@paregorios 
Added a test for `t:collection[@type="ancient"]` in `pn-xslt/metadata-dclp.xsl`

Test includes handling for `t:collection`  adds HTML link if `@ref` is present.  Would it be useful to test for valid @refs? (ie, only those starting with "http://" or "https://")

**Comment by paregorios** [comment]
I'm not a huge fan of papering over bad data in the transform, though there are certainly other places in this project where we do that. More immediately, I think it might be better to go ahead and emit the ```@ref``` value in an ```<a href>``` in this case because it will probably just work anyway in some browsers and, if it doesn't, it's a mistake that most users will be able to fix manually.

**Comment by wsalesky** [comment]
Okay. That matches current behavior.
