### ISSUE TITLE
SoSOL Meta Editor: Hide fragments in »author and work«

### ISSUE THREAD

**Issue by Edelweiss** [DCLP/dclpxsltbox#230]
https://github.com/DCLP/sosol/blob/master/app/views/dclp_meta_identifiers/_work.haml#L100

**Comment by Edelweiss** [comment]
[ok](https://github.com/DCLP/sosol/commit/034d89db614cc062e1b72031fca)

**Comment by Edelweiss** [comment]
@jcowey, @rla2118, @HolgerEssler, please test

**Comment by jcowey** [comment]
This is now OK. CLosing.
