### ISSUE TITLE
SoSOL Meta Editor: keywords cannot be saved

### ISSUE THREAD

**Issue by Edelweiss** [DCLP/dclpxsltbox#231]
Keywords are lost after pressing the »save« button.

**Comment by jcowey** [comment]
This still seems to be a problem.

**Comment by Edelweiss** [comment]
can be tested in the next [version](https://github.com/DCLP/sosol/commit/edfbd75b7be7642ea2b38db0b47fe4436be7667e) of the editor

**Comment by jcowey** [comment]
This works for me. I am closing it.
