### ISSUE TITLE
SoSOL metadata editor: display Checklist short titles

### ISSUE THREAD

**Issue by jcowey** [DCLP/dclpxsltbox#233]
When a biblio entry includes the following section: 
```
<note type="papyrological-series">
    <bibl>
      <title level="s" type="short-Checklist" n="1">BKT 2</title>
    </bibl>
</note>
```
please display the content of the title tag underneath what is displayed on the basis of the biblio number.

**Comment by paregorios** [comment]
@jcowey is there any similar requirement where the navigator HTML is concerned, or is that already working ok?

**Comment by Edelweiss** [comment]
Example biblio file

[BKT 2](https://github.com/DCLP/idp.data/blob/master/Biblio/96/95050.xml#L10)

**Comment by Edelweiss** [comment]
@jcowey & Co., is that what you would expect to see?

[95050](http://papyri.info/biblio/95050). Diels Hermann, BKT 2 (1905)

Underlying html:

```html
<!DOCTYPE html>
<html id="content">
    <p id="b95050"><a href="http://papyri.info/biblio/95050" target="_blank" class="id">95050</a>.
                <span class="author">Diels Hermann</span>, <span class="title">BKT 2</span><span> (1905)</span>
    </p>
</html>
```

**Comment by HolgerEssler** [comment]
I would expect to see just "BKT 2".

**Comment by rogerbagnall** [comment]
I know only what I see in the string of comments, but if it's short Checklist then I agree with Holger that BKT 2 would be all you would expect.

**Comment by Edelweiss** [comment]
ok, can be tested with the next [eXist](https://github.com/Edelweiss/papyXillio/commit/a65a9d525b3391cd1a36d2d53c9cf424e2db093c) server update

**Comment by jcowey** [comment]
95050 appears to work fine for me. 79329 displays "P.Oxy. 76P.Oxy. 76"

**Comment by jcowey** [comment]
This now works. eXist server had to be updated. As soon as that happened everything was OK.
