### ISSUE TITLE
Error message after voting

### ISSUE THREAD

**Issue by HolgerEssler** [DCLP/dclpxsltbox#234]
After voting I often get the error message "We are sorry, but something went wrong". The text seems to be processed correctly, with my comments intact. Example: http://litpap.info/editor/publications/328, DCLP Meta 140276, voted on Fri Mar 10, 2017 09:57:20.

**Comment by rla2118** [comment]
@HolgerEssler Does this problem persist?

**Comment by paregorios** [comment]
still waiting for a reply from @HolgerEssler to query from @rla2118 above

**Comment by HolgerEssler** [comment]
By now, it does not seem to occur any more.
