### ISSUE TITLE
transforms no longer producing apparatus

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#238]
Spotted by @leoba:

Commit 72f474c99b73acb878707436949a3cffe28c6778 of master output no longer includes ```<div id="apparatus">```. This likely results from changes that @sarcanon and I merged from epidoc-xslt master on Friday ([r2516](https://sourceforge.net/p/epidoc/code/2516/) - [r2519](https://sourceforge.net/p/epidoc/code/2519/)); somehow we missed the effective change. 

I'll undertake to try to reverse this change urgently. 

Blocker for #126.

**Comment by paregorios** [comment]
@leoba stepping back your epidoc-xslt workspace to [r2500](https://sourceforge.net/p/epidoc/code/2500/) should allow you to run dclpxsltbox/bin/2html.sh and get a set of HTML that has the apparatus.

**Comment by paregorios** [comment]
In work on svn branch https://sourceforge.net/p/epidoc/code/HEAD/tree/branches/dclp-issue238/

**Comment by paregorios** [comment]
I suspect that this is due to the fact that the epidoc stylesheets now use two apparatus-related parameters (```internal-app-style``` and ```external-app-style```) instead of the one that DCLP expects: ```apparatus-style```.

**Comment by paregorios** [comment]
And if that is the case, it's pretty clear that papyri.info is depending on a down version of the EpiDoc stylesheets, because [MakeHTML.xsl on papyri.info/master](https://github.com/papyri/navigator/blob/master/pn-xslt/MakeHTML.xsl#L290) still only uses the single ```apparatus-style``` variable. 

So, by stepping up to the latest version of the EpiDoc stylesheets, DCLP will be making the back-integration to papyri.info harder (fyi @hcayless).

**Comment by paregorios** [comment]
The change to the EpiDoc stylesheets that introduced this change is over two years old: [r2275](https://sourceforge.net/p/epidoc/code/2275/). This implies that papyri.info is relying on epidoc xsl code that is at least that old.

**Comment by jcowey** [comment]
Just something to bear in mind @paregorios. We still have not solved the business of deploying the XSLT you use to produce the static HTML transforms in the litpap.info navigator and editor environment. 
This is one of the things that I regard as highest priority for the next weeks.
If it were in place that we could meaningfully test all new stuff in the live environment. 
I hope my thoughts are relatively clear.

**Comment by paregorios** [comment]
@jcowey understood, and I agree with your prioritization. I'm trying to make sure we have clean code in the repos in order to support that effort.

**Comment by paregorios** [comment]
As I inferred above, [the last change to MakeHTML.xsl](https://github.com/papyri/navigator/blob/4a841f5fbcf624c845eac79ff3d53d09254a73c6/pn-xslt/MakeHTML.xsl) predates the EpiDoc xslt parameters change at issue here. 

Given that means anything subsequent on the EpiDoc side is untested in production papyri.info, I think we need to revert the merge from EpiDoc master to our DCLP branch until we can get a plan across all the projects to handle this update. I'll undertake the rollback momentarily.

**Comment by paregorios** [comment]
@leoba this should be resolved (i.e., no longer blocking #126). To proceed, please first:

- do a ```git pull origin master``` in dclpxsltbox
- do an ```svn update``` in navigator/epidoc-xsl

Sorry for the hassle.

**Comment by paregorios** [comment]
@leoba was able to get back to work on #126, so closing this issue.
