### ISSUE TITLE
unwanted accent included in apparatus entry

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#240]
*Splitting out from original issue #126. Block this issue for completion of #126.*

@andreabernini originally reported:

> col. II 139 https://github.com/DCLP/idp.data/blob/master/DCLP/129/128960.xml#L162
> Leiden+: ```Ἀχι]λῆ(^)’```
> Displayed in the apparatus: ```ῆ’ papyrus```
> Expected: ```ῆ papyrus```

The corresponding XML reads:

```xml
<supplied reason="lost">ἠ’ Ἀχι</supplied>λ<hi rend="circumflex">ῆ</hi>’ 
```

which is what I would have expected from the Leiden+. So, as @leoba noted, the acute accent in the final text node is coming along for the ride in the apparatus.

I think this ticket needs some clarification from papyrologists ( @rla2118 , @jcowey , @HolgerEssler ) before we can proceed:

Is the expectation that all diacriticals be removed in apparatus, or only when they appear in a word together with ```<hi rend``` (or some other logical ruleset)?

**Comment by rla2118** [comment]
Yes, only diacriticals within <hi rend> should display.  I don't understand why there is an apostrophe here and with ἠ’ in the Leiden+.  It should be [ἢ Ἀχι]λ η(^) = XML <supplied reason="lost">ἢ Ἀχι</supplied>λ<hi rend="circumflex">ῆ</hi>

**Comment by paregorios** [comment]
@rla2118 just to make sure I understand: the acute accent as final character in this string is, in your view, just an error. Or should we check the original publication?

**Comment by jcowey** [comment]
I have had a brief look at the original edition. Not really sure what has happened here. I need more time to see what has happened. It looks as if unnecessary diacritical signs have found their way into the text strings.

**Comment by jcowey** [comment]
What I think I would expect is:
```
<supplied reason="lost">ἠ Ἀχι</supplied>λ<hi rend="circumflex">ῆ</hi> <hi rend="diaeresis"><hi rend="acute">ἴ</hi></hi><unclear>σχ</unclear>ωσι
```

instead of 
```
<supplied reason="lost">ἠ’ Ἀχι</supplied>λ<hi rend="circumflex">ῆ</hi>’ <hi rend="diaeresis"><hi rend="acute">ἴ</hi></hi><unclear>σχ</unclear>ωσι
```
In
http://litpap.info/dclp/128960
This is the image:

http://163.1.169.40/gsdl/collect/POxy/index/assoc/HASHa2b8/bc5cf739.dir/POxy.v0075.n5032.a.01.hires.jpg

not located the position yet

**Comment by paregorios** [comment]
Per discussion with @rla2118 and @jcowey I will undertake to fix this mistake in XML to read as follows:

```xml
<supplied reason="lost">ἢ Ἀχι</supplied>λ<hi rend="circumflex">ῆ</hi>
```

**Comment by paregorios** [comment]
This is now in work in DCLP/idp.data branch "issue240"

**Comment by paregorios** [comment]
Waiting for review of the XML modification by @jcowey or @rla2118 on https://github.com/DCLP/idp.data/pull/4
