### ISSUE TITLE
multiple incorrect apparatus entries for single word with multiple diacritics

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#241]
*Splitting out from issue #126; block this issue for completion of #126*

@andreabernini originally reported:

> col. II 152 https://github.com/DCLP/idp.data/blob/dclp/DCLP/129/128960.xml#l164
> Leiden+:  ```ἰ(´¨) ή(´) ϊ(¨)ε```
> Displayed in the apparatus: 
> ^ ii.34. ```ίήϊε papyrus : ίϊίήϊε papyrus```
> ^ ii.34. ```ίήϊε papyrus```
> ^ ii.34. ```ίήϊε papyrus```
> Expected:``` ΐήϊε papyrus```

After initial analysis, @leoba observed:

> [https://github.com/DCLP/idp.data/blob/master/DCLP/129/128960.xml#L175](https://github.com/DCLP/idp.data/blob/master/DCLP/129/128960.xml#L175) (Displayed in the apparatus: ίήϊε papyrus : ίϊίήϊε papyrus, plus two additional entries): The complete tagging here is `<hi rend="acute"><hi rend="diaeresis">ἰ</hi></hi><hi rend="acute">ή</hi><hi rend="diaeresis">ϊ</hi>ε` -so we have a nested hi, which results in the duplicate views on the same line (what we see in the first example), but there’s the additional problem that each time there is a `<hi>` tag a new entry is generated for the apparatus, resulting in multiple entries for the same word. This seems like a more difficult problem to solve, since the words themselves aren’t tagged, but it should be its own issue.

So, I'll restate (and ask @rla2118 @jcowey @HolgerEssler to confirm) that the desired behavior is as follows:

> Any single word that appears in the XML text and that includes one or more ```<hi rend``` elements must receive one and only one corresponding apparatus entry. 

Yes? No? Otherwise?

**Comment by rla2118** [comment]
Yes, that's right.

**Comment by paregorios** [comment]
Thanks. We'll put this in the queue to address.

**Comment by wsalesky** [comment]
@paregorios I have a fix for this, should I wait for https://github.com/DCLP/dclpxsltbox/issues/126 to be resolved before filing it?

**Comment by paregorios** [comment]
@leoba can you please coordinate with @wsalesky about this issue and #126, which is currently assigned to you? I'd like to get these knocked out and if necessary we can hand off #126 to @wsalesky as well. Thanks.

**Comment by leoba** [comment]
Sorry @wsalesky and @paregorios  I didn't see that I was tagged here. I've just sent changes to epidoc-xslt that handle #126 and I think have the effect of handling #241 as well. Have just added an edit to my note over there.

**Comment by wsalesky** [comment]
@leoba  this ticket handles a slightly different issue. Your code addresses nested tei:hi elements, this issue is triggered by multiple tei:hi elements within a single apparatus, so they could be siblings or nested in some other way. Current code probably cuts down on dups that are produced by nested tei:hi, but the sample xml above still produces duplicates. 

Will integrate my fix with @leoba code.

**Comment by wsalesky** [comment]
**XSLT:**  epidoc-xslt/htm-tpl-apparatus.xsl
Changes: added a xsl:for-each-group to apparatus generation to suppress duplicates.

**Branch:** svn.code.sf.net/p/epidoc/code/branches/dclp-issue241/example-p5-xslt

**HTML pages changed:**

```
        modified:   output/dclp/114/113266.html
	modified:   output/dclp/129/128955.html
	modified:   output/dclp/129/128956.html
	modified:   output/dclp/129/128960.html
	modified:   output/dclp/129/128970.html
	modified:   output/dclp/155/154385.html
	modified:   output/dclp/60/59324.html
	modified:   output/dclp/60/59332.html
	modified:   output/dclp/60/59491.html
	modified:   output/dclp/60/59959.html
	modified:   output/dclp/61/60175.html
	modified:   output/dclp/61/60456.html
	modified:   output/dclp/62/61917.html
	modified:   output/dclp/63/62391.html
	modified:   output/dclp/63/62400.html
	modified:   output/dclp/63/62416.html
	modified:   output/dclp/63/62419.html
	modified:   output/dclp/63/62423.html
	modified:   output/dclp/63/62448.html
	modified:   output/dclp/63/62460.html
	modified:   output/dclp/63/62469.html
	modified:   output/dclp/63/62471.html
	modified:   output/dclp/63/62474.html
	modified:   output/dclp/63/62477.html
	modified:   output/dclp/63/62499.html
	modified:   output/dclp/63/62564.html
	modified:   output/dclp/63/62931.html
	modified:   output/dclp/64/63789.html
	modified:   output/dclp/66/65077.html
	modified:   output/dclp/66/65078.html
	modified:   output/dclp/66/65079.html
	modified:   output/dclp/66/65436.html
	modified:   output/dclp/68/67988.html
	modified:   output/dclp/69/68628.html
```

**Comment by paregorios** [comment]
The merge reports above do not seem to have been successful. I'm working on resurrecting these changes.
