### ISSUE TITLE
TM 59946 has invalid @ref value on collection element

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#244]
In [TM 59946](https://github.com/DCLP/idp.data/blob/master/DCLP/60/59946.xml#L28), one encounters:

```xml
<collection type="ancient" ref="www.trismegistos.org/archive/160">Ostraca from 
a Cellar in Philadelpheia; so-called "Kleitorios" Archive</collection>
```

[According to the *TEI Guidelines*](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.canonical.html#tei_att.ref), the value of ```@ref``` must be "one or more URIs, separated by whitespace." In order to be a valid URI, a string must begin with a [Registered URI Scheme](http://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml) string, but the value "www.trismegistos.org/archive/160" does not. It only has the **[authority](https://tools.ietf.org/html/rfc3986#section-3.2)** (```www.trismegistos.org```) and **[path](https://tools.ietf.org/html/rfc3986#section-3.3)** (```/archive/160```) components. In order for this to be a valid URI, it must begin with either "http://" or "https://", whichever is actually used.

@jcowey : If this was entered via the PE, the question occurs: can the PE enforce the entry of valid http(s) URIs in order to prevent this sort of thing happening?

cc @Edelweiss

**Comment by jcowey** [comment]
[TM 59946](https://github.com/DCLP/idp.data/blob/master/DCLP/60/59946.xml#L28) was indeed entered via the editor. 
Enforcing valid URIs. I am not sure. This is question for @Edelweiss

**Comment by paregorios** [comment]
reassigning to @Edelweiss to ask if it is possible to validate URIs on entry

**Comment by Edelweiss** [comment]
Yes, of course this is possible. I’m wondering, though, whether we want special treatment for just this particular field in order to enforce valid collection links while leaving all other entry fields as free text and therefore prone to invalid data or whether this might be the right time to remodel the entry mask as a whole and somehow ensure that each field is pre-checked (for instance by comparing its content to a given regular expression) before passing the data to the action controller that is responsible for saving the data in EpiDoc xml.

**Comment by paregorios** [comment]
I propose the following:

 [ ] Manually fix this entry (I'll do it momentarily).
 [ ] Hunt down and fix other examples in the data manually (also me).
 [ ] Close this ticket as resolved once the preceding two items are complete.
 [ ] Create a new "enhancement" ticket for pre-save validation in the editor and include the above use case in the description (also me).

Is that OK with you @Edelweiss, @jcowey, @rla2118 ?

**Comment by Edelweiss** [comment]
Yes, that sounds great. I looked at it this morning, it seems that this is the only case of ref="www…". I think it’s strange that it didn’t cause any validation errors. Does that mean that the EpiDoc scheme is a little lax there? For other definition violations, such as a missing msIdentifier, validation does a good job, though.
Thank you very much, paregorios

**Comment by paregorios** [comment]
I've created a new ticket #249 in which to discuss more generally the idea of "pre-save validation."
