### ISSUE TITLE
cannot change "principal" to "reference" editions in editor

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#245]
*see related issue #313*

**Comment by paregorios** [comment]
[Here, incidentally, is the distinction that @rogerbagnall drew between "principal edition" and "reference edition"](https://github.com/DCLP/dclpxsltbox/issues/135#issuecomment-98377388) when confusion erupted previously. It doesn't provide an answer for my question above, but it is relevant.

**Comment by rla2118** [comment]
I don't know if this is related to the problem that users have experienced of not being able to save reference editions.  The default seems to be "principal edition."  I'm drawing @Edelweiss into the conversation.

**Comment by paregorios** [comment]
@rla2118 is the "unable to save reference editions" problem ticketed somewhere?

**Comment by rla2118** [comment]
No, because I wondered if this ticket is related.

**Comment by paregorios** [comment]
@rla2118 if you have (or can get) a good step-by-step description of what's happening to users when they try to do that, can you paste it in here?

**Comment by rla2118** [comment]
Here is what Thomas Backhuys reports in submission notes for http://litpap.info/editor/publications/378# = TM 59221.

"Text according to edition P.Köln II 58 (cannot save this biblio reference as "reference edition": editor changes name to "principal edition")"

When he tries to change the biblio reference from "reference edition" to "principal edition" the system defaults to "principal edition".  The XML looks like this

         <div type="bibliography" subtype="principalEdition">
            <listBibl>
               <bibl n="1" type="reference" subtype="principal">
            
                  <title level="s" type="short-Checklist" n="1">P.Köln 2</title>
                  <author n="1">
                     <forename>Bärbel</forename>
                     <surname>Kramer</surname>
                  </author>
                  <pubPlace n="1">Opladen</pubPlace>
                  <date>1978</date>
                  
                  <ptr target="http://papyri.info/biblio/9119"/>
                  <biblScope n="1" unit="numbers">58</biblScope>
                  <biblScope n="2" unit="volume">2</biblScope>
               </bibl>
               <bibl n="2" type="publication" subtype="principal">
            
                  <title level="j" type="short-BP">ZPE</title>
                  <author n="1">
                     <surname>Merkelbach</surname>
                     <forename>Reinhold</forename>
                  </author>
                  <date>1974</date>
                  
                  <ptr target="http://papyri.info/biblio/50165"/>
                  <biblScope n="1" unit="volume">14</biblScope>
                  <biblScope n="2" unit="pp">97-113</biblScope>
               </bibl>
            </listBibl>

**Comment by paregorios** [comment]
From what @rla2118 reports above, this sounds indeed like something that stems from an editor behavior. I'm tagging it accordingly and leaving it assigned to @Edelweiss.

**Comment by Edelweiss** [comment]
google sheet for [duplicate biblio refs](https://docs.google.com/spreadsheets/d/1JUDWSgsxUZvndGuOG1hmEL5_ENCQmeI_L3G-5B-DZ9A/edit#gid=1058211202)

**Comment by paregorios** [comment]
@jcowey do you know what needs to be done here?

**Comment by paregorios** [comment]
Multiple users at the NYC event have experienced the same problem with the editor that @rla2118 describes above, namely: attempting to change the type of a citation from "principal" to "reference" (or similar), saving the metadata, and then discovering that the change has not been made.

**Comment by Edelweiss** [comment]
https://github.com/DCLP/sosol/commit/6e663d526d9699c84fb4bf7bd358872b99aba043

**Comment by jcowey** [comment]
Tested and works for me
