### ISSUE TITLE
unwanted whitespace inside (())

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#246]
For some values of the ```type``` attribute on the ```<g>``` element, the XSLT renders and opening double-parentheses "((" followed by the value of the ```type``` attribute and closed with an opposite double-parentheses "))".

In some, perhaps all, cases, extra whitespace is getting produced after the value of the ```type``` attribute, but before the closing double-parentheses "))".

Here's an example from [TM 112363, col. i, l. 11](https://github.com/DCLP/idp.data/blob/master/DCLP/113/112363.xml#L108):

```xml
<lb n="11" break="no"/><supplied reason="lost">τορί</supplied>αν γέγραφεν,<g type="ano-stigme"/> ἄμεμ
```

produces this in the output:

```[τορί]αν γέγραφεν, ((ano-stigme )) ἄμεμ-```

the underlying HTML markup reveals the whackiness:

```html
<br id="ai-l11">[τορί]αν γέγραφεν,
<text> ((</text>ano-stigme
<text>)) </text> ἄμεμ-<br id="ai-l12">
```

AFAIK, ```<text>``` is not an HTML element at all and shouldn't be getting emitted. There is some kind of breakage in the stylesheet that's causing an ```<xsl:text>``` element (which is presumably there to **control** unintended whitespace madness) to get dumped into the HTML output, and its also taking along a whitespace node for the ride.

**Comment by paregorios** [comment]
Marking this with priority: high because it's just so deeply wrong ...

**Comment by wsalesky** [comment]
There is actually a `<text>` element in the XSLT (epidoc-xslt/htm-teig.xsl), I'm guessing it is just a typo.

**Comment by paregorios** [comment]
yeah, in teig.xsl lines 304 and 307 we should have ```<xsl:text>``` instead of ```<text>```

**Comment by paregorios** [comment]
as @wsalesky said last night in email ;)

**Comment by wsalesky** [comment]
@paregorios So, what is the workflow for the epidoc xslt? Should I create an svn branch?

**Comment by paregorios** [comment]
@wsalesky yes, I think that's the way to go ... create a branch like ```/branches/dlcp-issue246``` from ```/branches/dclp```.

**Comment by wsalesky** [comment]
@paregorios 
Not sure I have permissions to create branches. I'm getting a permissions denied error when creating the new branch:
`svn: E000013: Can't open file '/svn/p/epidoc/code/db/txn-current-lock': Permission denied`

**Comment by wsalesky** [comment]
@paregorios 
Okay, change committed to `/branches/dclp-issue246`

**Comment by paregorios** [comment]
This fix was merged to ```/branches/dclp``` in the EpiDoc example-p5-xslt svn repos at [r2532](https://sourceforge.net/p/epidoc/code/2532/) and new review files generated and posted to the web with @cd6ef5a
