### ISSUE TITLE
litpap.info metadata HTML does not match dclpxsltbox metadata HTML

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#250]
As discussed with @jcowey and @m-k-r in tagup today. I have run a new set of transforms (now visible online), and this picked up @m-k-r's latest changes to navigator code; however, we can still see a difference regarding the principal edition bibliography. 

Compare [dclpxsltbox for TM62103](http://dclp.github.io/dclpxsltbox/output/dclp/63/62103.html):

![screen shot 2017-03-29 at 11 41 44 am](https://cloud.githubusercontent.com/assets/263285/24465981/cb6126f4-1474-11e7-83eb-c407ca4f81fc.png)

with [litpap.info for TM62103](http://litpap.info/dclp/62103):

![screen shot 2017-03-29 at 11 41 56 am](https://cloud.githubusercontent.com/assets/263285/24465990/d41fcc5a-1474-11e7-8bc9-2356edb14fee.png)

Litpap is still not showing us the full citation detail for principal edition. 

The dclpxsltbox run snapshotted above was made as follows:

 - DCLP/idp.data branch master@5392c82d19aa
 - DCLP/navigator branch master@64f895f6
 - navigator/epidoc-xslt svn:^/branches/dclp/example-p5-xslt at r2547
 - ```java -jar ../dclpxsltbox/bin/claxon-1.0.0-SNAPSHOT-standalone.jar --xsl ../navigator/pn-xslt/MakeHTML.xsl --dir ../idp.data/DCLP/ --out ../dclpxsltbox/output/dclp/ --ext .html collection dclp analytics no cssbase ../../css jsbase ../../js path /Users/paregorios/Documents/files/D/dclp-xslt/dclpxsltbox/../idp.data```

**Comment by paregorios** [comment]
I have just noticed that there is another divergeance. Litpap is still showing us a "Support/dimensions" rubric, instead of the newer, separate "Support Material" and (when present) "Support Dimensions" rubrics. That means that litpap HTML not only does not reflect fixes to #212 but also #225.

**Comment by paregorios** [comment]
I cannot myself any longer ssh into litpap to inspect the repository clones and pursue this issue further. The credentials provided me in January by @m-k-r no longer work ("connection refused" on the port previously specified). Therefore assigning this ticket to @m-k-r for followup. 

cc @jcowey

**Comment by paregorios** [comment]
With help from @m-k-r I have now logged in to litpap.info and had a look at some of the relevant repositories. I cannot tell (perhaps @m-k-r can advise) which "navigator" clone is being used for the production instance that we see. I spotted two of them:

 - ```/srv/data/papyri.info/git/navigator```
 - ```/srv/data/papyri.info/git/navigator-new```

If either of these directories is the clone being used for the online presentation, then I think I have found the problem. ```git log``` reveals that both of them are current only to commit DCLP/navigator@074dc1985a2b669da17dc9ce9c4202e0154d8fc8, which is at least 18 commits behind master:HEAD at this moment. It is clear that ```git fetch``` has been done a few times, but those updates not merged into the local working copy. I can tell this because both of these clones report (on ```git status```) that they are "behind 'origin/master' by 7 commits" (which is to say, in git, behind the locally fetched copy of origin/master). 

Recommend that @m-k-r verify which of these directories is the one being used by the production code and do either a full ```git pull origin``` or a ```git fetch origin master``` followed by ```git merge origin/master``` after committing, stashing, or getting rid of any uncommitted local changes.  Then re-run the HTML transforms.

If a different clone is being used somewhere else on the server, please point me to it so I can inspect it.

**Comment by m-k-r** [comment]
The problem was that the html files were generated with the branch issue188. The last commit there is from 22.02. I hadn't thought of that earlier. Sorry for that. At our development server the metadata was correct. I copied these files and litpap should show now the [correct metadata](http://litpap.info/dclp/62103). 

Litpap is just our public server. Indexing and mapping is done on our dev-server and then copied.
On dev there is navigator-new and navigator-old which is the navigator of papyri.info. Navigator is a symlink so I can change between different repositories and working directories.

The navigator on litpap is outdated because it is only needed for updating the dispatcher and sync which wasn't necessary for a while now.

This will change if sync is working.

**Comment by paregorios** [comment]
Thanks for the clarification. Recommend we close this issue as resolved.

**Comment by jcowey** [comment]
Just looked at 
http://litpap.info/dclp/63294
works very well
Many thanks for the investigation and analysis @paregorios and for the extremely swift action by @m-k-r 

Magnificent!

**Comment by jcowey** [comment]
Hang on.
litpap.info/dclp/142503
only reads P.Bagnall
and not P.Bagnall 1
https://github.com/DCLP/idp.data/blob/master/DCLP/143/142503.xml#L236
seems to have the info.
Not quite sure what is wrong here

**Comment by paregorios** [comment]
@jcowey yes ... happily (if I can use that word) the presentation on litpap.info is exactly what one sees on dclpxsltbox: http://dclp.github.io/dclpxsltbox/output/dclp/143/142503.html

**Comment by jcowey** [comment]
Indeed, should have thought to check that. Further indication that the problem of display of the "Prinicpal Edition" in litpap.info is now solved.
Splendid!

**Comment by paregorios** [comment]
Closing as resolved, with much joy, but little overt fanfare.
