### ISSUE TITLE
word division hyphen is wrongly placed when <lb> has rend="inverse"

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#251]
split out from #152 because this is a separate issue:

See ll. 3-4
https://github.com/DCLP/idp.data/blob/master/DCLP/129/128952.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/129/128952.xml

Leiden+

```
(3, inverse) ἡμᾶς_mese-stigme_ ἀνατο̣
(4,- inverse) λὴ ἐξ ὕψους_mese-stigme_
```

XML

```xml
<lb n="3" rend="inverse"/> ἡμᾶς<g type="mese-stigme"/> ἀνατ<unclear>ο</unclear>
<lb n="4" rend="inverse" break="no"/> λὴ ἐξ ὕψους<g type="mese-stigme"/>
```

Displayed

```
ἡμᾶς ((mese-stigme)) ἀνατο̣
-λὴ ἐξ ὕψους ((mese-stigme)) 
```

Expected:

```
ἡμᾶς ((mese-stigme)) ἀνατο̣-
λὴ ἐξ ὕψους ((mese-stigme)) 
```

**Comment by wsalesky** [comment]
@paregorios in this case, the hyphen is actually in the XML data:
https://github.com/DCLP/idp.data/blob/master/DCLP/129/128952.xml#L167

I can add a hyphen before the line break for this condition, but I think we need some other use cases.

**Comment by paregorios** [comment]
@wsalesky the XML has been fixed by @jcowey . Please run the transform again and see if we get the  expected output; I think that we will and this will be resolved without XSLT changes.

**Comment by wsalesky** [comment]
This appears to be resolved with the new xml, no changes necessary to XSLT:

New HTML output:
```
ἡμᾶς ((mese-stigme)) ἀνατο̣-
λὴ ἐξ ὕψους ((mese-stigme)) 
```
Previous output:
```
ἡμᾶς ((mese-stigme)) ἀνατο̣
- λὴ ἐξ ὕψους ((mese-stigme)) 
```
I will mark this as resolved.
