### ISSUE TITLE
encoding monograms properly

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#252]
In the the LitPapText spreadsheet, a (perceived? anticipated?) problem with XSLT encodings of strings of monograms is discussed. In the examples, monograms are constructed like ```<g type="monogram">σχι</g>```, but I believe this may be tag abuse. Or hypothetical.

[The TEI Guidelines say](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/WD.html#D25-40): 

> The element g itself will usually be empty, but could contain a code point from the Private Use Area (PUA) of the Unicode Standard, which is an area set aside for the very purpose of privately adding new characters to a document.

The supposition, clear from context in the Guidelines, is that Unicode characters **constituting** the glyph should appear inside ```<g>```, not the gloss of the glyph, which seems to be what is envisioned here. 

Moreover, there are no examples of ```<g type="monogram">blah</g>``` anywhere in the DCLP or DDB data files. In fact, there are no monograms at all in DCLP at present. In DDB

**interrupted: will complete: no action yet**

**Comment by jcowey** [comment]
`<g type="monogram"/>` is used extensively in DDbDP. It is displayed as 
_monogr._

**Comment by rla2118** [comment]
I'm fine with DDbDP practice--<g type="monogram"/>

**Comment by paregorios** [comment]
So this is no action. Closing.
