### ISSUE TITLE
add Book and Line to Editor

### ISSUE THREAD

**Issue by rla2118** [DCLP/dclpxsltbox#253]
The categories 'Book' and 'Line' should be added to the drop-down menu in the Passage section of the Editor.  These can be displayed as 'Bk. and l.'

**Comment by Edelweiss** [comment]
xpath for principal publication biblScope[@unit='lines'], see…

https://github.com/DCLP/idp.data/blob/master/DCLP/110/109262.xml#L89
https://github.com/DCLP/idp.data/blob/master/DCLP/131/130206.xml#L86
https://github.com/DCLP/idp.data/blob/master/DCLP/28/27298.xml#L93
https://github.com/DCLP/idp.data/blob/master/DCLP/60/59818.xml#L96
https://github.com/DCLP/idp.data/blob/master/DCLP/66/65004.xml#L88
https://github.com/DCLP/idp.data/blob/master/DCLP/83/82579.xml#L87

**Comment by Edelweiss** [comment]
already there (biblScope[@unit='xyz'] where xyz can be any of the following):

- volume
- vol
- pp
- no
- col
- tome
- fasc
- issue
- plate
- numbers
- pages
- page
- side
- generic
- 

new:

- book
- line or lines ?!

**Comment by Edelweiss** [comment]
all, in alphabetical order

- book
- chapter
- col
- fasc
- fragment
- generic
- issue
- line
- lines
- no
- numbers
- page
- pages
- plate
- poem
- pp
- side
- tome
- vol
- volume

**Comment by Edelweiss** [comment]
[add Book and Line to Editor, ticket #253](https://github.com/DCLP/sosol/commit/6ed0038ef5f39f2a86ea76de98147b2db21ce647)

**Comment by paregorios** [comment]
I have looked at the editor and this is complete. Closing.
