### ISSUE TITLE
display printed illustration and custodial information together with text

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#26]
From @HolgerEssler in email:

> Printed Illustration and Custodial Events: at the moment both will be linked to images, and both are related to single fragments (not the papyrus as a whole). My favourite solution would be to display this information at the top of each part of the text to which they belong.

**Comment by paregorios** [comment]
Blocker for #51

**Comment by paregorios** [comment]
I'm taking this ticket to try to figure out why I marked it blocked on 17 July 2014 but there's no link to the blocker.

**Comment by leoba** [comment]
@paregorios for this (and #51) are these both open to be worked on?

**Comment by paregorios** [comment]
@leoba if you see a path forward, then yes.

**Comment by HolgerEssler** [comment]
We have now added corresp-nos to both the <custEvent> and the 
corresponding <div> in the text. (Some files still need updating, but in 
general that should be the way to relate them).

**Comment by jcowey** [comment]
I looked at 
https://github.com/DCLP/idp.data/blob/dclp/DCLP/63/62400.xml
which does not seem to have corresps in the text ```<div>```
@HolgerEssler can you please give us an example where the corresps have been added to the text ```<div>```

**Comment by HolgerEssler** [comment]
Examples are TM:
59436
59491
59506
62460

**Comment by jcowey** [comment]
Taking 
https://github.com/DCLP/idp.data/blob/dclp/DCLP/60/59436.xml
as a working examples
https://github.com/DCLP/idp.data/blob/dclp/DCLP/60/59436.xml#L633
refers to the following
https://github.com/DCLP/idp.data/blob/dclp/DCLP/60/59436.xml#L496
and
https://github.com/DCLP/idp.data/blob/dclp/DCLP/60/59436.xml#L481

by virtue of 
#FR2754

**Comment by HolgerEssler** [comment]
The intended layout and the places where the information from the custEvent-elements should be displayed are illustrated in our old google doc, page 3-5:
https://drive.google.com/open?id=1q8uAl6sNzop0JyRwIrbk4NgZ1zrTQtr20q7SEfycPRY

**Comment by paregorios** [comment]
@leoba this issue has been identified by the papyrology team members as being very high on the wish list. I wonder if we should collaborate on mocking up something for review, before trying to code it. What do you think?

**Comment by paregorios** [comment]
The desired output looks like this (pulled from Googledoc referenced by @HolgerEssler):

```
TM 62382 = LDAB 3547
Philodemus, De dis 1
DCLP/LDAB Data [xml] (For current LDAB info see link)
Fragments: PHerc. 26 col. 1-26
Provenance: Fundort: Herculaneum (Campania); Schreibort: Italy ?
Material: Papyrus
Date: I v.Chr.
Reference edition: H. Diels, Philodemus Über die Götter erstes Buch, 1916.
License  This work is licensed under a Creative Commons 

Transcription [xml]
	
Columne 1
Unrolled 1804 by Antonio Lentari                                                                                                                                                                                       Disegno 1804-1806 by Gennaro Casanova	
Disegno by G.B. Casanova, engraved by  Raffaele Biondi

1. [.8] δοξ̣ί[α]ν, ἃ δεῖ [.12]
2. εἰ μ[ηδὲ]ν χωρὶϲ α[ἰτ]ίων δ̣[ύναται] γε̣ίνε[ϲ]
3. -θαι καὶ τῶν αἰτίων [.7]ν[.2]ταργϲ 
4. μὴ παρακολουθεῖν καὶ δι[ότ]ι φίλο[ι δ]όξ̣α̣ν
5. -τεϲ ἔνιοι, μὴ δοκοῦντε[ϲ εἷν]αι, φ[αίνονται]                                                                                    	
6. τὰ τοῖϲ χυδαίοιϲ ὅμοια π[ράτ]τοντεϲ ὀ[ν]ε̣ί̣
7. -ρων [κ]αταφαινομέν[ων ϲυ]ϲτέλλουϲ[ιν,]
8. ἕνεκα δὲ τῶν ἔνδον οὐ[δὲ]ν διαφέρου[ϲιν]. 
9. καὶ φωρ[ῶ]νται δὲ καθ' ἕ̣[ω]λ̣ο̣ν̣ φιλοτ[ιμίαν]
10. τὰ παραπλήϲ̣ια δρῶντε[ϲ] ἅ̣ τ̣ι̣[νεϲ] τ[ῶ]ν ἀφ̣ι                                                                                  
11. -λήτων ἀν<δ>ρῶν, καὶ παν[τα]π̣αϲι[ν ἐαυτοὺϲ
12. καταμηνύουϲιν, ὅ<τ>ι δεδ̣[ιότ]ε̣ϲ ὑπὸ [τῆϲ] 
13. φρείκηϲ οὐδ' ἐ̣ν τῶι λοιπῶι χρόνω[ι τό γ' εὐ]
14. -δοκεῖν δύνανται π[ε]ρ̣ιπ[οε]ῖϲθαι [. πρῶτον] 
15. τοίνυν ἐπέρχ̣εταί μοι κ[ο]ιν[ῶ]ϲ δια[λεγομέ]                                                                                  	
16. -νῳ πρ[ὸϲ τὰ] ὕ[ϲ]τερα δόγματ̣[α τούτων] 
17. ἐπιϲημαίν[εϲ]θαι τὸ μηδὲ π̣[αραζεῦ]
18. -ξ̣αι γνηϲίωϲ αἷϲ ἔ[ϲ]χον ὑπ[ονοίαιϲ, εἴ] 
19. τιϲ μύϲαϲ αὐτοῖϲ διδώη τι πα[ρ]ὰ [τὴν τῶν ἀμέ]
20. -ϲων ἀ[κρί]βιαν ἀκολουθε[ῖν][.9]                                                                                                         	
21. [.2]ιν[.7]χθήϲετ̣[αι][.3] τημ.3 
22. ὑπε[.3]δ[.2 ἐ]γ δὲ τῶ[ν] ψε[υδ][.7]
23. [.1]κα[.3]α[.4]ον[.9] να[.1]ον
24. [.3]νκαι [.21]
 
 
 
Columne 2
Unrolled 1804 by Antonio Lentari                                                                                                                                                                                       Disegno 1804-1806 by Gennaro Casanova	
Disegno by G.B. Casanova, engraving by  Carlo Orazi

 
1. [.9]τωνενιϲφ[.10]                                                                                                                                              	
2. [.9]π̣εραινομ̣ένου[.6]
3. [.9]ν τὸ του[.1]παρ[.1]αϲ [.4] 
4. α̣[.1]το[.5]ντα δὲ [.2 ]πινμηνο[.2]α
5. λ[.8]α ταὐτὸν φυϲιολογία<ϲ> ἴδιον                                                                                                       	
6. κ̣αυτω[.4]τα [.3 ]ωπαιϲπανλ[.4]
7. γ[.8]ια δεικτέον ἀπ' ἀνθρώ[πων]
8. [τὴν προϲεμ]φέ̣ριαν ϲυν[ϲτά]ϲε[ι] τῶ̣ν 
9. θ̣[εῶν, ὥϲτε] φῆϲ[αι τ]ὸν θεὸν ζῶιον
10. [ἀίδιον καὶ ἄφθαρ]τον καὶ ϲυμπεπλη                                                                                                  	
11. [-ρῶϲθαι εὐ]δ̣αιμ[ονίαι· κ]αθοϲ[ο]ν ο[ὔ]τ[ε τ]οὺϲ
12. [ἀνθρωπείουϲ ἔχει πό]νουϲ [οὔτε τὰ] 
13. [περὶ τὸν θά]να[τ]ον κακά, μή τ[ί]
14. [γε τιμωρία]ϲ, ο̣<ὐ>δὲ̣ δεκτικόϲ γε πά[ν]
15. -τω[ν τῶν ἀλγε]ιν̣ῶ̣ν ἔϲται, δεκ[τι]κὸ[ϲ]                                                                                             	
16. [δ' ἀγαθῶν καὶ] ϲυ[μπε]πληρω[μένοϲ] 
17. ω[ραιότητι. ἔϲτι δὲ προ]λήψει π[εριλη]
18. -π[τὸϲ][.5] τι[.3] κακ[.10]  
19. ϲθ[.1]αικαϲικονταντ[.12]  
20. τα [.24]                                                                                                                                                               	
21. μ[.1]νη[.3]ϲα[.2]ηπ[.13] 
22. λ[.3]τ[.3]υδϲ[.3]ν[.11]
23. [.16]αγου[.6]
24. [.14]ιταατ[.2]ν̣ο[.3]
25. [.17]νι[.8]
 
 
Columne 3
Unrolled 1804 by Antonio Lentari                                                                                                                                                                                       Disegno 1804-1806 by Gennaro Casanova	
Disegno by G.B. Casanova, engraved by  Carlo Orazi
 
1. δειν[.22]                                                                                                                                                               
2. και[.2]το[.19]
3. ταιχε[.21]
4. πων ἄλλων ὅτι διν̣[.12]
5. ται τῶν οὐ[.18]                                                                                                                                                  
6. τὸ μὴ φανερὸν[.15]
7. θεὸν ὁ τῶν κ[.17]
8. περὶ τῶν ἐν [.14 ενυ]
9. -πνιων[.2]ν[.18]
10. φικοι[.22]
11. ερο[.1]ναιϲω[.18]
12. και[.2]ικα[.20]
13. νιϲτηϲδι[.19]
14. ρηνταϲα[.19]
15. .2 ινεν[.8]ϲιν[.7 νο
16. -μίζων[.7]ινεϲι[.9]
17. ναιπιατ[.8]γα[.9]
18. οζ[.24]
19. [.1]ελλε[.1]τενα[.16]
20. καικα[.1]εδ[.18]
```

**Comment by paregorios** [comment]
instead of what we have now; namely, all custodial events together at the top of the file.

**Comment by leoba** [comment]
Sorry, I somehow missed this when I was tagged on January 15. I will put hours to this tomorrow (2/20).

**Comment by leoba** [comment]
I have moved code from metadata.xsl to htm-teidivedition.xsl and added a bit more to display the custodial events at the top of each column. I've also commented out the code that was in metadata.xsl that displayed everything at the top of the file. This is messy - everything displays, so if there are a bunch of references for one column, they all display. It will also be obvious when codes are missing or aren't done correctly. Please let me know if this needs to be cleaned up more in the XSLT.

**Comment by HolgerEssler** [comment]
I suppose in order to see the results, we will have to wait for the next 
round of transform. Otherwise, I would be very grateful, if somebody 
could point me to the latest output files.

**Comment by paregorios** [comment]
I will undertake to post a new set of transform results as soon as
possible, but perhaps not before Tuesday 1 March.

-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by rla2118** [comment]
That would be helpful.  Thanks, Tom.

**Comment by HolgerEssler** [comment]
I finally got to have a look a the results which are great. May I ask 
for one addition and one change?

a) could the display of custEvents follow the following order of types: 
1) "unrolled" 2) "sketched" 3) "engraved" 4) "MSI" 5) "imaged"?

b) Previously we had links to the images underlying the entries which 
have now disappeared. I would prefer to add them after the relative 
entry (e.g. "Sketched by Carlo Orazi") in the form: ": Image on YXZ.YZ" 
where YXZ.YZ is the root element of the link stored in the url-Attribute 
of graphic. Outcomes would then be "Image on chartes.it", "Image on 
classics.ox.ac.uk" etc.

**Comment by HolgerEssler** [comment]
Taking up from
https://github.com/DCLP/dclpxsltbox/issues/51
I would also suggest that we add the content of the corresponding idno 
element at the top of the entries thus created, i.e. before the content 
of custEvent type="unrolled".
   Thus in the example
https://github.com/DCLP/idp.data/blob/dclp/DCLP/60/59436.xml
   for the first column ("#FR365") we would have:
"P.Herc. 1027 col. 1" from
https://github.com/DCLP/idp.data/blob/dclp/DCLP/60/59436.xml#L82
and then
"Unrolled 1805 by Camillo Paderni
Sketched by Gennaro Casanova
Sketched by Carlo Malesci
Sketched by Giovanni Battista Malesci
Sketched by Vincenzo Crispino
Engraved by Vincenzo Orsini
Engraved by Francesco Biondi"

**Comment by HolgerEssler** [comment]
At the moment the display of the information as created in February 2016 is not visible any more in the static html file on litpap.info (e.g. http://litpap.info/dclp/62400)?
@m-k-r, is this a server problem?

**Comment by Edelweiss** [comment]
The missing revision is:


>r2389 | leoba | 2016-02-28 23:14:49 +0100 (So, 28. Feb 2016) | 1 Zeile
>Geänderte Pfade:
>   M /branches/dclp/example-p5-xslt/htm-teidivedition.xsl
>
>Moved code from metadata.xsl to htm-teidivedition.xsl to display custodial history at top of each column

(```svn://svn.code.sf.net/p/epidoc/code/branches/dcl```, ```svn log -v -r {2016-02-19}:{2016-03-01}```)

**Comment by Edelweiss** [comment]
Make sure that the EpiDoc sources in the following folders comprise the revision mentioned above

EpiDoc for indexer

- /srv/data/papyri.info/git/navigator/epidoc-xslt
- /srv/data/papyri.info/git/navigator/epidoc-xslt-dclp/papyri

EpiDoc for SoSOL editor

- /srv/data/papyri.info/sosol/shared/externals/data/xslt/epidoc/1755
- /srv/data/papyri.info/sosol/shared/externals/data/xslt/epidoc/dclp
- /srv/data/papyri.info/sosol/editor/data/xslt/epidoc (only a symlink to one the two folders above)

**Comment by paregorios** [comment]
@Edelweiss I don't think there's anything for me to do here, so I'm un-assigning myself. Let me know if you need me to do something.

**Comment by paregorios** [comment]
As far as I can see, this issue is resolved as far as required XSLT changes. I therefore am removing the "blocker" label, which marked this issue as a prerequisite for #51. 

I am also removing the "tweak XSLT" label and adding a "task" label.

@jcowey and @Edelweiss please review this ticket to determine what the appropriate priority label is (it is currently marked "urgent").

**Comment by Edelweiss** [comment]
[Commits](https://sourceforge.net/p/epidoc/code/2573/log/?path=/branches/dclp) in [dclp](https://sourceforge.net/p/epidoc/code/HEAD/tree/branches/dclp/) branch

missing commit r2389 by leoba on 2016-02-28:

[Moved code from metadata.xsl to htm-teidivedition.xsl to display custodial history at top of each column](https://sourceforge.net/p/epidoc/code/2389/)

**Comment by Edelweiss** [comment]
Is that what’s supposed to be missing?

![bildschirmfoto 2017-04-19 um 15 53 05](https://cloud.githubusercontent.com/assets/612862/25183634/7034b764-2518-11e7-9332-e28739d5fef5.png)

→ [59436](http://litpap.info/dclp/59436)

**Comment by paregorios** [comment]
That's my impression. @HolgerEssler how does this look to you now?

**Comment by HolgerEssler** [comment]
Excellent. I am closing this issue.
