### ISSUE TITLE
Display Fragment idnos together with text

### ISSUE THREAD

**Issue by HolgerEssler** [DCLP/dclpxsltbox#260]
This issue is in some way analogous to #26. There we display together the text fragment and information form custEvent by virtue of the corresp-attribute. To take James' example:
In
https://github.com/DCLP/idp.data/blob/development/DCLP/60/59436.xml
as a working example
https://github.com/DCLP/idp.data/blob/development/DCLP/60/59436.xml#L740
refers to the following
https://github.com/DCLP/idp.data/blob/development/DCLP/60/59436.xml#L596
and
https://github.com/DCLP/idp.data/blob/development/DCLP/60/59436.xml#L580
and
https://github.com/DCLP/idp.data/blob/development/DCLP/60/59436.xml#L442
by virtue of
corresp="#FR2754"

In the same way I would like to display the content of 
//sourceDesc/msDesc/msIdentifier/idno/@type="invNo"
before the block of custodial information from #26.
Again the text fragments are related in virtue of the corresp. Taking the example from above:
In
https://github.com/DCLP/idp.data/blob/development/DCLP/60/59436.xml
as a working example
https://github.com/DCLP/idp.data/blob/development/DCLP/60/59436.xml#L740
because the div has /@corresp="#FR2754"
refers to 
https://github.com/DCLP/idp.data/blob/development/DCLP/60/59436.xml#L90
because the idno has xml:id="FR2754".
Thus the xml:id of the corresponding idno equals the  //div/@corresp minus the initial hastag.

**Comment by paregorios** [comment]
This seems sensible and "do-able" to me. What priority shall we assign to this work @rla2118 @HolgerEssler @jcowey @rogerbagnall ?

**Comment by wsalesky** [comment]
@HolgerEssler I can take over this ticket, can you give me an example of the desired output, using: 
https://github.com/DCLP/idp.data/blob/development/DCLP/60/59436.xml#L740

Thanks.

**Comment by HolgerEssler** [comment]
@wsalesky great.
current output is:

column 6
Sketched by Giovanni Battista Malesci
Engraved by Vincenzo Orsini

desired output (with addition in bold for ease of reference):

column 6
**P.Herc. 1027 col. 6**
Sketched by Giovanni Battista Malesci
Engraved by Vincenzo Orsini

Does that help?

**Comment by wsalesky** [comment]
@HolgerEssler thanks that is what I needed!

**Comment by wsalesky** [comment]
**XSLT Changed:**  `epidoc-xslt/htm-teidivedition.xsl`
**Branch:** ` ../branches/dclp-issue260/example-p5-xslt`
Added corresponding tei:idno:
```
<xsl:for-each select="//t:idno[@xml:id = (tokenize(replace($corresp,'#',''),' '))]">
         <span class="corresp idno"><xsl:value-of select="."/></span><br/>
      </xsl:for-each>
```
Adjusted logic for custEvent to handle multiple values in the corresp attribute. 
(Example: https://github.com/DCLP/idp.data/blob/development/DCLP/60/59502.xml#L1126 )

**Sample diff:**
```
diff --git a/output/dclp/60/59112.html b/output/dclp/60/59112.html
index 76aefb2b1..7d78c52dc 100644
--- a/output/dclp/60/59112.html
+++ b/output/dclp/60/59112.html
@@ -179,51 +179,51 @@

-                           </div>  <span class="textpartnumber" id="textpart-textpart-textpart-ab2-4-5-6">column 6</span><span class="custevent" id="ce2-4-5-6"><a href="http://clp.classics.ox.ac.uk/gsdl/collect/PHerc/index/assoc/HASH0193/4f312e94.dir/herc.v001.0155.a.01.hires.jpg" title="scan of sketch of column 6">Sketched</a> 1802-1802 by Giuseppe Casanova</span><br><br><div class="textpart"><a id="a2-4-5-6-l1">
+                           </div>  <span class="textpartnumber" id="textpart-textpart-textpart-ab2-4-5-6">column 6</span><span class="corresp idno">P.Herc. 176 col. 6</span><br><span class="custevent" id="ce2-4-5-6"><a href="http://clp.classics.ox.ac.uk/gsdl/collect/PHerc/index/assoc/HASH0193/4f312e94.dir/herc.v001.0155.a.01.hires.jpg" title="scan of sketch of column 6">Sketched</a> 1802-1802 by Giuseppe Casanova</span><br><br><div class="textpart"><a id="a2-4-5-6-l1">
                                  <!--0--></a>[- ca.12 -]γ̣ατηι<br id="a2-4-5-6-l2">[- ca.13 -]οιου<br id="a2-4-5-6-l3">[- ca.13 -]σελυ-<br id="a2-4-5-6-l4">[- ca.12 -]παρ' αὐ-<br id="a2-4-5-6-l5"><span class="linenumber">5</span>[τ- ca.15 -δ]<br id="a2-4-5-6-l6">[&nbsp;&nbsp;̣&nbsp;&nbsp;̣&nbsp;&nbsp;̣&nbsp;&nbsp;̣&nbsp;&nbsp;̣] δηλοῦν τοῖς δι-<br id="a2-4-5-6-l7">[&nbsp;&nbsp;̣&nbsp;&nbsp;̣&nbsp;&nbsp;̣&nbsp;&nbsp;̣&nbsp;&nbsp;̣&nbsp;&nbsp;̣&nbsp;&nbsp;̣] χ̣ο̣ρηγεῖν ε-<br id="a2-4-5-6-l8">δ[ε]όμεθα ομη[&nbsp;&nbsp;̣]εις ὀργῆι<br id="a2-4-5-6-l9">παραπλήσιον καθισας<br id="a2-4-5-6-l10"><span class="linenumber">10</span>[&nbsp;&nbsp;̣]αι πεφυκα̣μ[εν&nbsp;&nbsp;̣&nbsp;&nbsp;̣ -ca.?- ]<br id="a2-4-5-6-l11">[ὅ]ταν ο[&nbsp;&nbsp;̣]ν[- ca.11 -]<br id="a2-4-5-6-l12">σκ[&nbsp;&nbsp;̣]α[- ca.14 -]<br id="a2-4-5-6-l13">[10 lines missing]<br id="a2-4-5-6-l23"><span class="linenumber">23</span>[&nbsp;&nbsp;̣&nbsp;&nbsp;̣&nbsp;&nbsp;̣]θ[- ca.15 -]<br id="a2-4-5-6-l24">[- ca.14 -]ε τωι<br id="a2-4-5-6-l25"><span class="linenumber">25</span>μη γιν[- ca.9 -]ρατ' ὀ-<br id="a2-4-5-6-l26">κνου[- ca.14 -]-<br id="a2-4-5-6-l27">λον επι̣[&nbsp;&nbsp;̣&nbsp;&nbsp;̣&nbsp;&nbsp;̣&nbsp;&nbsp;̣]εον[&nbsp;&nbsp;̣&nbsp;&nbsp;̣&nbsp;&nbsp;̣]ου<br id="a2-4-5-6-l28">π̣λ̣ου[&nbsp;&nbsp;̣&nbsp;&nbsp;̣&nbsp;&nbsp;̣&nbsp;&nbsp;̣&nbsp;&nbsp;̣&nbsp;&nbsp;̣]ν̣επ[&nbsp;&nbsp;̣&nbsp;&nbsp;̣]οδ[&nbsp;&nbsp;̣]ν<br id="a2-4-5-6-l29">αυ[&nbsp;&nbsp;̣&nbsp;&nbsp;̣]εχ[&nbsp;&nbsp;̣&nbsp;&nbsp;̣&nbsp;&nbsp;̣&nbsp;&nbsp;̣&nbsp;&nbsp;̣&nbsp;&nbsp;̣]τυπ[- ca.6 -]<br id="a2-4-5-6-l30"><span class="linenumber">30</span>δειασ[- ca.15 -]<br id="a2-4-5-6-l31">κον[&nbsp;&nbsp;̣&nbsp;&nbsp;̣&nbsp;&nbsp;̣&nbsp;&nbsp;̣&nbsp;&nbsp;̣]ν αυτ[- ca.8 -] 
-                           </div>  <span class="textpartnumber" id="textpart-textpart-textpart-ab2-4-5-7">column 7</span><span class="custevent" id="ce2-4-5-7"><a href="http://clp.classics.ox.ac.uk/gsdl/collect/PHerc/index/assoc/HASH0195/4f332ea4.dir/herc.v001.0156.a.01.hires.jpg" title="scan of sketch of column 7">Sketched</a> 1802-1802 by Giuseppe Casanova</span><br><br><div class="textpart"><a id="a2-4-5-7-l1">
+                           </div>  <span class="textpartnumber" id="textpart-textpart-textpart-ab2-4-5-7">column 7</span><span class="corresp idno">P.Herc. 176 col. 7</span><br><span class="custevent" id="ce2-4-5-7"><a href="http://clp.classics.ox.ac.uk/gsdl/collect/PHerc/index/assoc/HASH0195/4f332ea4.dir/herc.v001.0156.a.01.hires.jpg" title="scan of sketch of column 7">Sketched</a> 1802-1802 by Giuseppe Casanova</span><br><br><div class="textpart"><a id="a2-4-5-7-l1">
 
```

**Comment by paregorios** [comment]
Code is working and has been merged to https://github.com/DCLP/epidoc-xslt master.
