### ISSUE TITLE
XML for TM59946 has malformed MP3 idno

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#261]
In [TM 59946](https://github.com/DCLP/idp.data/blob/master/DCLP/60/59946.xml) we find:

```xml
<idno type="MP3">MP3 1575</idno>
```

but all other appearances of the MP3 idno look like this:

 - [TM 139884](https://github.com/DCLP/idp.data/blob/master/DCLP/140/139884.xml):  - ```<idno type="MP3">0343.01</idno>```
 - [TM 140284](https://github.com/DCLP/idp.data/blob/master/DCLP/141/140284.xml):  - ```<idno type="MP3">1407.31</idno>```
 - [TM 142503](https://github.com/DCLP/idp.data/blob/master/DCLP/143/142503.xml):  - ```<idno type="MP3">2353.81</idno>```
 - [TM 171880](https://github.com/DCLP/idp.data/blob/master/DCLP/172/171880.xml):  - ```<idno type="MP3">1258.002</idno>```
 - [TM 171882](https://github.com/DCLP/idp.data/blob/master/DCLP/172/171882.xml):  - ```<idno type="MP3">1258.011</idno>```
 - [TM 175280](https://github.com/DCLP/idp.data/blob/master/DCLP/176/175280.xml):  - ```<idno type="MP3">2147.24</idno>```
 - [TM 62334](https://github.com/DCLP/idp.data/blob/master/DCLP/63/62334.xml): ``` - <idno type="MP3">1331</idno>```
 - [TM 63633](https://github.com/DCLP/idp.data/blob/master/DCLP/64/63633.xml): ``` - <idno type="MP3">01897.200</idno>```
 - [TM 65740](https://github.com/DCLP/idp.data/blob/master/DCLP/66/65740.xml): ``` - <idno type="MP3">2348</idno>```

**Comment by paregorios** [comment]
Assigning to papyrologists to prioritize and so they can decide who should fix this data entry.

**Comment by jcowey** [comment]
```xml
<idno type="MP3">MP3 1575</idno>
```
is now

```xml
<idno type="MP3">1575</idno>
```

as we would expect 
https://github.com/DCLP/idp.data/blob/master/DCLP/60/59946.xml#L23

So everything should now be fine, @paregorios

**Comment by paregorios** [comment]
Looks good, thanks! Changes deployed to test HTML.
