### ISSUE TITLE
Editorial History is messing up the layout of the html-files

### ISSUE THREAD

**Issue by m-k-r** [DCLP/dclpxsltbox#263]
A few days ago I changed the MakeHTML.xls to get Editorial History for dclp but the output is messed up.

Without Editorial History it looks like this: [http://litpap.info/dclp/59137](http://litpap.info/dclp/59137) (Transcription und Apparatus are new)
With Editorial History it looks like this:
![dclp-59137](https://cloud.githubusercontent.com/assets/24894427/26034488/8ea3d0dc-38bd-11e7-9258-fed0afa35d9b.jpg)
It should look like this: [http://litpap.info/ddbdp/bgu;1;2](http://litpap.info/ddbdp/bgu;1;2)

The changes in MakeHTML can be seen here:
[https://github.com/DCLP/navigator/commit/5d2588593042c115908f722e5e380d833be23986](https://github.com/DCLP/navigator/commit/5d2588593042c115908f722e5e380d833be23986)

For now Editorial History is deactived until the problem can be solved.

**Comment by paregorios** [comment]
@rla2118 @HolgerEssler @jcowey @rogerbagnall what are you expecting to see for editorial history?

**Comment by m-k-r** [comment]
I did a bit further investigation and it seems this error occurs not only with dclp editorial history but with every editorial history when dclp is involved. For example [http://litpap.info/ddbdp/sb;22;15203](http://litpap.info/ddbdp/sb;22;15203). 649 ddbdp-files files contain "Provisional papyri.info output"

The changes responsible for this have to be in the last 2 month.

**Comment by paregorios** [comment]
Ah, so this is a pre-existing papyri.info feature that is not working right with DCLP content?

**Comment by m-k-r** [comment]
It seems that way. This commit [https://github.com/DCLP/navigator/commit/bf1c2a81907fb1a2c074c68a2bc3c751871d0510](https://github.com/DCLP/navigator/commit/bf1c2a81907fb1a2c074c68a2bc3c751871d0510) looks like a good starting point. As far as I remember the error wasn't there yet and has to be introduced later.

**Comment by paregorios** [comment]
thanks @m-k-r I will ask @wsalesky @leoba or @sarcanon to have a look

**Comment by jcowey** [comment]
Using this as an example:
http://papyri.info/ddbdp/sb;28;17209

This is what we would like to see:
![bildschirmfoto 2017-05-17 um 16 04 02](https://cloud.githubusercontent.com/assets/612992/26157830/7f41272a-3b1a-11e7-8dbd-4d91d58d4682.png)

which is displaying the contents of 
https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/sb/sb.28/sb.28.17209.xml#L32-L37

**Comment by jcowey** [comment]
For http://litpap.info/dclp/59137

I would hope to see the contents of 

https://github.com/DCLP/idp.data/blob/master/DCLP/60/59137.xml#L106-L123

**Comment by wsalesky** [comment]
**XSLT Changes:**  pn-xslt/MakeHTML.xsl
Add template to include `t:revisionDesc`

**Example diff:**

```
diff --git a/output/dclp/100/99554.html b/output/dclp/100/99554.html
index 67cce891c..d49ee2b2e 100644
--- a/output/dclp/100/99554.html
+++ b/output/dclp/100/99554.html
@@ -110,6 +110,23 @@
                         <div id="edition"></div>
                      </div>
                   </div>
+                  <div id="history" class="text">
+                     <div id="history-headers">
+                        <h3><span id="edit-history">Editorial History</span>; 
+                           <span id="all-history">All History</span>; 
+                           (<a href="https://github.com/DCLP/idp.data/blame/master/DCLP/100/99554.xml" target="_blank">detailed</a>)
+                        </h3>
+                     </div>
+                     <div id="history-lists">
+                        <ul id="edit-history-list" style="display:none;">
+                           <li>No editorial history recorded.</li>
+                        </ul>
+                        <ul id="all-history-list" style="display:none">
+                           <li>2014-12-10 [<a href="DCLP">DCLP</a>]: Crosswalked to EpiDoc XML
+                           </li>
+                        </ul>
+                     </div>
+                  </div>
```
**Question** 
I used the logic from history display used by the other data repositories, however I'm not sure "All History" behaves as expected, perhaps due to a difference in data encoding? 

Current logic: 
Editorial History is designated by the a 'T' in the change date: `t:change[contains(@when, 'T')]` 
All History is designated by date encoding: ` t:change[matches(@when, '^\d{4}-\d{2}-\d{2}$')]`

So "All History" does not display all the change elements, as I would expect. Should I change the logic, or are you happy with the current functionality.
