### ISSUE TITLE
Header Display

### ISSUE THREAD

**Issue by jcowey** [DCLP/dclpxsltbox#265]
Separate issue for each section of the vexed question of Header/Title/Work/Content/PrincipalEdition.
This is presented in the Googlespreadsheet:
https://docs.google.com/spreadsheets/d/17CsmPyiV9zL_bn7mqYHop5cutLtreHXVZp8ZuNwRvro/edit#gid=1324973521

By Header we mean the centred statement of Trismegistos and LDAB  numbers e.g.: 
**Trismegistos 92863 = LDAB 92863**
http://dclp.github.io/dclpxsltbox/output/dclp/93/92863.html

This functions and should remain. There are a couple of tweaks to be added.

**Comment by jcowey** [comment]
This attempts to separate out into individual issues some of the stuff that we grappled with in #206.

**Comment by jcowey** [comment]
Tweak one!
When the content titleStmt/title **start with** ''P\.\s*Herc\.'' then display the whole content of title in the first position of the Header.

**Comment by wsalesky** [comment]
**Edited:** pn-xslt/MakeHTML.xsl

**XSLT:** added to `xsl:template name="get-references"`
```
<xsl:if test="/t:TEI/t:teiHeader/t:fileDesc/t:titleStmt/t:title[matches(., '^P\.\s*Herc\.')]">
      <xsl:value-of select="/t:TEI/t:teiHeader/t:fileDesc/t:titleStmt/t:title[matches(., '^P\.\s*Herc\.')]"/>
      <xsl:text> = </xsl:text>
    </xsl:if>
```
**Sample diff:**
```
diff --git a/output/dclp/106/105748.html b/output/dclp/106/105748.html
index e912d4b8b..b51b1af62 100644
--- a/output/dclp/106/105748.html
+++ b/output/dclp/106/105748.html
@@ -24,7 +24,7 @@
             <xi:include xmlns:xi="http://www.w3.org/2001/XInclude" href="nav.xml"></xi:include>
             <div id="main">
                <div class="content ui-corner-all">
-                  <h3 style="text-align:center">Trismegistos <a href="http://www.trismegistos.org/text/105748">105748</a>
+                  <h3 style="text-align:center">P.Herc. Stub = Trismegistos <a href="http://www.trismegistos.org/text/105748">105748</a>
                        = <a href="http://www.trismegistos.org/ldab/text.php?quick=105748">LDAB 105748</a></h3>
                   <h4 style="text-align:center" id="titledate"></h4>
                   <div id="controls" class="ui-widget">
diff --git a/output/dclp/106/105749.html b/output/dclp/106/105749.html
index 98627e010..f3eb6630c 100644
--- a/output/dclp/106/105749.html
+++ b/output/dclp/106/105749.html
@@ -24,7 +24,7 @@
             <xi:include xmlns:xi="http://www.w3.org/2001/XInclude" href="nav.xml"></xi:include>
             <div id="main">
                <div class="content ui-corner-all">
-                  <h3 style="text-align:center">Trismegistos <a href="http://www.trismegistos.org/text/105749">105749</a>
+                  <h3 style="text-align:center">P.Herc. Stub = Trismegistos <a href="http://www.trismegistos.org/text/105749">105749</a>
                        = <a href="http://www.trismegistos.org/ldab/text.php?quick=105749">LDAB 105749</a></h3>
                   <h4 style="text-align:center" id="titledate"></h4>
                   <div id="controls" class="ui-widget">

```

**Comment by jcowey** [comment]
That looks good to me. P.Herc. Stub was indeed meant as a place holder. It looks a bit strange but is I am pretty sure what is wanted. Great. I am taking off the review label

**Comment by paregorios** [comment]
I'm putting the "review" label back on (no offence intended) and reassigning to myself for merge.

**Comment by jcowey** [comment]
OK no problem, great and thanks.

**Comment by jcowey** [comment]
Tweak two. And just as well we still have the review label (it is getting late here).
In the case of 
litpap.info/dclp/128923
https://github.com/DCLP/idp.data/blob/master/DCLP/13/128923.xml
Where there is a principal edition of the type
P.Oxy. 75 5021
We would like to see  	P.Oxy. 75 5021 = Trismegistos 128923 = LDAB 128923
in the header
The trigger in this case should be:
if you find a dclp-hybrid in a DCLP file e.g. in this case
https://github.com/DCLP/idp.data/blob/master/DCLP/129/128923.xml#L15
then display the principal edition display in the header in first position.
Let me know if this is unclear or you need to look for a different way to do this @wsalesky

**Comment by paregorios** [comment]
@jcowey I need some clarification with regard to [your second tweak](https://github.com/DCLP/dclpxsltbox/issues/265#issuecomment-302498411), above. There are XML files in which one finds ```<idno type="dclp-hybrid">``` for which the principal edition is not of the form ```P.Blah 1 2```. For example, TM 61352 has ```<idno type="dclp-hybrid">na;;61352</idno>``` and a ZPE principal edition.

Which of the following do you want:

 - Output principal edition for any and all XML files that contain ```<idno type="dclp-hybrid">```
 - Output principal edition only for XML files that contain ```<idno type="dclp-hybrid">``` whose text content looks like "p.oxy;75;5021" (but what about ostraka etc.?)
 - something else?

Thanks.

**Comment by jcowey** [comment]
Just collecting some examples here, before commenting and trying to sort out.
http://dclp.github.io/dclpxsltbox/output/dclp/64/63868.html

**Comment by paregorios** [comment]
Per convo with @jcowey:

output principal edition info at beginning of heading line if ```<idno type="dclp-hybrid"``` exists and its content does not begin with ```"na;"```.
