### ISSUE TITLE
Title Display

### ISSUE THREAD

**Issue by jcowey** [DCLP/dclpxsltbox#266]
Separate issue for each section of the vexed question of Header/Title/Work/Content/PrincipalEdition.
This is presented in the Googlespreadsheet:
https://docs.google.com/spreadsheets/d/17CsmPyiV9zL_bn7mqYHop5cutLtreHXVZp8ZuNwRvro/edit#gid=1324973521

Up until now we have **NOT** displayed Title.
So far we have displayed 
Header
Work* (* = when it is available, otherwise not)
Content* (* = when it is available, otherwise not)
Principal Edition* (* = when it is available, otherwise not)

From now on with new XSLT we will display
Header
Title
Work* (* = when it is available, otherwise not)
Content* (* = when it is available, otherwise not)
Principal Edition* (* = when it is available, otherwise not)

The new XSLT will use the word 'Title' in bold (just like the bold Work/Content/PrincipalEdition etc)
it will display the content of title (teiHeader/fileDesc/titleStmt/title)

An example:
http://dclp.github.io/dclpxsltbox/output/dclp/93/92863.html
will display
https://github.com/DCLP/idp.data/blob/master/DCLP/93/92863.xml#L6-L8

`Title    Suppl. Mag. 1 42`

so the full display will be 
`Title    Suppl. Mag. 1 42`
`Content 	love spell (lesbian) with assistance of a demon, partly in iambic trimeter and choliambics`
`Principal Edition 	Suppl.Mag. 1 42`

We have agreed to live with the fact that Title and Principal Edition are the same in this case.

There will always be a Title for every file. Every valid file must have a titleStmt/title. So every file will have a Title.

**Comment by jcowey** [comment]
This attempts to separate out into individual issues some of the stuff that we grappled with in #206.

**Comment by wsalesky** [comment]
**XSLT edited:** `pn-xslt/metadata-dclp`
Added new template for title/@mode='metadata'

**Git diff:** 
```

diff --git a/output/dclp/1/555.html b/output/dclp/1/555.html
index 5fe35e94d..668f7ee85 100644
--- a/output/dclp/1/555.html
+++ b/output/dclp/1/555.html
@@ -42,6 +42,12 @@
                            </h2>
                            <table class="metadata">
                               <tbody>
+                                 
+                                 <tr>
+                                    <th class="rowheader" rowspan="1">Title</th>
+                                    <td class="mdtitle">P. Cairo. 2 30962</td>
+                                 </tr>
+                                 
                                  <tr>
                                     <th class="rowheader" rowspan="1">Content</th>
                                     <td>hymns to Sobek-Re and Hathor</td>
diff --git a/output/dclp/100/99287.html b/output/dclp/100/99287.html
index b9273a40d..1f21ee205 100644
--- a/output/dclp/100/99287.html
+++ b/output/dclp/100/99287.html
@@ -42,6 +42,12 @@
                            </h2>
                            <table class="metadata">
                               <tbody>
+                                 
+                                 <tr>
+                                    <th class="rowheader" rowspan="1">Title</th>
+                                    <td class="mdtitle">TM 99287</td>
+                                 </tr>
+                                 
                                  <tr>
                                     <th class="rowheader" rowspan="1">Content</th>
                                     <td>school text</td>

```

**Comment by jcowey** [comment]
Also looking good. Many thanks.
