### ISSUE TITLE
Work Display

### ISSUE THREAD

**Issue by jcowey** [DCLP/dclpxsltbox#267]
Separate issue for each section of the vexed question of Header/Title/Work/Content/PrincipalEdition.
This is presented in the Googlespreadsheet:
https://docs.google.com/spreadsheets/d/17CsmPyiV9zL_bn7mqYHop5cutLtreHXVZp8ZuNwRvro/edit#gid=1324973521

This seems to be performing perfectly. 
http://dclp.github.io/dclpxsltbox/output/dclp/60/59749.html

Taking info from `<div type="bibliography" subtype="ancientEdition">`
https://github.com/DCLP/idp.data/blob/master/DCLP/60/59749.xml#L2392-L2404
it displays
author
https://github.com/DCLP/idp.data/blob/master/DCLP/60/59749.xml#L2397
title
https://github.com/DCLP/idp.data/blob/master/DCLP/60/59749.xml#L2398-L2400
biblScope
https://github.com/DCLP/idp.data/blob/master/DCLP/60/59749.xml#L2401

When there is no work, then nothing is displayed. This is as we want it.

**Comment by jcowey** [comment]
Possibly slightly unnecessary, but I think helpful as a reference.

**Comment by paregorios** [comment]
Another ticket-for-reference. Production code is working correctly. Closing.
