### ISSUE TITLE
Content Display

### ISSUE THREAD

**Issue by jcowey** [DCLP/dclpxsltbox#268]
Separate issue for each section of the vexed question of Header/Title/Work/Content/PrincipalEdition.
This is presented in the Googlespreadsheet:
https://docs.google.com/spreadsheets/d/17CsmPyiV9zL_bn7mqYHop5cutLtreHXVZp8ZuNwRvro/edit#gid=1324973521

This seems to be performing perfectly.
http://dclp.github.io/dclpxsltbox/output/dclp/59/58911.html

Taking info from `keywords/<term type="overview">`
https://github.com/DCLP/idp.data/blob/master/DCLP/59/58911.xml#L105
it displays
Achilles Tatius; Leucippe et Clitophon, 02.2.3-5, 14.5-7

We live with the fact that in this case there is a certain overlap with Work.

When there is no `keywords/<term type="overview">`, then nothing is displayed. This is as we want it.

**Comment by jcowey** [comment]
Possibly slightly unnecessary, but I think helpful as a reference.

**Comment by paregorios** [comment]
Right. This ticket is for reference, and production code is working as designed. Closing.
