### ISSUE TITLE
Principal Edition Display

### ISSUE THREAD

**Issue by jcowey** [DCLP/dclpxsltbox#269]
Separate issue for each section of the vexed question of Header/Title/Work/Content/PrincipalEdition.
This is presented in the Googlespreadsheet:
https://docs.google.com/spreadsheets/d/17CsmPyiV9zL_bn7mqYHop5cutLtreHXVZp8ZuNwRvro/edit#gid=1324973521

I think there are still some problems here.
Taking info from `<div type="bibliography" subtype="principalEdition">`
It has to take info from the biblio record
https://github.com/papyri/idp.data/blob/master/Biblio/81/80609.xml#L2
which I suppose it get from 
https://github.com/DCLP/idp.data/blob/master/DCLP/144/143318.xml#L137
and then combine this with info from the file itself
https://github.com/DCLP/idp.data/blob/master/DCLP/144/143318.xml#L126-L142

It is the second part that does not seem to perform properly in the example above.

**Comment by jcowey** [comment]
This is related to #242 and #212.

**Comment by wsalesky** [comment]
@jcowey Can you clarify what needs to happen here? An example file with current behavior and expected behavior would be  helpful. 

Also, does #212 resolve any of the issues here?

**Comment by jcowey** [comment]
OK
http://litpap.info/dclp/143318
displays 
`Principal Edition 	Den syngende korporal. [Le caporal chantant.]`
which it presumably gets from 
https://github.com/papyri/idp.data/blob/master/Biblio/81/80609.xml#L2
cf. also for the same behaviour
http://dclp.github.io/dclpxsltbox/output/dclp/144/143318.html


What I would like to see displayed in 
`Principal Edition 	Den syngende korporal. [Le caporal chantant.], 1-9`
which one would get from 
https://github.com/DCLP/idp.data/blob/master/DCLP/144/143318.xml#L138

It is the display of the content of the biblScope element in the file itself that is what is important
The title one get from the biblio file
but the added information, which is essential, one get from the XML of the file itself

Does that help?

**Comment by wsalesky** [comment]
Yes, that does make sense. This is handled by the changes made in https://github.com/DCLP/dclpxsltbox/issues/212

**Comment by paregorios** [comment]
It looks to me as if #212 in its current state addresses all of this, but I will try to make sure during review.
