### ISSUE TITLE
Biblio id still not saving

### ISSUE THREAD

**Issue by rla2118** [DCLP/dclpxsltbox#271]
This issue concerns http://litpap.info/editor/publications/534/dclp_meta_identifiers/1092/edit

If one enters the biblio id (95251), the system recognizes the number and it previews the bibl. correctly.  Still, the file will not save. Instead, the system generates this error message:

Error updating file: element "profileDesc" not allowed here; expected the element end-tag. This file was NOT SAVED.

**Comment by Edelweiss** [comment]
TM No. 219238

**Comment by Edelweiss** [comment]
reason for this malfunction is that profileDesc is appended after revisionDesc

it must come after fileDesc and before revisionDesc

```
element teiHeader
{
   att.global.attributes,
   att.global.rendition.attributes,
   att.global.linking.attributes,
   att.global.analytic.attributes,
   att.global.facs.attributes,
   att.global.change.attributes,
   att.global.responsibility.attributes,
   att.global.source.attributes,
   ( fileDesc, model.teiHeaderPart*, revisionDesc? )
}
```

(profileDesc being part of teiHeaderPart)

**Comment by Edelweiss** [comment]
children of DCLP’s teiHeader

- fileDesc
- encodingDesc
- profileDesc
- revisionDesc

**Comment by Edelweiss** [comment]
https://github.com/DCLP/sosol/commit/11456d0723e7849767c8214305a1c9e0c75e43f4

**Comment by jcowey** [comment]
This now seems fine. I am closing.
