### ISSUE TITLE
Not all Principal Editions displaying

### ISSUE THREAD

**Issue by rla2118** [DCLP/dclpxsltbox#279]
This issue concerns

http://litpap.info/dclp/61352

The following principalEdition entry is not appearing in the HTML.  The other bibl's with this subtype are, however.

```
<div type="bibliography" subtype="principalEdition">
            <listBibl>
               <bibl n="1" type="publication" subtype="principal">
            <!-- ignore - start, i.e. SoSOL users may not edit this -->
                  <title level="j" type="short-BP">ZPE</title>
                  <author n="1">
                     <surname>Gronewald</surname>
                     <forename>Michael</forename>
                  </author>
                  <date>1976</date>
                  <!-- ignore - stop -->
                  <ptr target="http://papyri.info/biblio/51367"/>
</bibl>
```

**Comment by jcowey** [comment]
This is category of bibliography for which, I think, we do not have the relevant XSLT.

**Comment by wsalesky** [comment]
@rla2118 @jcowey @paregorios 
I wonder if the online version is lagging behind the codebase? When I run the XSLT locally on the master branch of the data I get the following output for Principal Editions:

**Principal Edition**	P. Berol. 10747 Ostrakon = Isokrates, An Demonikos pt. 28.
**Principal Edition**	Corpus dei Papiri filosofici greci e latini (CPF). Testi e lessico nei papiri di cultura greca e latina. Parte I.2* - 2**: Cultura e Filosofia (Galenus - Isocrates). (Accademia Toscana di Scienze e Lettere "La Colombaria". Union Académique Internationale. Unione Accademica Nazionale.) 114T 940-942
**Principal Edition**

**HTML code:**
```
   <tr>
     <th>Principal Edition</th>
     <td>P. Berol. 10747 Ostrakon = Isokrates, An Demonikos pt. 28. </td>
  </tr>
  <tr>
     <th>Principal Edition</th>
     <td>Corpus dei Papiri filosofici greci e latini (CPF). Testi e lessico nei papiri di cultura                                        greca e latina. Parte I.2* - 2**: Cultura e Filosofia (Galenus - Isocrates). (Accademia Toscana di Scienze e Lettere "La Colombaria". Union Académique Internationale. Unione Accademica Nazionale.) 114T 940-942
     </td>
  </tr>
  <tr>
      <th>Principal Edition</th>
      <td> </td>
  </tr>
```
There is an empty Principal Edition, but that is due to an empty bibl element: https://github.com/DCLP/idp.data/blob/master/DCLP/62/61352.xml#L200

**Comment by wsalesky** [comment]
@rla2118 @jcowey 
Okay, back and caffeinated. 

The current rule for principalEdition in https://github.com/papyri/navigator/blob/master/pn-xslt/htm-teibibl.xsl first selects `t:title[@type='short-Checklist']` and defaults to` t:title` if `@type='short-Checklist'` is not available. For all other bibl types, there is a more convoluted rule, that also pulls in `t:relatedItem[@type='appearsIn']/t:title` 

All that is to say I can add the relatedItem handling to the principalEdition template. A few questions about the logic rules: 

1. Should the title found in the `t:relatedItem[@type='appearsIn']/t:ptr`  take precedence over the `t:title[@type='short-Checklist']`? 

Also, in this bibl record: https://github.com/papyri/idp.data/blob/master/Biblio/1/511.xml there are two titles:

1. Does the  `t:title/@type="short-BP"` take precedence over the `t:title/@type="main"`? 
2. Should `t:title/@type="main"` be used if there is no short title?

**Comment by paregorios** [comment]
@rla2118 and @jcowey please provide answers to @wsalesky's questions on this issue. We are blocked on completion until they are addressed. Thanks.

**Comment by rla2118** [comment]
I'm ill versed in the jargon here.  I defer to James.

**Comment by wsalesky** [comment]
@jcowey Thoughts on the questions below?

1. Should the title found in the t:relatedItem[@type='appearsIn']/t:ptr take precedence over the t:title[@type='short-Checklist']?

Also, in this bibl record: https://github.com/papyri/idp.data/blob/master/Biblio/1/511.xml there are two titles:

1. Does the t:title/@type="short-BP" take precedence over the t:title/@type="main"?
2. Should t:title/@type="main" be used if there is no short title?

**Comment by paregorios** [comment]
@jcowey to respond

**Comment by paregorios** [comment]
This is a duplicate for #31. I'm consolidating this information into that ticket and will reiterate the question for @jcowey there.

**Comment by paregorios** [comment]
Transferred info to #31. Closing this ticket as duplicate.
