### ISSUE TITLE
missing diacriticals in multiple texts

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#282]
Papyrologists: what is the **right** way to do this?

This issue is a blocker for resolution of #130.

In sorting through issue #130, I believe I have discovered that encoding practice for dealing with lenis, asper, etc. in the original witness is inconsistent across the corpus. Take, for example, lenis. In DDB we find the following examples in 10 texts:

 - [BGU 3.715](https://github.com/DCLP/idp.data/tree/master/DDB_EpiDoc_XML/bgu/bgu.3/bgu.3.715.xml): ```<hi rend="lenis">Ἀ</hi>```
 - [P.Dura 31](https://github.com/DCLP/idp.data/tree/master/DDB_EpiDoc_XML/p.dura/p.dura.31.xml): ```<hi rend="lenis"><gap reason="illegible" quantity="1" unit="character"/></hi>```
 - [P.Lond. 5.1808](https://github.com/DCLP/idp.data/tree/master/DDB_EpiDoc_XML/p.lond/p.lond.5/p.lond.5.1808.xml): ```<hi rend="lenis">ὑ</hi>```
 - [P.Muench. 1.13](https://github.com/DCLP/idp.data/tree/master/DDB_EpiDoc_XML/p.muench/p.muench.1/p.muench.1.13.xml): ```<hi rend="lenis">ἢ</hi> ἀντιποιησομένου ἐν παντὶ καιρῷ <hi rend="lenis">ἢ</hi>```
   - ```<hi rend="lenis">ἢ</hi> καὶ μηδενὸς τέκνων <hi rend="lenis">ἢ</hi> ἐγγόνων <hi rend="lenis">ἢ</hi> ξένων <hi rend="lenis">ἢ</hi> οἰκείων πρὸς πατρὸς <hi rend="lenis">ἢ</hi>```
   - ```<hi rend="lenis">ἢ</hi> τέκνοις <hi rend="diaeresis">ὑ</hi>μῶν <hi rend="lenis">ἢ</hi> ἐγγόνοις <hi rend="lenis">ἢ</hi> διαδόχοις <hi rend="lenis">ἢ</hi> διακατόχοις <hi rend="lenis">ἢ</hi> ἐνάγειν <hi rend="lenis">ἢ</hi>```
   - ```<hi rend="lenis">ἢ</hi> ἐγκαλέσειν ταύτης ἕνεκεν τῆς πράσεως <hi rend="lenis">ἢ</hi> παραβῆναι <hi rend="lenis">ἢ</hi>```
   - ```<hi rend="lenis">ἢ</hi> χρόνῳ μεθʼ<g type="apostrophe"/> <hi rend="diaeresis">ὑ</hi>πογραφῆς τοῦ <hi rend="diaeresis">ὑ</hi>πὲρ ἡμῶν <hi rend="diaeresis">ὑ</hi>```
 - [P.Ness. 3](https://github.com/DCLP/idp.data/tree/master/DDB_EpiDoc_XML/p.ness/p.ness.3/p.ness.3.31.xml): ```<hi rend="lenis"><unclear>ἧ</unclear></hi>```
   - ```<hi rend="lenis">ἷ</hi>```
   - ```<hi rend="lenis">ο</hi>```
   - ```<hi rend="lenis">υ</hi>```
   - ```<hi rend="lenis">ο</hi>```
 - [P.Panop.Beatty 2](https://github.com/DCLP/idp.data/tree/master/DDB_EpiDoc_XML/p.panop.beatty/p.panop.beatty.2.xml): ```<hi rend="lenis">ἐ</hi>```
 - [P.Prag 1.37](https://github.com/DCLP/idp.data/tree/master/DDB_EpiDoc_XML/p.prag/p.prag.1/p.prag.1.37.xml): ```<hi rend="lenis">ο</hi>```
 - [P.Rain.Cent. 152](https://github.com/DCLP/idp.data/tree/master/DDB_EpiDoc_XML/p.rain.cent/p.rain.cent.152.xml): ```<hi rend="lenis">Ἰ</hi>ουλίῳ <choice><reg>Γαι<supplied reason="omitted">α</supplied>νοῦ</reg><orig>Γα<hi rend="diaeresis">ι</hi>```
   - ```<hi rend="lenis">Ἠ</hi>```
 - [P.Ryl. 4.624](https://github.com/DCLP/idp.data/tree/master/DDB_EpiDoc_XML/p.ryl/p.ryl.4/p.ryl.4.624.xml): ```<hi rend="lenis">ἦ</hi>```
 - [SB 6.9140](https://github.com/DCLP/idp.datatree/master//DDB_EpiDoc_XML/sb/sb.6/sb.6.9140.xml): ```<hi rend="lenis">ἀ</hi>```

In most of these cases, the proper unicode character(s) for lenis and the vowel are encoded, and the fact of the ancient usage of same is indicated by using the ```<hi>``` element. But note P.Prag 1.37, which omits the unicode lenis, and P.Ness 3, which is internally inconsistent.

A similar lack of consistency can be found in the DCLP content:

 - [TM 113264](https:/github.com/DCLP/idp.data/tree/master/DCLP/114/113264.xml): ```<hi rend="lenis">ε</hi>```
 - [TM 370041](https:/github.com/DCLP/idp.data/tree/master/DCLP/371/370041.xml): 
   - ```<hi rend="lenis">ἄ</hi>```
   - ```<hi rend="lenis">ἐ</hi>```
   - ```<hi rend="lenis"><unclear>ὰ</unclear></hi>```
   - ```<hi rend="lenis">ο</hi>```
   - ```<hi rend="lenis"><unclear>η</unclear></hi>```
   - ```<hi rend="lenis">ἐ</hi>```
   - ```<hi rend="lenis">ε</hi>```
 - [TM 62564](https:/github.com/DCLP/idp.data/tree/master/DCLP/63/62564.xml): 
   - ```<hi rend="lenis"><hi rend="circumflex">α</hi></hi>```
   - ```<hi rend="lenis"><hi rend="acute">ἴ</hi></hi>τ<g type="apostrophe"/> <hi rend="lenis"><hi rend="circumflex">ὦ</hi></hi>```
 - [TM 63423](https:/github.com/DCLP/idp.data/tree/master/DCLP/64/63423.xml): 
   - ```<hi rend="lenis">Α</hi>```
   - ```<hi rend="lenis">Α</hi>```
   - ```<hi rend="lenis">Α</hi>σμβ</num></add><del rend="corrected"><num value="1243"><hi rend="lenis">Α</hi>```
   - ```<hi rend="lenis">Α</hi>```
   - ```<hi rend="lenis">Α</hi>```
   - ```<hi rend="lenis">Α</hi>```
   - ```<hi rend="lenis">Α</hi>```
 - [TM 68628](https:/github.com/DCLP/idp.data/tree/master/DCLP/69/68628.xml): 
   - ```<hi rend="lenis">ἐ</hi>```
   - ```<hi rend="lenis">ἐ</hi>φ<g type="apostrophe"/> ο<hi rend="circumflex">ἷ</hi>```
   - ```<hi rend="lenis"><unclear>ἀ</unclear></hi><supplied reason="lost">νθ</supplied><hi rend="acute"><unclear>ά</unclear></hi><supplied reason="lost">δ’</supplied> <unclear>ὄ</unclear><supplied reason="lost">ντα το</supplied><hi rend="circumflex"><unclear>ῖ</unclear></hi><unclear>ς</unclear> <supplied reason="lost">ἐ</supplied>κε<hi rend="circumflex">ῖ</hi> φρ<hi rend="acute">ά</hi>```

@rla2118 @jcowey @HolgerEssler @rogerbagnall @jds15 @jlougovaya

**Comment by jds15** [comment]
I might not follow entirely, but… Do not expect consistency between unicode and Hi@. <hi rend="lenis”> represents what the scribe wrote in antiquity on the papyrus. The Unicode chars, whether they agree with what the scribe wrote or not, represent what the modern editor printed in the edition.

this help?

--
Associate Professor in Class
ical Studies & History, Duke
University | Duke Collaborat
ory for Classics Computing |
Greek, Roman and Byzantine S
tudies | Duke Data Bank of D
ocumentary Papyri | papyri.i
nfo | people.duke.edu/~jds15<http://people.duke.edu/~jds15>

On Jun 13, 2017, at 11:44 AM, Tom Elliott <notifications@github.com<mailto:notifications@github.com>> wrote:


Papyrologists: what is the right way to do this?

In sorting through issue #130<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DCLP_dclpxsltbox_issues_130&d=DwMFaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=GWmHrFDZvSPNmQnfB_uD9Q&m=4f_CVda36zfrayONoZ1U55p-f0O-KqPU-zswi3gmxdk&s=IHDC7QKytLCvlo2j5aaaWT6vq8aypITO62rlqdEgZUk&e=>, I believe I have discovered that encoding practice for dealing with lenis, asper, etc. in the original witness is inconsistent across the corpus. Take, for example, lenis. In DDB we find the following examples in 10 texts:

  *   BGU 3.715<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DCLP_idp.data_tree_master_DDB-5FEpiDoc-5FXML_bgu_bgu.3_bgu.3.715.xml&d=DwMFaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=GWmHrFDZvSPNmQnfB_uD9Q&m=4f_CVda36zfrayONoZ1U55p-f0O-KqPU-zswi3gmxdk&s=LxG0cvEyOYuH5oqJTJJVyp6WkPIxeAzDwKrjYjKVPV4&e=>: <hi rend="lenis">Ἀ</hi>
  *   P.Dura 31<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DCLP_idp.data_tree_master_DDB-5FEpiDoc-5FXML_p.dura_p.dura.31.xml&d=DwMFaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=GWmHrFDZvSPNmQnfB_uD9Q&m=4f_CVda36zfrayONoZ1U55p-f0O-KqPU-zswi3gmxdk&s=ZDwVsOFsaejrYnbppfI0b7HpgVzAiOjFiP5dDvfJ28Q&e=>: <hi rend="lenis"><gap reason="illegible" quantity="1" unit="character"/></hi>
  *   P.Lond. 5.1808<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DCLP_idp.data_tree_master_DDB-5FEpiDoc-5FXML_p.lond_p.lond.5_p.lond.5.1808.xml&d=DwMFaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=GWmHrFDZvSPNmQnfB_uD9Q&m=4f_CVda36zfrayONoZ1U55p-f0O-KqPU-zswi3gmxdk&s=wEmenkF2kJhJa6AFiH_VQQpblJp3O3iM4zj3xYkdaT0&e=>: <hi rend="lenis">ὑ</hi>
  *   P.Muench. 1.13<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DCLP_idp.data_tree_master_DDB-5FEpiDoc-5FXML_p.muench_p.muench.1_p.muench.1.13.xml&d=DwMFaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=GWmHrFDZvSPNmQnfB_uD9Q&m=4f_CVda36zfrayONoZ1U55p-f0O-KqPU-zswi3gmxdk&s=7vr9SDHuyWDncMr4VvjqMqPqjwb1tPzLsAZ1y9ch6us&e=>: <hi rend="lenis">ἢ</hi> ἀντιποιησομένου ἐν παντὶ καιρῷ <hi rend="lenis">ἢ</hi>
     *   <hi rend="lenis">ἢ</hi> καὶ μηδενὸς τέκνων <hi rend="lenis">ἢ</hi> ἐγγόνων <hi rend="lenis">ἢ</hi> ξένων <hi rend="lenis">ἢ</hi> οἰκείων πρὸς πατρὸς <hi rend="lenis">ἢ</hi>
     *   <hi rend="lenis">ἢ</hi> τέκνοις <hi rend="diaeresis">ὑ</hi>μῶν <hi rend="lenis">ἢ</hi> ἐγγόνοις <hi rend="lenis">ἢ</hi> διαδόχοις <hi rend="lenis">ἢ</hi> διακατόχοις <hi rend="lenis">ἢ</hi> ἐνάγειν <hi rend="lenis">ἢ</hi>
     *   <hi rend="lenis">ἢ</hi> ἐγκαλέσειν ταύτης ἕνεκεν τῆς πράσεως <hi rend="lenis">ἢ</hi> παραβῆναι <hi rend="lenis">ἢ</hi>
     *   <hi rend="lenis">ἢ</hi> χρόνῳ μεθʼ<g type="apostrophe"/> <hi rend="diaeresis">ὑ</hi>πογραφῆς τοῦ <hi rend="diaeresis">ὑ</hi>πὲρ ἡμῶν <hi rend="diaeresis">ὑ</hi>
  *   P.Ness. 3<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DCLP_idp.data_tree_master_DDB-5FEpiDoc-5FXML_p.ness_p.ness.3_p.ness.3.31.xml&d=DwMFaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=GWmHrFDZvSPNmQnfB_uD9Q&m=4f_CVda36zfrayONoZ1U55p-f0O-KqPU-zswi3gmxdk&s=__aE9Xxk4eWj1av7FgSZLGBr8U9prA8e-5gFgjMxVmM&e=>: <hi rend="lenis"><unclear>ἧ</unclear></hi>
     *   <hi rend="lenis">ἷ</hi>
     *   <hi rend="lenis">ο</hi>
     *   <hi rend="lenis">υ</hi>
     *   <hi rend="lenis">ο</hi>
  *   P.Panop.Beatty 2<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DCLP_idp.data_tree_master_DDB-5FEpiDoc-5FXML_p.panop.beatty_p.panop.beatty.2.xml&d=DwMFaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=GWmHrFDZvSPNmQnfB_uD9Q&m=4f_CVda36zfrayONoZ1U55p-f0O-KqPU-zswi3gmxdk&s=ZAUmtvoEef0TFs8Dof5gSpmRdjWcgQljRrfW1V_MMhU&e=>: <hi rend="lenis">ἐ</hi>
  *   P.Prag 1.37<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DCLP_idp.data_tree_master_DDB-5FEpiDoc-5FXML_p.prag_p.prag.1_p.prag.1.37.xml&d=DwMFaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=GWmHrFDZvSPNmQnfB_uD9Q&m=4f_CVda36zfrayONoZ1U55p-f0O-KqPU-zswi3gmxdk&s=I7Nu_iLFpXg0nwkOJTPKNyODTTAggei5_4-K3byQfKQ&e=>: <hi rend="lenis">ο</hi>
  *   P.Rain.Cent. 152<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DCLP_idp.data_tree_master_DDB-5FEpiDoc-5FXML_p.rain.cent_p.rain.cent.152.xml&d=DwMFaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=GWmHrFDZvSPNmQnfB_uD9Q&m=4f_CVda36zfrayONoZ1U55p-f0O-KqPU-zswi3gmxdk&s=UnpDdX650jZRzptWbHXNHxMD5UsfrX13ms9jBD5JOHo&e=>: <hi rend="lenis">Ἰ</hi>ουλίῳ <choice><reg>Γαι<supplied reason="omitted">α</supplied>νοῦ</reg><orig>Γα<hi rend="diaeresis">ι</hi>
     *   <hi rend="lenis">Ἠ</hi>
  *   P.Ryl. 4.624<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DCLP_idp.data_tree_master_DDB-5FEpiDoc-5FXML_p.ryl_p.ryl.4_p.ryl.4.624.xml&d=DwMFaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=GWmHrFDZvSPNmQnfB_uD9Q&m=4f_CVda36zfrayONoZ1U55p-f0O-KqPU-zswi3gmxdk&s=8IhkW-kcZ0dah60Ga3mxyRE2s4qhcYYxik6BxdgfiDg&e=>: <hi rend="lenis">ἦ</hi>
  *   SB 6.9140<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DCLP_idp.datatree_master__DDB-5FEpiDoc-5FXML_sb_sb.6_sb.6.9140.xml&d=DwMFaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=GWmHrFDZvSPNmQnfB_uD9Q&m=4f_CVda36zfrayONoZ1U55p-f0O-KqPU-zswi3gmxdk&s=ZEblGrB9Z0xtCITALiA6sJXOYFej9NXYPvqkybaLtwE&e=>: <hi rend="lenis">ἀ</hi>

In most of these cases, the proper unicode character(s) for lenis and the vowel are encoded, and the fact of the ancient usage of same is indicated by using the <hi> element. But note P.Prag 1.37, which omits the unicode lenis, and P.Ness 3, which is internally inconsistent.

A similar lack of consistency can be found in the DCLP content:

  *   TM 113264<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DCLP_idp.data_tree_master_DCLP_114_113264.xml&d=DwMFaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=GWmHrFDZvSPNmQnfB_uD9Q&m=4f_CVda36zfrayONoZ1U55p-f0O-KqPU-zswi3gmxdk&s=RgutiLfO637ktY2gqwq3WX6s6QSKa910pEPTSIhGlqA&e=>: <hi rend="lenis">ε</hi>
  *   TM 370041<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DCLP_idp.data_tree_master_DCLP_371_370041.xml&d=DwMFaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=GWmHrFDZvSPNmQnfB_uD9Q&m=4f_CVda36zfrayONoZ1U55p-f0O-KqPU-zswi3gmxdk&s=p16ifTONG8jn92jZByUCeE5ldczFz9AhE5CeU1GlXbs&e=>:
     *   <hi rend="lenis">ἄ</hi>
     *   <hi rend="lenis">ἐ</hi>
     *   <hi rend="lenis"><unclear>ὰ</unclear></hi>
     *   <hi rend="lenis">ο</hi>
     *   <hi rend="lenis"><unclear>η</unclear></hi>
     *   <hi rend="lenis">ἐ</hi>
     *   <hi rend="lenis">ε</hi>
  *   TM 62564<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DCLP_idp.data_tree_master_DCLP_63_62564.xml&d=DwMFaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=GWmHrFDZvSPNmQnfB_uD9Q&m=4f_CVda36zfrayONoZ1U55p-f0O-KqPU-zswi3gmxdk&s=lKW65Z01jud2Fg-6fb13Vw1yy0wWtHIFbEjdLvReLhY&e=>:
     *   <hi rend="lenis"><hi rend="circumflex">α</hi></hi>
     *   <hi rend="lenis"><hi rend="acute">ἴ</hi></hi>τ<g type="apostrophe"/> <hi rend="lenis"><hi rend="circumflex">ὦ</hi></hi>
  *   TM 63423<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DCLP_idp.data_tree_master_DCLP_64_63423.xml&d=DwMFaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=GWmHrFDZvSPNmQnfB_uD9Q&m=4f_CVda36zfrayONoZ1U55p-f0O-KqPU-zswi3gmxdk&s=g3GAaKfFnixboCcXAcXEANWle823z0e65zl2YnGzopc&e=>:
     *   <hi rend="lenis">Α</hi>
     *   <hi rend="lenis">Α</hi>
     *   <hi rend="lenis">Α</hi>σμβ</num></add><del rend="corrected"><num value="1243"><hi rend="lenis">Α</hi>
     *   <hi rend="lenis">Α</hi>
     *   <hi rend="lenis">Α</hi>
     *   <hi rend="lenis">Α</hi>
     *   <hi rend="lenis">Α</hi>
  *   TM 68628<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DCLP_idp.data_tree_master_DCLP_69_68628.xml&d=DwMFaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=GWmHrFDZvSPNmQnfB_uD9Q&m=4f_CVda36zfrayONoZ1U55p-f0O-KqPU-zswi3gmxdk&s=xh6BN0K6_IA-UwSdlh3PidhnRYyUQpfHpbmQBPjOUU0&e=>:
     *   <hi rend="lenis">ἐ</hi>
     *   <hi rend="lenis">ἐ</hi>φ<g type="apostrophe"/> ο<hi rend="circumflex">ἷ</hi>
     *   <hi rend="lenis"><unclear>ἀ</unclear></hi><supplied reason="lost">νθ</supplied><hi rend="acute"><unclear>ά</unclear></hi><supplied reason="lost">δ’</supplied> <unclear>ὄ</unclear><supplied reason="lost">ντα το</supplied><hi rend="circumflex"><unclear>ῖ</unclear></hi><unclear>ς</unclear> <supplied reason="lost">ἐ</supplied>κε<hi rend="circumflex">ῖ</hi> φρ<hi rend="acute">ά</hi>

@rla2118<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_rla2118&d=DwMFaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=GWmHrFDZvSPNmQnfB_uD9Q&m=4f_CVda36zfrayONoZ1U55p-f0O-KqPU-zswi3gmxdk&s=b-yQM2ub3hF18bEVBeCeoQcRDcCQaiu51Lxc0hIbFGQ&e=> @jcowey<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jcowey&d=DwMFaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=GWmHrFDZvSPNmQnfB_uD9Q&m=4f_CVda36zfrayONoZ1U55p-f0O-KqPU-zswi3gmxdk&s=9Nlfvm7sfIVzNrnSRov_1pKcpwU9bS9w_WiSQdW5tIw&e=> @HolgerEssler<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_holgeressler&d=DwMFaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=GWmHrFDZvSPNmQnfB_uD9Q&m=4f_CVda36zfrayONoZ1U55p-f0O-KqPU-zswi3gmxdk&s=XYsWi4OfOtRucqkTEuVMylJN4Fc-umn7PJreEfw-zF4&e=> @rogerbagnall<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_rogerbagnall&d=DwMFaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=GWmHrFDZvSPNmQnfB_uD9Q&m=4f_CVda36zfrayONoZ1U55p-f0O-KqPU-zswi3gmxdk&s=znD2C8-85IWwBJsTn2o8x7PyymPYJKw7jZ_s-6cJ388&e=> @jds15<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jds15&d=DwMFaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=GWmHrFDZvSPNmQnfB_uD9Q&m=4f_CVda36zfrayONoZ1U55p-f0O-KqPU-zswi3gmxdk&s=YJBCENtBN0TASX6UTjF09bzFJvOmcMv7jKYqNxcgiIo&e=> @jlougovaya<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jlougovaya&d=DwMFaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=GWmHrFDZvSPNmQnfB_uD9Q&m=4f_CVda36zfrayONoZ1U55p-f0O-KqPU-zswi3gmxdk&s=7XVaCPv4j9TBx4eYdZ04CNqpjl82o1qreNhHap2xHKw&e=>

**Comment by rla2118** [comment]
Josh is right.  Spot-checking some of the TM numbers that were said to have inconsistent elements didn't turn up any real inconsistencies. They were cases where <hi rend="lenis”> and the Unicode lenis did not coincide.

**Comment by paregorios** [comment]
Thanks both for explaining and checking. Your answers will help us narrow down what the real issue is for #130.

**Comment by jds15** [comment]
At #130 I see:
= = =

Leiden+: <:<# Α( ᾿)σμβ=1242#>|subst|<# Α( ᾿)σμγ=1243#>:>

Displayed
corr. ex Α(ἀ)σμγ : ἀσμβ papyrus

Expected to see:
corr. ex Ασμγ : ἀσμγ papyrus : ἀσμβ papyrus
= = =

For last I think *I* expect to see:
Text: Aσμβ
app: corr. ex Ασμγ ; Α᾿σμγ papyrus

*Really* I don’t expect to see ancient lenis on numbers at all. But if there were an analogous example with words rather than numbers, this is how I’d expect it to render.

And in fact I’d prefer
Text: Aσμβ
app: corr. ex Α᾿σμγ
…but we handle ancient diacriticals as a separate app entry, which is crap, but (we decided) less crap than what we would have had to do to display the ancient diacriticals up in the text (or as necessary embedded in app entries).

josh

--
Associate Professor in Class
ical Studies & History, Duke
University | Duke Collaborat
ory for Classics Computing |
Greek, Roman and Byzantine S
tudies | Duke Data Bank of D
ocumentary Papyri | papyri.i
nfo | people.duke.edu/~jds15<http://people.duke.edu/~jds15>

On Jun 14, 2017, at 12:34 PM, Tom Elliott <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks both for explaining and checking. Your answers will help us narrow down what the real issue is for #130<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DCLP_dclpxsltbox_issues_130&d=DwMCaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=GWmHrFDZvSPNmQnfB_uD9Q&m=hmXsN0-5IvScXSpmX_f6WpKTtIzTMAzWgt41FNbqOnU&s=9_-AOZ41jPRhMgxz--oVAc0I0ZnUDmOMwyW780wzexA&e=>.

**Comment by paregorios** [comment]
@rla2118 and @jcowey to follow up with response/resolution of issues raised above by @jds15

**Comment by jcowey** [comment]
When Greek letters are used to indicate numbers I would prefer to see the use in DCLP of capital Greek letters to indicate that we are dealing with multiples of thousands (as we do in papyri.info for the documentary texts). It would then be consistent practice across ddbdp and dclp. If that decision were taken we would have to clean up a few files in DCLP and part of this problem would disappear.

**Comment by rogerbagnall** [comment]
Agreed. Always use caps for thousands.

**Comment by paregorios** [comment]
@jcowey please clarify in two ways:

1. You want to see the text ENTERED with capital Greek letters (for thousands) or you want to see them entered however but ALWAYS have them OUTPUT BY XSLT in capitals?
2. I do not see that you have addressed whether you agree otherwise with the recommendation made by @jds15 at all.

Thanks

**Comment by paregorios** [comment]
/me to add clarification notes and assign for resolution.

**Comment by paregorios** [comment]
Per @jcowey there is conflation in discussion above between technical requirements and papyri.info/dclp data entry conventions. To wit:

 - For Greek alphabetic numerals, the text is to be ENTERED by the user with capital Greek letters (for thousands). No XSLT modifications to capitalization are expected or desired.
 - For Greek alphabetic numerals, it is editorial policy in papyri.info for the user to OMIT ENTERING any diacritical marks made by the ancient scribe except overlines. 

Consequently, no "ancient lenis" should have been entered with the numerals in TM 63423 in the first place. So, this is a "no action."
