### ISSUE TITLE
Biblio not reaching HTML from Editor

### ISSUE THREAD

**Issue by rla2118** [DCLP/dclpxsltbox#285]
This issue concerns 

http://litpap.info/editor/publications/648/dclp_meta_identifiers/1335/edit
and
http://litpap.info/dclp/217929

In the editor, the biblio number (95345) is present and it appears in the XML as follows      

```<div type="bibliography" subtype="principalEdition">
            <listBibl>
               <bibl type="publication" subtype="principal">
            <!-- ignore - start, i.e. SoSOL users may not edit this -->
            <!-- ignore - stop -->
                  <ptr target="http://papyri.info/biblio/95345"/>
               </bibl>
            </listBibl>
         </div> 
```

In the HTML and prodo XML, however, it is absent.

**Comment by rla2118** [comment]
Just to follow up: part of the biblio record is now displaying for this record (http://litpap.info/dclp/217929).  It's only the article title, however, and not the author, journal, etc.

**Comment by paregorios** [comment]
It would appear that this is a duplicate for #31. I have transferred details there and am closing this ticket as a duplicate.
