### ISSUE TITLE
invalid XML has been committed to master for some Herculaneum texts

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#302]
The following XML files are currently invalid in DCLP/idp.data master:

 - TM 62384
 - TM 62393
 - TM 62499
 - TM 62500

Full transcript of errors generated by saxon during XML processing:

> Error on line 38 column 12 
  SXXP0003: Error reported by XML parser: The element type "idno" must be terminated by the
  matching end-tag "</idno>".
org.xml.sax.SAXParseException; lineNumber: 38; columnNumber: 12; The element type "idno" must be terminated by the matching end-tag "</idno>". processing file /Users/paregorios/Documents/files/D/dclp-xslt/dclpxsltbox/../idp.data/DCLP/63/62384.xml

>Error on line 881 column 24 
  SXXP0003: Error reported by XML parser: The element type "custEvent" must be terminated by
  the matching end-tag "</custEvent>".
org.xml.sax.SAXParseException; lineNumber: 881; columnNumber: 24; The element type "custEvent" must be terminated by the matching end-tag "</custEvent>". processing file /Users/paregorios/Documents/files/D/dclp-xslt/dclpxsltbox/../idp.data/DCLP/63/62393.xml

> Error on line 2413 column 24 
  SXXP0003: Error reported by XML parser: The element type "custEvent" must be terminated by
  the matching end-tag "</custEvent>".
org.xml.sax.SAXParseException; lineNumber: 2413; columnNumber: 24; The element type "custEvent" must be terminated by the matching end-tag "</custEvent>". processing file /Users/paregorios/Documents/files/D/dclp-xslt/dclpxsltbox/../idp.data/DCLP/63/62500.xml

> Error on line 1772 column 24 
  SXXP0003: Error reported by XML parser: The element type "custEvent" must be terminated by
  the matching end-tag "</custEvent>".
org.xml.sax.SAXParseException; lineNumber: 1772; columnNumber: 24; The element type "custEvent" must be terminated by the matching end-tag "</custEvent>". processing file /Users/paregorios/Documents/files/D/dclp-xslt/dclpxsltbox/../idp.data/DCLP/63/62499.xml

**Comment by HolgerEssler** [comment]
This should be solved now by the following commit
https://github.com/DCLP/idp.data/commit/c027df1470fb20be5dc983b1d309486923165a0f
@paregorios please check, if any problems persist.
