### ISSUE TITLE
implement better top-level navigation

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#303]
This ticket has been split off from #288.

**Comment by paregorios** [comment]
Resolution of this ticket is a blocker for #288.

**Comment by paregorios** [comment]
The DCLP project has introduced new elements into the top-level navigation in order to facilitate access to DCLP content. A new link ("DCLP") has been added to the main menu bar, as is clear from comparison of these screen captures:

**Comment by paregorios** [comment]
# Inadequacies, concerns, and suggested resolutions

## 1. "[ddbdp browse](http://litpap.info/browse/ddbdp/)" and "[dclp browse](http://litpap.info/browse/dclp/)" overlap

When one clicks through to the main "DDBDP" or the main "DCLP" browse pages, one is presented with a list of series represented in the corresponding collection. One then selects the link corresponding to the series of interest, yielding another page listing the volumes of that series that are represented in the corresponding collection. BGU is a good example: [DDBDP takes in 20 volumes](http://litpap.info/browse/ddbdp/bgu) whereas [DCLP takes in only five](http://litpap.info/browse/dclp/bgu). But then one clicks through the link for the volume of interest and finds oneself at the standard search page, with the series and volume pre-selected. What's **not** preselected is the collection, such that the the results of clicking through the following link chains are exactly the same (i.e., they include the union set of BGU 2 content found in DDBDP and DCLP):

- [browse ddbdp](http://litpap.info/browse/ddbdp/) => [bgu](http://litpap.info/browse/ddbdp/bgu) => [bgu 2](http://litpap.info/search?SERIES=bgu&VOLUME=2)
- [browse dclp](http://litpap.info/browse/dclp/) => [bgu](http://litpap.info/browse/dclp/bgu) => [bgu 2](http://litpap.info/search?SERIES=bgu&VOLUME=2)

Note that the URL one gets for the final step in each of the above browse paths is identical to the other: http://litpap.info/search?SERIES=bgu&VOLUME=2

**recommendation:** include a query parameter that differentiates between DCLP and DDBDP at the final step (related issue: #264).

## 2. "[dclp browse](http://litpap.info/browse/dclp/)" vs. "[browse by series](http://litpap.info/browse/dclp/series)" 

At present, given the above information architecture, there are two browse-by-series affordances provided by the DCLP interface: [one](http://litpap.info/browse/dclp/) by clicking through the "DCLP" link and [the other](http://litpap.info/browse/dclp/series) by activating the "dropdown" on that link and then selecting "browse by series." I submit that this dichotomy is not only redundant, but likely to confuse and frustrate users. We should try to fix the "dclp browse" as discussed in section 1 (above) and get rid of the dropdown's "browse by series" function entirely. Indeed, [@m-k-r calls out the dropdown's "browse by series" function](https://github.com/DCLP/dclpxsltbox/issues/288#issuecomment-316417284) in #288 as a quick-and-dirty workaround for the overlap/redundancy described above.

**recommendation:** eliminate the dropdown-accessed DCLP "[browse by series](http://litpap.info/browse/dclp/series)" affordance.

## 3. DCLP's "[browse by TM number](http://litpap.info/browse/dclp/tm)" vs. the existing TM-number lookup dialog

Core papyri.info functionality provides a TM lookup dialog via a link in the main navigation:

<img width="389" alt="screen shot 2017-07-20 at 5 04 56 pm" src="https://user-images.githubusercontent.com/263285/28440832-984aff22-6d6d-11e7-9412-7ae8e89a992d.png">

The added "browse by TM number" functionality on the DCLP dropdown seems redundant by comparison.

**recommendation:** eliminate the dropdown-accessed DCLP "[browse by TM number](http://litpap.info/browse/dclp/tm)" affordance.

## 4. DCLP "[authors and works](http://litpap.info/browse/dclp/authors)"

This is truly unique functionality and an essential axis of access for the literary papyri and surely should be retained. 

**recommendations:**

- Either eliminate the dropdown behavior and make "authors and works" a separate main link or eliminate the click-through behavior and modify the contents of the drop-down to be "browse by series" and "browse by authors and works"
- Eliminate the links to dclpxsltbox and github now found on the "authors and works" page, since these are artifacts of development effort

# The above recommendations are reflected in the following architecture diagrams:

## Option 1 (eliminate dropdown functionality entirely)

![option-nav-1](https://user-images.githubusercontent.com/263285/28441192-2c2d0644-6d6f-11e7-981f-c29944e12081.png)

## Option 2 (use dropdown as the only function on the DCLP link)

![option-nav-2](https://user-images.githubusercontent.com/263285/28441200-36c4f936-6d6f-11e7-899f-057bf54a3595.png)

**Comment by paregorios** [comment]
I invite comments from @rogerbagnall @rla2118 @jcowey @HolgerEssler and @jds15 on the recommendations laid out above. If we can get consensus on what you want to see, then we can move on to resolving the technical issues, including those in #288.

cc @hcayless @ryanfb @wsalesky @m-k-r

**Comment by rogerbagnall** [comment]
Perhaps I am missing something, but I don't see in either recommended architecture an option for the user to decide whether to be looking for only DDbDP content, only DCLP content, or both. I thought we had talked about this at an early stage. Or is this applicable only to search? Recommendation 1 above does seem to apply this to browse, but I don't see how it fits into the diagram.

**Comment by paregorios** [comment]
@rogerbagnall search across/within collections is addressed in a separate ticket (#264) as indicated parenthetically and telegraphically above, sub "Inadequacies..." sub "1" sub "recommendations".

Can I get thumbs up or thumbs down on my suggestions above from the papyrologists ( @rogerbagnall @rla2118 @jcowey @HolgerEssler and @jds15 ) ? We're running out of runway to address this issue.

**Comment by rogerbagnall** [comment]
I think I prefer the simplicity of option 1. The other recommendations seem OK to me.

**Comment by HolgerEssler** [comment]
I prefer option 1 as well.

**Comment by paregorios** [comment]
@hcayless Since I know you're working on the general technical problems underlying browse and search re-integration, I'm assigning this ticket to you so you are aware of what the users would like to see eventually.

**Comment by Edelweiss** [comment]
Option 1 already implemented in litpap.info
