### ISSUE TITLE
Remove Create New Publication button

### ISSUE THREAD

**Issue by rla2118** [DCLP/dclpxsltbox#304]
Because of problems we're experiencing with the "Create New Publication" feature in DCLP, it's probably best to remove the button from the Advanced Create page, http://litpap.info/editor/publications/advanced_create

**Comment by paregorios** [comment]
Removing my assignment since this issue, per discussion in the weekly tagup, is to be handed by Marcel, who is already assigned.

**Comment by m-k-r** [comment]
[comitted](https://github.com/DCLP/sosol/commit/3489cf922ef7f13d5bf43a4dbdd3b46e7cc34dbb) and tested on our testserver. I update litpap.info later this day when nobody is working on it.

**Comment by m-k-r** [comment]
Works on litpap.info. I think we can close this issue.
