### ISSUE TITLE
Hide surplus fields in author and works section of the editor

### ISSUE THREAD

**Issue by rla2118** [DCLP/dclpxsltbox#305]
From/to and certainty.

**Comment by Edelweiss** [comment]
![bildschirmfoto 2017-08-02 um 16 43 46](https://user-images.githubusercontent.com/612862/28879576-cff220d8-77a2-11e7-8ca5-c730e4f35736.png)

**Comment by Edelweiss** [comment]
![bildschirmfoto 2017-08-02 um 16 53 20](https://user-images.githubusercontent.com/612862/28879833-74e6faa0-77a3-11e7-8d03-748f0b0d5f50.png)

**Comment by paregorios** [comment]
@rla2118 please at your leisure assign priority and associate with a milestone (or not at your discretion).

**Comment by jcowey** [comment]
Has been done. Certainty and from to attributes no longer visible.
