### ISSUE TITLE
combo box content in metadata editor is not alphabetical

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#309]
For example, in the DCLP metadata editor when editing bibliographic entries, there is a long list of possible values for the reference system. If these were to appear in alphabetical order, it would be easier to find and pick the one the user is looking for:

<img width="254" alt="screen shot 2017-08-07 at 4 12 44 pm" src="https://user-images.githubusercontent.com/263285/29043988-5d448b6a-7b8b-11e7-98e2-88d08bb7d4a5.png">

**Comment by paregorios** [comment]
@rla2118 please prioritize

cc @rogerbagnall, who reported this issue

**Comment by ryanfb** [comment]
It's difficult to tell where exactly these values are coming from. It seems to be here https://github.com/DCLP/sosol/blob/master/public/javascripts/dclp.js#L121-L184 or here https://github.com/DCLP/sosol/blob/master/public/javascripts/dclp.js#L325-L346

But those are missing several values in the screenshot, such as "Line" or "Chapter". Also there appear to be several repeated values, both in the screenshot and in the JS. Somewhat disconcertingly some of these map the same user-visible string to different form values, such as:

```
<option value="pp">Pages</option>
<option value="pages">Pages</option>
```

**Comment by Edelweiss** [comment]
https://github.com/DCLP/sosol/commit/4b10085a9540138b7ec0cd33646cc94216506bd8

**Comment by jcowey** [comment]
I have made a spreadsheet of the values used in column A and of the list that we would like to change to (in other words getting rid of the duplicates, noted by Ryan above) in column B:

https://docs.google.com/spreadsheets/d/1bnd9Mtuooj1PB8qwNGRphBnkUwB0QZxyLIDYmcbS3C4/edit#gid=0

Would you, @paregorios , please assess what knock on effects / requirements that would have for XSLT. Obviously Carmen would have to make many change and replace commits to DCLP files which contain XML encoding that we would be changing.

**Comment by jcowey** [comment]
There is an issue from nearly two years ago, in which the @unit / @type on biblScope was flagged: https://github.com/papyri/idp.data/issues/9.

Carmen and I did go through the data in HGV and Biblio, but never got everything together in order to push for an upgrade of the XML in papyri.info. This is still something we would like to attend to sooner rather than later.

**Comment by paregorios** [comment]
While resolving #325, I also laid in flexibility for dealing with the various possible values of ```biblScope@type``` and ```biblScope@unit``` across the collections, so @jcowey and @Edelweiss I believe that you are clear to go ahead and make the data and code changes discussed above. 

If you want to see all the values for which we now cater, have a look at https://github.com/DCLP/navigator/blob/master/pn-xslt/htm-teibibl.xsl#L14

All the bibliographic formatting code now checks for any of the relevant values in either ```@type``` or ```@unit```, thereby making output as uniform as possible across DCLP, HGV, DDB, and Biblio even though there are differences in underlying encoding.

**Comment by Edelweiss** [comment]
as of now

- book
- chapter
- col
- columns
- fasc
- fascicle
- folio
- fragment
- fragments
- generic
- inventory
- issue
- line
- lines
- no
- number
- numbers
- page
- pages
- pp
- parts
- plate
- poem
- side
- tome
- vol
- volume

**Comment by Edelweiss** [comment]
as desired

- book
- chapter
- column
- fascicle
- folio
- fragment
- generic
- inventory
- issue
- line
- no
- number
- page
- part
- plate
- poem
- side
- tome
- volume

**Comment by Edelweiss** [comment]
deprecated

- col
- columns
- fasc
- fragments
- lines
- numbers
- pages
- pp
- parts
- vol

**Comment by Edelweiss** [comment]
https://github.com/DCLP/idp.data/commit/531efd190e50f4de45773d275fb5a011baffdc16

**Comment by Edelweiss** [comment]
https://github.com/DCLP/sosol/commit/0707a0a51f90fa65b1ad9a912552ff86e705cef7

**Comment by jcowey** [comment]
This has now been tested and functions well. 
There is a warning not which tells the user / editor what the chosen value was and invites the user / editor to choose the appropriate one from the drop down menu.
Once the correct value has been chosen the warning disappears.
