### ISSUE TITLE
illegal values in <objectDesc> "form" attribute cause errors in editor

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#311]
Some characters are prohibited from use in attribute values, but some illegal characters (e.g., "?") have been written into the "form" attribute on the ```<objectDesc>``` element in XML converted from LDAB (e.g., "roll?"). 

Files like this are invalid XML and shouldn't have been committed to the repository master branch without a successful attempt to validate them.

A user at the NYC workshop undertook to input a text for a DCLP stub file from LDAB that had this problem. He typed in the text and clicked "save." The editor reported an "XML Error" indicating an invalid value for the form attribute. Attempting to navigate back or to "save the broken Leiden plus" (which wasn't broken), resulted in everybody's favorite "we're sorry something went wrong" message.

**Comment by paregorios** [comment]
@jcowey @rla2118 please advise to whom this should be assigned for fixing

**Comment by jcowey** [comment]
yes this is bad news - shall have this chased up tomorrow

**Comment by jcowey** [comment]
which file was the one affected, so that it can be made available again?

**Comment by paregorios** [comment]
We fixed the file in question manually by editing the metadata and just
removing the question mark. I will assemble a list of other offending
files.

T

-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

Humanities Commons: @paregorios <https://hcommons.org/members/paregorios/>
OrcID: 0000-0002-4114-6677 <http://orcid.org/0000-0002-4114-6677>

**Comment by Edelweiss** [comment]
Validator versions:

SoSOL
http://www.stoa.org/epidoc/schema/8.22/tei-epidoc.rng

in eXist
/db/data/epidoc/schema/latest/tei-epidoc.rng

**Comment by Edelweiss** [comment]
Found one example

https://github.com/DCLP/idp.data/blob/master/DCLP/62/61362.xml#L34
