### ISSUE TITLE
dclp metadata editor tab reads "HGV" instead of "meta" (or something)

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#315]
<img width="631" alt="screen shot 2017-08-09 at 3 16 33 pm" src="https://user-images.githubusercontent.com/263285/29139693-d040b888-7d15-11e7-9391-cff50cca85b3.png">

**Comment by Edelweiss** [comment]
https://github.com/DCLP/sosol/commit/e4f948e5556087d844f7132e9bf513ab81c1f771

**Comment by jcowey** [comment]
Looks fine now.
