### ISSUE TITLE
Multiple Principal Editions

### ISSUE THREAD

**Issue by hcayless** [DCLP/dclpxsltbox#319]
There are 148 DCLP documents which have multiple principle editions. This is a completely new feature as far as the Navigator goes, and no provision has been made for it. How do you want this to work? A naïve implementation would lead to them showing up multiple times in search/browse results. A stupid implementation would mean my just grabbing the first one. Presumably neither of these is satisfactory...

I've attached a list of the affected files:

https://github.com/DCLP/idp.data/blob/master/DCLP/39/38657.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/40/39249.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/46/45958.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/56/55859.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/56/55861.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/56/55966.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/59/58915.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/60/59007.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/60/59008.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/60/59029.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/60/59074.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/60/59135.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/60/59141.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/60/59170.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/60/59212.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/60/59232.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/60/59265.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/60/59319.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/60/59370.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/60/59396.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/60/59397.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/60/59458.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/60/59485.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/60/59507.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/60/59519.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/60/59537.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/60/59788.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/60/59822.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/60/59843.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/60/59906.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/60/59927.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/60/59934.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/61/60091.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/61/60262.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/61/60332.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/61/60429.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/61/60977.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/62/61028.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/62/61073.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/62/61230.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/62/61269.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/62/61309.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/62/61420.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/62/61429.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/62/61458.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/62/61466.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/62/61505.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/62/61515.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/62/61520.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/62/61583.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/62/61594.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/62/61608.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/62/61630.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/62/61646.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/62/61721.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/62/61737.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/62/61784.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/62/61815.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/62/61859.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/62/61861.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/62/61915.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/62/61916.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/63/62054.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/63/62144.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/63/62265.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/63/62310.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/63/62312.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/63/62323.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/63/62327.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/63/62375.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/63/62564.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/63/62586.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/63/62593.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/63/62599.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/63/62741.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/63/62742.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/63/62746.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/63/62769.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/63/62856.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/63/62867.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/63/62913.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/63/62978.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/63/62983.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/64/63032.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/64/63125.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/64/63183.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/64/63194.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/64/63515.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/64/63589.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/64/63821.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/64/63877.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/64/63888.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/64/63912.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/64/63920.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/65/64289.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/65/64384.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/65/64391.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/65/64723.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/66/65002.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/66/65003.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/66/65010.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/66/65011.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/66/65014.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/66/65158.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/66/65174.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/66/65187.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/66/65225.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/66/65755.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/66/65840.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/66/65842.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/66/65844.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/66/65909.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/66/65945.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/67/66043.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/67/66432.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/67/66624.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/67/66913.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/69/68656.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/69/68816.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/69/68817.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/69/68819.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/69/68820.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/69/68959.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/69/68983.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/70/69673.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/79/78911.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/84/83358.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/84/83697.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/86/85073.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/108/107918.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/108/107951.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/108/107952.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/109/108050.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/109/108299.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/109/108517.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/109/108522.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/109/108529.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/109/108635.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/114/113383.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/118/117699.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/118/117703.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/118/117706.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/129/128545.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/131/130515.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/131/130717.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/144/143378.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/220/219269.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/221/220465.xml

**Comment by Edelweiss** [comment]
My approach woud be to change 
```
<idno type="dclp-hybrid">psi;11;1210</idno>
<idno type="dclp-hybrid">p.oxy;18;2160</idno>
```
at
https://github.com/DCLP/idp.data/blob/master/DCLP/60/59007.xml#L15-L16

to 
```
<idno type="dclp-hybrid">na;;59007</idno>
```

And all publication::principals will become reference::partial in

https://github.com/DCLP/idp.data/blob/master/DCLP/60/59007.xml#L96-L115

**Comment by Edelweiss** [comment]
file `idp.data/DCLP/144/143378.xml` was already fixed in the following commit

https://github.com/DCLP/idp.data/commit/d2e8d5707c19c1ea7a8ab7f8bce664c12d4cc82f

**Comment by Edelweiss** [comment]
https://github.com/DCLP/idp.data/tree/issue319

(also in development and master)

Affected dclp-hybrids (same files as the one in the list provided by Tom Elliot, except for TM no. 143378)

[bku;1;165, bku;1;166](http://litpap.info/dclp/107918) 
[p.lond.copt;;130, p.lond.copt;;133](http://litpap.info/dclp/107951) 
[p.lond.copt;;962, p.lond.copt;;122](http://litpap.info/dclp/107952) 
[bku;3.1;322, bku;3.1;326](http://litpap.info/dclp/108050) 
[bku;3.1;324, bku;3.1;325](http://litpap.info/dclp/108299) 
[p.mon.epiph;;7, p.mon.epiph;;8](http://litpap.info/dclp/108517) 
[p.mon.epiph;;13, p.mon.epiph;;18](http://litpap.info/dclp/108522) 
[p.mon.epiph;;22, p.mon.epiph;;52](http://litpap.info/dclp/108529) 
[p.lond.copt;;325, p.lond.copt;;338](http://litpap.info/dclp/108635) 
[o.petr.mus;;32, o.petr.mus;;33, o.petr.mus;;34](http://litpap.info/dclp/113383) 
[mpern.s;31;1, mpern.s;31;2](http://litpap.info/dclp/117699) 
[mpern.s;31;7, mpern.s;31;8](http://litpap.info/dclp/117703) 
[mpern.s;31;11, mpern.s;31;12](http://litpap.info/dclp/117706) 
[p.gen;4;148, p.gen;4;149](http://litpap.info/dclp/128545) 
[p.monts.roca;2;25, p.monts.roca;2;26, p.monts.roca;2;27](http://litpap.info/dclp/130515) 
[p.prag;3;206, p.prag;3;207](http://litpap.info/dclp/130717) 
[p.paramone;;5, p.scholl;;4, p.harrauer;;62](http://litpap.info/dclp/219269) 
[p.bodm;;20, p.bodm;;9](http://litpap.info/dclp/220465) 
[sb;16;12403, p.rain.unterricht;;171](http://litpap.info/dclp/38657) 
[p.rain.unterricht;;107, p.rain.unterrichtkopt;;178](http://litpap.info/dclp/39249) 
[p.cairo;2;31168, p.cairo;2;31169](http://litpap.info/dclp/45958) 
[p.cairo;2;30705, p.cairo;2;30706, p.cairo;2;30707](http://litpap.info/dclp/55859) 
[p.cairo;2;30824, p.cairo;2;30825](http://litpap.info/dclp/55861) 
[p.cairo;3;50138, p.cairo;3;50139, p.cairo;3;50140, p.tebt.tait;;17](http://litpap.info/dclp/55966) 
[p.oxy;56;3837, p.oxy;10;1250](http://litpap.info/dclp/58915) 
[psi;11;1210, p.oxy;18;2160](http://litpap.info/dclp/59007) 
[psi;11;1209, p.oxy;18;2161](http://litpap.info/dclp/59008) 
[p.oxy;18;2163, psi;15;1472](http://litpap.info/dclp/59029) 
[p.oxy;10;1233, p.oxy;17;2081](http://litpap.info/dclp/59074) 
[p.oxy;11;1364, p.oxy;52;3647](http://litpap.info/dclp/59135) 
[p.schub;;15, p.gen;4;157](http://litpap.info/dclp/59141) 
[p.oxy;9;1179, p.oxy;75;5027](http://litpap.info/dclp/59170) 
[p.oxy;15;1807, p.koeln;4;185](http://litpap.info/dclp/59212) 
[p.oxy;6;854, p.oxy;69;4708](http://litpap.info/dclp/59232) 
[p.oxy;56;3840, p.oxy;73;4935, p.oxy;78;5132](http://litpap.info/dclp/59265) 
[p.oxy;38;2832, p.oxy;47;3330](http://litpap.info/dclp/59319) 
[psi;11;1218, p.oxy;18;2170](http://litpap.info/dclp/59370) 
[p.oxy;18;2173, psi;15;1500](http://litpap.info/dclp/59396) 
[p.oxy;17;2079, p.oxy;18;2167, psi;11;1217](http://litpap.info/dclp/59397) 
[p.oxy;8;1097, p.oxy;10;1251](http://litpap.info/dclp/59458) 
[p.oxy;17;2078, p.oxy;50;3531](http://litpap.info/dclp/59485) 
[p.aberd;;113, p.aberd;;137](http://litpap.info/dclp/59507) 
[p.oxy;62;4314, p.oxy;70;4764](http://litpap.info/dclp/59519) 
[psi;11;1203, psi;16;1605](http://litpap.info/dclp/59537) 
[p.oxy;6;863, p.oxy;37;2806](http://litpap.info/dclp/59788) 
[p.oxy;27;2457, p.oxy;52;3650](http://litpap.info/dclp/59822) 
[p.ryl;3;547, p.oxy;2;224](http://litpap.info/dclp/59843) 
[p.koeln;6;252, p.oxy;60;4013](http://litpap.info/dclp/59906) 
[p.petr;1;1, p.petr;1;2](http://litpap.info/dclp/59927) 
[p.hamb;2;118, p.hamb;2;119](http://litpap.info/dclp/59934) 
[p.oxy;30;2511, psi;15;1465](http://litpap.info/dclp/60091) 
[p.lond.lit;;30, p.sijp;;3](http://litpap.info/dclp/60262) 
[p.princ;3;110, p.hamb;3;196](http://litpap.info/dclp/60332) 
[p.koeln;2;72, p.fouad;;1](http://litpap.info/dclp/60429) 
[psi;7;748, psi;7;749](http://litpap.info/dclp/60977) 
[o.petr.mus;;21, o.petr.mus;;22, o.petr.mus;;23, o.petr.mus;;24, o.petr.mus;;25, o.petr.mus;;26, o.petr.mus;;27, o.petr.mus;;28, o.petr.mus;;29, o.petr.mus;;30, o.petr.mus;;31](http://litpap.info/dclp/61028) 
[psi;13;1298, p.laur;4;130](http://litpap.info/dclp/61073) 
[p.bingen;;2, p.koeln;7;307](http://litpap.info/dclp/61230) 
[p.koeln;3;127, p.oxy;30;2512](http://litpap.info/dclp/61269) 
[o.petr.mus;;36, o.petr.mus;;37, o.petr.mus;;38, o.petr.mus;;42, o.petr.mus;;44, o.petr.mus;;50](http://litpap.info/dclp/61309) 
[p.bodm;;10, p.bodm;;13](http://litpap.info/dclp/61420) 
[p.oxy;4;668, psi;12;1291](http://litpap.info/dclp/61429) 
[psicongr;13;4, p.pisalit;;25, p.palaurib.lit;;14, p.palaurib.lit;;13, p.palaurib.lit;;16](http://litpap.info/dclp/61458) 
[p.oxy;10;1238, p.oxy;45;3217](http://litpap.info/dclp/61466) 
[p.oxy;3;409, p.oxy;33;2655](http://litpap.info/dclp/61505) 
[p.oxy;4;678, p.oxy;62;4302](http://litpap.info/dclp/61515) 
[p.oxy;22;2329, p.oxy;79;5186](http://litpap.info/dclp/61520) 
[p.koeln;5;203, p.koeln;6;243](http://litpap.info/dclp/61583) 
[p.bodm;;4, p.koeln;8;331, p.bodm;;25, p.bodm;;26](http://litpap.info/dclp/61594) 
[p.lond.lit;;142, p.oxy;56;3830](http://litpap.info/dclp/61608) 
[p.oxy;2;208, p.oxy;15;1781](http://litpap.info/dclp/61630) 
[o.petr.mus;;13, o.petr.mus;;15, o.petr.mus;;16](http://litpap.info/dclp/61646) 
[mpern.s;4;39, mpern.s;29;7](http://litpap.info/dclp/61721) 
[p.rain.unterrichtkopt;;248, p.rain.unterrichtkopt;;235](http://litpap.info/dclp/61737) 
[p.oxy;34;2683, p.oxy;64;4405](http://litpap.info/dclp/61784) 
[p.naqlun;2;16, p.naqlun;2;17](http://litpap.info/dclp/61815) 
[p.oxy;7;1008, p.oxy;7;1009](http://litpap.info/dclp/61859) 
[p.oxy;4;657, psi;12;1292](http://litpap.info/dclp/61861) 
[p.mil.vogl;2;45, p.mil.vogl;6;262](http://litpap.info/dclp/61915) 
[p.oxy;19;2221, p.koeln;5;206](http://litpap.info/dclp/61916) 
[p.rain.cent;;26, p.schoyen;1;18](http://litpap.info/dclp/62054) 
[o.crum;;512, p.rain.unterrichtkopt;;240](http://litpap.info/dclp/62144) 
[p.bad;5;127, p.bad;4;65](http://litpap.info/dclp/62265) 
[p.lond.lit;;207, p.lond.lit;;255](http://litpap.info/dclp/62310) 
[p.amh;1;3, p.amh;1;3](http://litpap.info/dclp/62312) 
[p.lond.copt;;48, p.lond.copt;;55](http://litpap.info/dclp/62323) 
[p.palaurib.lit;;5, p.palaurib.lit;;3](http://litpap.info/dclp/62327) 
[psi;11;1207, p.oxy;9;1173, p.oxy;11;1356](http://litpap.info/dclp/62375) 
[p.oxy;26;2442, p.oxy;75;5039](http://litpap.info/dclp/62564) 
[psi;11;1200, psicongr;13;9](http://litpap.info/dclp/62586) 
[p.oslo;2;9, psi;15;1484, p.oxy;76;5092](http://litpap.info/dclp/62593) 
[p.oxy;52;3671, p.oxy;76;5087](http://litpap.info/dclp/62599) 
[p.oxy;9;1174, p.oxy;17;2081](http://litpap.info/dclp/62741) 
[p.oxy;9;1175, p.oxy;17;2081](http://litpap.info/dclp/62742) 
[p.oxy;18;2180, psi;11;1192](http://litpap.info/dclp/62746) 
[p.hib;1;11, p.grenf;2;6](http://litpap.info/dclp/62769) 
[p.oxy;17;2100, p.oxy;57;3891, p.oxy;61;4109, psi;16;1587](http://litpap.info/dclp/62856) 
[p.oxy;57;3879, psi;16;1584](http://litpap.info/dclp/62867) 
[p.gen.horsserie;;2, p.ryl;3;548, p.oxy;49;3450, p.oxy;57;3885, p.koeln;7;304](http://litpap.info/dclp/62913) 
[psi;11;1197, p.oxy;2;226, psi;16;1593](http://litpap.info/dclp/62978) 
[psi;11;1196, psi;15;1485](http://litpap.info/dclp/62983) 
[p.fay.copt;;9, p.lond.copt;;515](http://litpap.info/dclp/63032) 
[p.ryl;1;22, p.yale;2;110](http://litpap.info/dclp/63125) 
[p.oxy;19;2221, p.koeln;5;206](http://litpap.info/dclp/63183) 
[p.rain.unterricht;;7, p.rain.unterricht;;8, p.rain.unterricht;;10, p.rain.unterricht;;179](http://litpap.info/dclp/63194) 
[p.lond.lit;;140, psi;2;148](http://litpap.info/dclp/63515) 
[pgm.2;2;72, pgm.2;2;57](http://litpap.info/dclp/63589) 
[chla;1;10, chla;1;11](http://litpap.info/dclp/63821) 
[p.oxy;15;1802, p.oxy;71;4812](http://litpap.info/dclp/63877) 
[p.oxy;15;1800, p.oxy;17;2081](http://litpap.info/dclp/63888) 
[sb;14;11708, o.bodl;2;2182](http://litpap.info/dclp/63912) 
[sb;14;12086, p.princ;3;155](http://litpap.info/dclp/63920) 
[p.oxy;49;3456, p.oxy;1;9](http://litpap.info/dclp/64289) 
[sb;22;15233, sb;22;15232](http://litpap.info/dclp/64384) 
[p.brookl;;30, p.brookl;;31](http://litpap.info/dclp/64391) 
[psi;1;26, psi;1;27](http://litpap.info/dclp/64723) 
[p.aphrod.lit;;14, p.aphrod.lit;;15, p.aphrod.lit;;21](http://litpap.info/dclp/65002) 
[p.aphrod.lit;;12, p.aphrod.lit;;23](http://litpap.info/dclp/65003) 
[p.aphrod.lit;;8, p.aphrod.lit;;9](http://litpap.info/dclp/65010) 
[p.aphrod.lit;;28, p.aphrod.lit;;43](http://litpap.info/dclp/65011) 
[p.aphrod.lit;;7, p.aphrod.lit;;42](http://litpap.info/dclp/65014) 
[p.mon.epiph;;617, p.rain.unterrichtkopt;;250](http://litpap.info/dclp/65158) 
[p.mon.epiph;;592, p.mon.epiph;;49](http://litpap.info/dclp/65174) 
[p.koeln;7;324, p.koeln;7;325, p.koeln;7;326, p.koeln;7;326](http://litpap.info/dclp/65187) 
[p.mon.epiph;;621, p.rain.unterrichtkopt;;247](http://litpap.info/dclp/65225) 
[p.ryl;1;39, p.grenf;2;7, p.hib;2;190](http://litpap.info/dclp/65755) 
[p.oxy;63;4400, p.oxy;63;4400](http://litpap.info/dclp/65840) 
[sb;20;14302, sb;20;15179](http://litpap.info/dclp/65842) 
[suppl.mag;2;74, suppl.mag;2;75](http://litpap.info/dclp/65844) 
[p.oxy;66;4511, p.oxy;79;5196](http://litpap.info/dclp/65909) 
[p.oxy.astr;2;4151, p.oxy.astr;2;4164](http://litpap.info/dclp/65945) 
[p.oxy.astr;2;4230, p.oxy.astr;2;4230](http://litpap.info/dclp/66043) 
[bgu;2;611, chla;10;418](http://litpap.info/dclp/66432) 
[p.aphrod.lit;;44, p.aphrod.lit;;45](http://litpap.info/dclp/66624) 
[cla;6;743, cla;8;1130](http://litpap.info/dclp/66913) 
[sb;26;16688, sb;26;16689](http://litpap.info/dclp/68656) 
[o.petr.mus;;40, o.petr.mus;;41, o.petr.mus;;43, o.petr.mus;;45, o.petr.mus;;46, o.petr.mus;;48, o.petr.mus;;49, o.petr.mus;;47](http://litpap.info/dclp/68816) 
[o.petr.mus;;4, o.petr.mus;;5, o.petr.mus;;6, o.petr.mus;;7](http://litpap.info/dclp/68817) 
[o.petr.mus;;1, o.petr.mus;;9, o.petr.mus;;10](http://litpap.info/dclp/68819) 
[o.petr.mus;;11, o.petr.mus;;12](http://litpap.info/dclp/68820) 
[psi;15;1498, p.oxy;68;4654](http://litpap.info/dclp/68959) 
[p.koeln;11;429, p.koeln;11;430](http://litpap.info/dclp/68983) 
[p.lond.copt;;94, p.lond.copt;;82](http://litpap.info/dclp/69673) 
[sb;22;15203, sb;22;15204](http://litpap.info/dclp/78911) 
[o.crum;;469, p.rain.unterrichtkopt;;253](http://litpap.info/dclp/83358) 
[p.rain.unterrichtkopt;;283, o.vind.copt;;16](http://litpap.info/dclp/83697) 
[p.rain.unterrichtkopt;;305, p.rain.unterrichtkopt;;290](http://litpap.info/dclp/85073)

**Comment by Edelweiss** [comment]
Files can be viewed on github and will be picked up with the next sync.
