### ISSUE TITLE
No top-level edit bar tabs for DCLPTextIdentifier or DCLPMetaIdentifier

### ISSUE THREAD

**Issue by ryanfb** [DCLP/dclpxsltbox#321]
In: https://github.com/dclp/sosol/blob/master/app/views/identifiers/_edit_bar.haml

For e.g. litpap.info/dclp/61246 I see:
![screen shot 2017-08-22 at 1 05 02 pm](https://user-images.githubusercontent.com/19781/29577769-a5b6a9e0-873a-11e7-92cd-4d45d4eded3b.png)

I would expect tabs next to "Overview" that say "DCLP Meta" and "DCLP Text".

There's a sub-menu for edit/commentary/xml/preview if you're already within a DCLPTextIdentifier, but no top-level tabs (in the `#identifier_menu ul`) like there are for DDBIdentifier/HGVMetaIdentifier/APISIdentifier/HGVTransIdentifier/BiblioIdentifier.

See #315 for the related issue of sub-menu tab names.

**Comment by paregorios** [comment]
cc @jcowey

**Comment by Edelweiss** [comment]
https://github.com/DCLP/sosol/commit/c56ea643d1f1c2fcc611f5fa6fd27f443d0f8a5a

**Comment by jcowey** [comment]
Not working for me:
http://litpap.info/editor/publications/1242/dclp_text_identifiers/2566/edit


![bildschirmfoto 2018-02-13 um 21 58 23](https://user-images.githubusercontent.com/612992/36173359-11f219de-1109-11e8-916a-4c6f9aea12dc.png)

**Comment by Edelweiss** [comment]
Derzeit nur auf [Test](http://dclp-test.zaw.uni-heidelberg.de)

**Comment by jcowey** [comment]
This now looks fine.
