### ISSUE TITLE
XSLT for navigator and epidoc-xslt does not handle biblScope@unit

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#325]
We made a decision long ago with DCLP to come forward into the light of more recent TEI releases than DDBDP, and we have recently undertaken to police compliance with that decision (#312). One consequence is that we must comply with [the now-three-year-old decision by the TEI](http://tei-l.970651.n3.nabble.com/Removal-of-biblScope-type-from-the-next-TEI-release-td4026741.html) to get rid of the ```type``` attribute on the ```<biblScope>``` element and replace it with a ```unit``` attribute. We've bumped into that issue a couple of times (#182 and #262), but with #312 should have universal conformance to the decision.

DDDBDP and HGV have **not** been similarly renovated.

It appears that XSLT for navigator and epidoc-xslt **only** interact well with the old-style use of the ```type``` attribute on ```<biblScope>```. I grepped for "biblScope" in all XSL files in the epidoc-xslt repos and in the navigator/pn-xslt and then grepped in those results for "unit." I got zero hits.

We must retain all tests that depend on ```biblScope@type``` (because otherwise we'll break DDBDP and HGV), but we also must add logically equivalent tests of ```biblScope@unit``` in order to deal properly with DCLP.

I'm working on this now.

NB: this ticket is a blocker for resolving XSLT aspects of #309, but it needs to be done even if we decide to defer #309 .

**Comment by jcowey** [comment]
There is an issue from nearly two years ago, in which the @unit / @type on biblScope was flagged: https://github.com/papyri/idp.data/issues/9.

Carmen and I did go through the data in HGV and Biblio, but never got everything together in order to push for an upgrade of the XML in papyri.info. This is still something we would like to attend to sooner rather than later.

**Comment by paregorios** [comment]
The following files are possibly affected:

```
navigator/pn-xslt/htm-teibibl.xsl
navigator/pn-xslt/idgSolr.xsl
navigator/pn-xslt/MakeSolr.xsl
navigator/pn-xslt/metadata.xsl
epidoc-xslt/htm-tpl-metadata.xsl
epidoc-xslt/odf-tpl-metadata.xsl
```
