### ISSUE TITLE
Add schema 8.23 to preprocess.xml

### ISSUE THREAD

**Issue by Edelweiss** [DCLP/dclpxsltbox#333]
DCLP Text identifiers should use the same preprocess.xml as DDB, or the transformation rules from DDB’s preprocess.xsl musst be copied over to whatever file DCLP Text is using.

**preprocess.xsl XSLT for DDB, HGV and DCLPMeta**
- https://github.com/DCLP/sosol/blob/development/data/xslt/ddb/preprocess.xsl#L110
- https://github.com/DCLP/sosol/blob/development/data/xslt/metadata/preprocess.xsl#L19

**path to preprocess.xsl for DCLPText and DCLPMeta**
- https://github.com/DCLP/sosol/blob/development/app/models/dclp_text_identifier.rb#L102
- https://github.com/DCLP/sosol/blob/development/app/models/hgv_meta_identifier.rb#L89

**Comment by Edelweiss** [comment]
https://github.com/DCLP/sosol/commit/738085a0e6acf504cec65e9c2b8d7bf447144b5c

**Comment by Edelweiss** [comment]
@ryanfb, @paregorios, @jcowey, @m-k-r could you please review the changes made in the commit above as to whether they are necessary and valid. I think if they don’t break anything they should be comprised in the version for the new server.

**Comment by ryanfb** [comment]
The changes seem OK from the DDB side. I ran the resulting `preprocess.xsl` across DCLP/idp.data/DCLP with:

     find DCLP -type d | parallel --bar -j8 -u 'mkdir -p /Users/ryan/mess/current/dclp_preprocess/{}; java  -jar ~/source/dc3/dclp/sosol/lib/java/saxon9he.jar -xsl:/Users/ryan/source/dc3/dclp/sosol/data/xslt/ddb/preprocess.xsl -s:{} -o:/Users/ryan/mess/current/dclp_preprocess/{}' 

The resulting diff is here: https://gist.github.com/ryanfb/c4bd5428ea858c23dfaf034fd4b08871

Most changes seem to be small whitespace modifications, moving/adding an empty `<div type="edition">` so it comes right after `<body>`, stripping `<!-- comments -->`, and updating `<langUsage>`

**Comment by paregorios** [comment]
I don't see any problems from my end.
