### ISSUE TITLE
More DCLP-hybrid problems

### ISSUE THREAD

**Issue by hcayless** [DCLP/dclpxsltbox#336]
This has surfaced in a couple of places already, but DCLP seems to have a habit of treating unpublished papyri in their IDs as though they had been published. This causes problems when you have a series with volumes (e.g. P.Gen.) and then DCLP documents are treated as though they belong directly to the series, with ids like `<series>;;<inventory no>`, instead of `<series>;<volume>;<item no>`. This surfaced this morning as I was working on deploying to Atlantides.

If it's a requirement that these sorts of ids be allowed, I can probably make it work, but it seems like an error to me. The affected files in this case are:

http://litpap.info/dclp/100162
http://litpap.info/dclp/131590
http://litpap.info/dclp/100161
http://litpap.info/dclp/154298
http://litpap.info/dclp/154297
http://litpap.info/dclp/131593

**Comment by jcowey** [comment]
@hcayless 

In the case of
http://litpap.info/dclp/100162
is the section
https://github.com/DCLP/idp.data/blob/master/DCLP/101/100162.xml#L80-L88

```
<div type="bibliography" subtype="principalEdition">
   <listBibl>
      <bibl type="publication" subtype="principal">
         <title level="s" type="abbreviated">P. Gen.</title>
         <biblScope unit="numbers">208</biblScope>
         <biblScope unit="generic">ined.</biblScope>
      </bibl>
   </listBibl>
</div>

```

the part that is causing trouble for you? 
Or is it the dclp-hybrid at
https://github.com/DCLP/idp.data/blob/master/DCLP/101/100162.xml#L15

`<idno type="dclp-hybrid">p.gen;;208</idno>`

Or both?

Both are unsatisfactory. 

I would however be very happy to delete the dclp-hybrid and replace it with the relevant

`<idno type="dclp-hybrid">na;;\d+</idno>`

value

**Comment by rogerbagnall** [comment]
I'm getting nothing but 404 error messages when I try to look at these. I can understand why people would use inventory numbers this way, in the absence of a volume and serial number reference, and no literary equivalent to SB, but I think it would be better to replace these with the publication information, like journal citation.

**Comment by Edelweiss** [comment]
In DCLP, there are 90 bibliographic records that come along with the information ‘ined.’ (that is, ```<biblScope unit="generic">ined.</biblScope>``` or ```<biblScope unit="generic">ined.?</biblScope>``` or ```<biblScope unit="generic">qua ined.</biblScope>```)

https://github.com/DCLP/idp.data/blob/master/DCLP/57/56179.xml#L100
https://github.com/DCLP/idp.data/blob/master/DCLP/63/62317.xml#L86
https://github.com/DCLP/idp.data/blob/master/DCLP/64/63022.xml#L84
https://github.com/DCLP/idp.data/blob/master/DCLP/64/63023.xml#L84
https://github.com/DCLP/idp.data/blob/master/DCLP/64/63024.xml#L84
https://github.com/DCLP/idp.data/blob/master/DCLP/64/63033.xml#L86
https://github.com/DCLP/idp.data/blob/master/DCLP/64/63234.xml#L82
https://github.com/DCLP/idp.data/blob/master/DCLP/64/63235.xml#L84
https://github.com/DCLP/idp.data/blob/master/DCLP/64/63236.xml#L84
https://github.com/DCLP/idp.data/blob/master/DCLP/64/63429.xml#L86
https://github.com/DCLP/idp.data/blob/master/DCLP/64/63430.xml#L84
https://github.com/DCLP/idp.data/blob/master/DCLP/64/63431.xml#L83
https://github.com/DCLP/idp.data/blob/master/DCLP/64/63432.xml#L82
https://github.com/DCLP/idp.data/blob/master/DCLP/64/63433.xml#L88
https://github.com/DCLP/idp.data/blob/master/DCLP/64/63434.xml#L83
https://github.com/DCLP/idp.data/blob/master/DCLP/64/63436.xml#L85
https://github.com/DCLP/idp.data/blob/master/DCLP/64/63437.xml#L86
https://github.com/DCLP/idp.data/blob/master/DCLP/64/63438.xml#L85
https://github.com/DCLP/idp.data/blob/master/DCLP/64/63439.xml#L84
https://github.com/DCLP/idp.data/blob/master/DCLP/64/63440.xml#L84
https://github.com/DCLP/idp.data/blob/master/DCLP/64/63441.xml#L85
https://github.com/DCLP/idp.data/blob/master/DCLP/64/63442.xml#L85
https://github.com/DCLP/idp.data/blob/master/DCLP/64/63795.xml#L82
https://github.com/DCLP/idp.data/blob/master/DCLP/64/63796.xml#L82
https://github.com/DCLP/idp.data/blob/master/DCLP/65/64012.xml#L85
https://github.com/DCLP/idp.data/blob/master/DCLP/65/64401.xml#L82
https://github.com/DCLP/idp.data/blob/master/DCLP/65/64402.xml#L93
https://github.com/DCLP/idp.data/blob/master/DCLP/65/64404.xml#L90
https://github.com/DCLP/idp.data/blob/master/DCLP/65/64405.xml#L82
https://github.com/DCLP/idp.data/blob/master/DCLP/65/64710.xml#L82
https://github.com/DCLP/idp.data/blob/master/DCLP/65/64711.xml#L88
https://github.com/DCLP/idp.data/blob/master/DCLP/65/64712.xml#L88
https://github.com/DCLP/idp.data/blob/master/DCLP/65/64715.xml#L85
https://github.com/DCLP/idp.data/blob/master/DCLP/66/65024.xml#L82
https://github.com/DCLP/idp.data/blob/master/DCLP/66/65025.xml#L86
https://github.com/DCLP/idp.data/blob/master/DCLP/66/65026.xml#L82
https://github.com/DCLP/idp.data/blob/master/DCLP/66/65027.xml#L86
https://github.com/DCLP/idp.data/blob/master/DCLP/66/65177.xml#L90
https://github.com/DCLP/idp.data/blob/master/DCLP/66/65178.xml#L90
https://github.com/DCLP/idp.data/blob/master/DCLP/66/65314.xml#L86
https://github.com/DCLP/idp.data/blob/master/DCLP/66/65521.xml#L87
https://github.com/DCLP/idp.data/blob/master/DCLP/66/65565.xml#L85
https://github.com/DCLP/idp.data/blob/master/DCLP/66/65648.xml#L86
https://github.com/DCLP/idp.data/blob/master/DCLP/66/65694.xml#L84
https://github.com/DCLP/idp.data/blob/master/DCLP/69/68762.xml#L90
https://github.com/DCLP/idp.data/blob/master/DCLP/69/68763.xml#L91
https://github.com/DCLP/idp.data/blob/master/DCLP/69/68764.xml#L90
https://github.com/DCLP/idp.data/blob/master/DCLP/69/68765.xml#L93
https://github.com/DCLP/idp.data/blob/master/DCLP/69/68766.xml#L91
https://github.com/DCLP/idp.data/blob/master/DCLP/69/68767.xml#L91
https://github.com/DCLP/idp.data/blob/master/DCLP/69/68828.xml#L90
https://github.com/DCLP/idp.data/blob/master/DCLP/69/68829.xml#L90
https://github.com/DCLP/idp.data/blob/master/DCLP/69/68830.xml#L90
https://github.com/DCLP/idp.data/blob/master/DCLP/69/68831.xml#L90
https://github.com/DCLP/idp.data/blob/master/DCLP/69/68832.xml#L86
https://github.com/DCLP/idp.data/blob/master/DCLP/70/69057.xml#L87
https://github.com/DCLP/idp.data/blob/master/DCLP/70/69159.xml#L92
https://github.com/DCLP/idp.data/blob/master/DCLP/70/69160.xml#L95
https://github.com/DCLP/idp.data/blob/master/DCLP/92/91340.xml#L92
https://github.com/DCLP/idp.data/blob/master/DCLP/92/91580.xml#L84
https://github.com/DCLP/idp.data/blob/master/DCLP/94/93273.xml#L93
https://github.com/DCLP/idp.data/blob/master/DCLP/94/93278.xml#L90
https://github.com/DCLP/idp.data/blob/master/DCLP/101/100160.xml#L85
https://github.com/DCLP/idp.data/blob/master/DCLP/101/100161.xml#L90
https://github.com/DCLP/idp.data/blob/master/DCLP/101/100162.xml#L85
https://github.com/DCLP/idp.data/blob/master/DCLP/103/102233.xml#L95
https://github.com/DCLP/idp.data/blob/master/DCLP/103/102234.xml#L92
https://github.com/DCLP/idp.data/blob/master/DCLP/103/102243.xml#L86
https://github.com/DCLP/idp.data/blob/master/DCLP/103/102244.xml#L84
https://github.com/DCLP/idp.data/blob/master/DCLP/108/107960.xml#L87
https://github.com/DCLP/idp.data/blob/master/DCLP/108/107987.xml#L91
https://github.com/DCLP/idp.data/blob/master/DCLP/109/108133.xml#L84
https://github.com/DCLP/idp.data/blob/master/DCLP/109/108411.xml#L95
https://github.com/DCLP/idp.data/blob/master/DCLP/109/108605.xml#L95
https://github.com/DCLP/idp.data/blob/master/DCLP/109/108612.xml#L90
https://github.com/DCLP/idp.data/blob/master/DCLP/109/108615.xml#L90
https://github.com/DCLP/idp.data/blob/master/DCLP/109/108616.xml#L91
https://github.com/DCLP/idp.data/blob/master/DCLP/110/109317.xml#L91
https://github.com/DCLP/idp.data/blob/master/DCLP/112/111352.xml#L86
https://github.com/DCLP/idp.data/blob/master/DCLP/113/112402.xml#L92
https://github.com/DCLP/idp.data/blob/master/DCLP/113/112403.xml#L89
https://github.com/DCLP/idp.data/blob/master/DCLP/113/112404.xml#L88
https://github.com/DCLP/idp.data/blob/master/DCLP/132/131590.xml#L89
https://github.com/DCLP/idp.data/blob/master/DCLP/132/131593.xml#L95
https://github.com/DCLP/idp.data/blob/master/DCLP/144/143378.xml#L100
https://github.com/DCLP/idp.data/blob/master/DCLP/144/143378.xml#L107
https://github.com/DCLP/idp.data/blob/master/DCLP/155/154297.xml#L91
https://github.com/DCLP/idp.data/blob/master/DCLP/155/154298.xml#L85
https://github.com/DCLP/idp.data/blob/master/DCLP/218/217927.xml#L96
https://github.com/DCLP/idp.data/blob/master/DCLP/245/244005.xml#L90

**Comment by Edelweiss** [comment]
https://github.com/DCLP/idp.data/commit/d2e8d5707c19c1ea7a8ab7f8bce664c12d4cc82f

**Comment by jcowey** [comment]
Spoke with @hcayless about this.
Agreed to change the dclp-hybrid from

`<idno type="dclp-hybrid">p.gen;;208</idno>`

to

`<idno type="dclp-hybrid">na;;100162</idno>`

as suggested in the comment from 1 sept.

Also got rid of the bibliographic reference in

https://github.com/DCLP/idp.data/blob/master/DCLP/101/100162.xml#L80-L88

which made no sense.

The above commit should now be merged to master and the issue can be closed

**Comment by Edelweiss** [comment]
https://github.com/DCLP/idp.data/commits/master
