### ISSUE TITLE
DCLP XML files need appropriate copyright and license statements encoded in them

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#34]
Compare DDB texts, e.g., https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/bgu/bgu.1/bgu.1.10.xml#L16

**Comment by paregorios** [comment]
Hi @rla2118 what would you like to do about this issue?

**Comment by rla2118** [comment]
Add copyright and license statements, as in DDbDP.

**Comment by paregorios** [comment]
This is probably a job for a modified unity transform to be run across all XML. But whatever template or code the Heidelberg crosswlak uses should probably be updated to match. Does that make sense @jcowey and @Edelweiss ? If you two are OK with this, then we can assign @cgajjar05 to implement. I'm taking back ownership of this ticket pending that decision.

**Comment by paregorios** [comment]
I don't have a record of @jcowey or @Edelweiss commenting on this. Assigning to @jcowey to get his opinion.

**Comment by Edelweiss** [comment]
I don't think there is such a thing as a »Heidelberg xwalk« any more. There are just zillions of xslt files, each designed for a very specific purpose, such as »xwalk stuff from herculaneum« or »insert bibliographic information«.

However, in order to be on the safe side I added a code fragment to all the files dealing with the publicationStmt that, if they should ever be called to action again, they will fail with a command line message that will tell my future self to revisit this ticket.

Sth. like

<xsl:message terminate="yes">This section might need to be updated according to ticket https://github.com/DCLP/dclpxsltbox/issues/34</xsl:message>

Thank you for pointing our attention to this issue!

**Comment by jcowey** [comment]
When added #108 will no longer be a problem.

**Comment by paregorios** [comment]
per @rla2118 via email, we are go for CC

**Comment by paregorios** [comment]
@jcowey given #108 is this issue now resolved?

**Comment by paregorios** [comment]
reassigned to @Edelweiss per discussion in weekly call on 9 November

**Comment by jcowey** [comment]
We have authority statements throughout the corpus (otherwise the files would not validate)
here is an example:
https://github.com/DCLP/idp.data/blob/dclp/DCLP/109/108003.xml#L9-L10
```
<publicationStmt>
   <authority>Digital Corpus of Literary Papyri</authority>
```

**Comment by paregorios** [comment]
So, will everyone be happy if that is the only thing that surfaces (i.e., without any explicit mention of copyright or license)?

**Comment by jcowey** [comment]
What we need to add is the licensing info in the `<availability>` tag
```
<availability>
      <p>© Digital Corpus of Literary Papyri. This work is licensed under a <ref type="license" target="http://creativecommons.org/licenses/by/3.0/">Creative Commons Attribution 3.0 License</ref>.</p>
</availability>
```
which has to be added just before the closing `<publicationStmt>`tag
for example
https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/bgu/bgu.1/bgu.1.2.xml#L19-L21

```
<publicationStmt>
   <authority>Duke Collaboratory for Classics Computing (DC3)</authority>
   <idno type="filename">bgu.1.2</idno>
   <idno type="ddb-perseus-style">0001;1;2</idno>
   <idno type="ddb-hybrid">bgu;1;2</idno>
   <idno type="HGV">8961</idno>
   <idno type="TM">8961</idno>
   <availability>
      <p>© Duke Databank of Documentary Papyri. This work is licensed under a <ref type="license" target="http://creativecommons.org/licenses/by/3.0/">Creative Commons Attribution 3.0 License</ref>.</p>
   </availability>
</publicationStmt>
```

**Comment by Edelweiss** [comment]
[add licensing information](https://github.com/DCLP/idp.data/commit/9817d514b3c8d2308a33ed533eb777defb9ce639)

The one ‘line deleted’ comes from file [102801.xml](https://github.com/DCLP/idp.data/blob/dclp/DCLP/103/102801.xml)

something to do with the closing tag of the publication statement
```
</publicationStmt>
```

**Comment by jcowey** [comment]
OK. This should be solved once and for all now.
