### ISSUE TITLE
SoSOL editor: bibliography, line separators

### ISSUE THREAD

**Issue by Edelweiss** [DCLP/dclpxsltbox#342]
Remove horizontal line above passage list, have instead a line above each biblio entry

![bildschirmfoto 2017-11-08 um 16 26 33](https://user-images.githubusercontent.com/612862/32557386-49245b50-c4a2-11e7-9807-86437420fbc9.png)

**Comment by jcowey** [comment]
If this one could be fitted in as well to those things that you are fixing that would be great

**Comment by Edelweiss** [comment]
https://github.com/DCLP/sosol/tree/issue342

https://github.com/DCLP/sosol/commit/92dbc9996eb2e636975da741b1ea3fa8e6d9a53e

(merged to development and master)

**Comment by Edelweiss** [comment]
now available for testing on http://dclp-test.zaw.uni-heidelberg.de
