### ISSUE TITLE
Add new editor field »LDAB«

### ISSUE THREAD

**Issue by Edelweiss** [DCLP/dclpxsltbox#350]
Just where to place it? Perhaps under »Editions & Bibliography« alongside »TM-No.«, or under »General Notes« where »MP3« is residing?

**Comment by Edelweiss** [comment]
in issue branch and development branch

[issue50](https://github.com/DCLP/sosol/commits/issue350)

**Comment by rla2118** [comment]
I would say next to the TM no.
