### ISSUE TITLE
g-type *apostrophe* is not getting picked up by the XSLT

### ISSUE THREAD

**Issue by Edelweiss** [DCLP/dclpxsltbox#352]
@rla2118 in an e-mail
> I also discovered something minor that I want to report, in case it was not noticed before. The g-type *apostrophe* is not getting picked up by the XSLT.  Instead of an apostrophe, which is what we expect to see, nothing is displaying.

**Comment by paregorios** [comment]
I remember a long discussion about this and associated encoding issues. I'll try to dig it up and reconcile with what you're seeing here. @rla2118 can you give us a link to one or more texts where you're not seeing the behavior you expect?

**Comment by paregorios** [comment]
The previous thread was on #63, which was closed as resolved.

**Comment by Edelweiss** [comment]
http://litpap.info/dclp/59814

It seems to work here.
