### ISSUE TITLE
Insert appropriate nome name in relevant files

### ISSUE THREAD

**Issue by jcowey** [DCLP/dclpxsltbox#366]
The tag
`<placeName type="ancient" subtype="nome">U</placeName>`

must be replaced with the relevant one. All that we have is the above tag. This is a result of the data we received.

**Comment by Edelweiss** [comment]
There are 6438 files containing this kind of information.

Examples

Pathyris
https://github.com/DCLP/idp.data/blob/master/DCLP/1/555.xml#L46

Oxyrynchos
https://github.com/DCLP/idp.data/blob/master/DCLP/61/60066.xml#L46

Tentyris
https://github.com/DCLP/idp.data/blob/master/DCLP/99/98077.xml#L53

What should the placeholder »U« be replaced with?

**Comment by jcowey** [comment]
Would you please generate a distinct list of those placeNames which are siblings of 
`<placeName type="ancient" subtype="nome">U</placeName>` in a googlespreadsheet

**Comment by jcowey** [comment]
I generated a distinct list of `<placeName type="ancient" ref="[^<]+">[^<]+</placeName>` at 311, but many of those were not accompanied by `<placeName type="ancient" subtype="nome">U</placeName>`

**Comment by jcowey** [comment]
I would then fill in the relevant replacements for »U« 
On the basis of such a list you would then be able to change and replace in appropriate fashion.

**Comment by Edelweiss** [comment]
https://docs.google.com/spreadsheets/d/1uNsT53My4l0JdcE8jogBsqVZyYHjWsWuIw5Dh5GoCI0/edit?usp=sharing

**Comment by jcowey** [comment]
https://github.com/DCLP/idp.data/blob/master/DCLP/1/555.xml#L46-L48
now looks like 
```
   <placeName type="ancient" subtype="nome">U</placeName>
   <placeName type="ancient" subtype="region">Egypt</placeName>
   <placeName type="ancient" ref="http://www.trismegistos.org/place/1628">Pathyris</placeName>
```
should look be
```
   <placeName type="ancient" subtype="nome" ref="http://www.trismegistos.org/place/2849">Pathyrites</placeName>
   <placeName type="ancient" subtype="region">Egypt</placeName>
   <placeName type="ancient" ref="http://www.trismegistos.org/place/1628">Pathyris</placeName>
```

The same should of course be the case for
https://github.com/DCLP/idp.data/blob/master/DCLP/1/555.xml#L53-L55

https://github.com/DCLP/idp.data/blob/master/DCLP/1/555.xml#L41
now offers
```
<origPlace>Found: Pathyris (U, Egypt); written: Pathyris (U, Egypt)</origPlace>
```

It should be 
```
<origPlace>Found: Pathyris (Pathyrites, Egypt); written: Pathyris (Pathyrites, Egypt)</origPlace>
```

**Comment by jcowey** [comment]
https://github.com/DCLP/idp.data/blob/master/DCLP/61/60066.xml#L46-L48
offers
```
<placeName type="ancient" subtype="nome">U</placeName>
<placeName type="ancient" subtype="region">Egypt</placeName>
<placeName type="ancient" ref="http://www.trismegistos.org/place/1524">Oxyrynchos</placeName>
```


It should be
```
<placeName type="ancient" subtype="nome" ref="http://www.trismegistos.org/place/2722">Oxyrhynchites</placeName>
<placeName type="ancient" subtype="region">Egypt</placeName>
<placeName type="ancient" ref="http://www.trismegistos.org/place/1524">Oxyrhynchos</placeName>
```

Please note "Oxyrynchos" => "Oxyrhynchos"

https://github.com/DCLP/idp.data/blob/master/DCLP/61/60066.xml#L41
offers
```
<origPlace>Found: Oxyrynchos (U, Egypt); written: Egypt</origPlace>
```

it should be 
```
<origPlace>Found: Oxyrhynchos (Oxyrhynchites, Egypt); written: Egypt</origPlace>
```

**Comment by jcowey** [comment]
Please leave the purple ones

**Comment by Edelweiss** [comment]
Beispiele für verschiedene Schreib- und Fundorte

**/DCLP/109/108739.xml**

```xml
<history>
  <origin>
     <origPlace>Found: Apollonopolis (U, Egypt); written: Latopolis (U, Egypt)</origPlace>
     <origDate notBefore="0500" notAfter="0699">500 - 699</origDate>
  </origin>
  <provenance type="found">
     <p>
        <placeName type="ancient" subtype="nome">U</placeName>
        <placeName type="ancient" subtype="region">Egypt</placeName>
        <placeName type="ancient" ref="http://www.trismegistos.org/place/269">Apollonopolis</placeName>
     </p>
  </provenance>
  <provenance type="composed">
     <p>
        <placeName type="ancient" subtype="nome">U</placeName>
        <placeName type="ancient" subtype="region">Egypt</placeName>
        <placeName type="ancient" ref="http://www.trismegistos.org/place/1227">Latopolis</placeName>
     </p>
  </provenance>
</history>
```

Weitere Beispiele
--
http://www.trismegistos.org/place/269\|http://www.trismegistos.org/place/1227
http://www.trismegistos.org/place/471\|http://www.trismegistos.org/place/801
http://www.trismegistos.org/place/576\|http://www.trismegistos.org/place/1589
http://www.trismegistos.org/place/801\|http://www.trismegistos.org/place/801
http://www.trismegistos.org/place/816\|http://www.trismegistos.org/place/1298
http://www.trismegistos.org/place/816\|http://www.trismegistos.org/place/1524
http://www.trismegistos.org/place/816\|http://www.trismegistos.org/place/3017
http://www.trismegistos.org/place/952\|http://www.trismegistos.org/place/952
http://www.trismegistos.org/place/952\|http://www.trismegistos.org/place/2766
http://www.trismegistos.org/place/1524\|http://www.trismegistos.org/place/1271
http://www.trismegistos.org/place/1524\|http://www.trismegistos.org/place/2800
http://www.trismegistos.org/place/1589\|http://www.trismegistos.org/place/3121
http://www.trismegistos.org/place/1628\|http://www.trismegistos.org/place/2207
http://www.trismegistos.org/place/1628\|http://www.trismegistos.org/place/2766
http://www.trismegistos.org/place/2800\|http://www.trismegistos.org/place/3695
http://www.trismegistos.org/place/2843\|http://www.trismegistos.org/place/2800
http://www.trismegistos.org/place/3121\|http://www.trismegistos.org/place/2800
http://www.trismegistos.org/place/3695\|http://www.trismegistos.org/place/2800

**Comment by Edelweiss** [comment]
**Typen**

- Found|written
- Fundort|Schreibort
- Schreibort|Fundort

**Mapping auf die Datenelemente**

- Schreibort / written > composed
- Fundort / found > found

**Mögliche Kombinationen**

- found|composed
- composed|found

**Comment by Edelweiss** [comment]
https://github.com/DCLP/idp.data/commit/346523e9150aec4a620b7a4e23b438662455c387
https://github.com/DCLP/idp.data/commit/1a64dda73ef2ee0d0771361596eea978630443e0

Beispiele:


https://github.com/DCLP/idp.data/blob/master/DCLP/65/64487.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/66/65099.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/66/65067.xml
https://github.com/DCLP/idp.data/blob/master/DCLP/49/48854.xml

**Comment by jcowey** [comment]
Looks excellet thank you. 
Would you now please create another pass at the Sheet "X für ein U" in the spreadsheet DCLP Geo
https://docs.google.com/spreadsheets/d/1uNsT53My4l0JdcE8jogBsqVZyYHjWsWuIw5Dh5GoCI0/edit#gid=0

For the remaining cases of the use of "u" which you did not change because I was unsure of which nome was to be used.

Then I can go ahead and do the necessary work.
If you do a new read out it will probably simply corroborate the rows I have marked in purple, but it is probably worth doing a new read out.

**Comment by jcowey** [comment]
Thank you. I see that you have now marked rows 16, 18-19 and 21-23 as one which correspond the the purple I had in the previous version.

Are the ones you are marking with HTTPS ones you did not catch previously. I had been surprised to see them, because I thought they would have been dealt with anyway.

So a second read out was indeed a very useful check.

**Comment by jcowey** [comment]
Oh sorry, that was my fault. I had pasted a https URL and not cleaned it as I had done with the others

**Comment by Edelweiss** [comment]
Ja, absolut! Gute Idee… Danke! Uff, ich bin gerade am sondieren, warum manche aufgenommen wurden, von denen man es nicht erwartet hätte, und warum andere offenbar nicht gematcht wurden.

**Comment by Edelweiss** [comment]
Ja, das mit dem HTTP(S) ist wohl deswegen entstanden, weil die Daten in Spalte »place name« und »place ref« nur Beispiele waren. Das war etwas irreführend und mir später selbst nicht mehr bewusst.

**Comment by Edelweiss** [comment]
Frage: Sollen die refs alle einheitlich auf entweder HTTP oder HTTPS lauten? Als Vorab-Clean-Up.

**Comment by jcowey** [comment]
I think we should go for HTTPS. It is what the URL (e.g. www.trismegistos.org/place/1008) resolves to. And everything is moving towards HTTPS nowadays

**Comment by jcowey** [comment]
I feel sure it is not like that in papyri.info, but that would be easy to fix and is for another day.

**Comment by Edelweiss** [comment]
httpS

https://github.com/DCLP/idp.data/commit/1535ee172ae587fd01f32f98c6298775511c0d1f
https://github.com/DCLP/idp.data/commit/f115e30a28c961eaef15156f2233f4f128d8301d

X for U
https://github.com/DCLP/idp.data/commit/b10bffe80859b3672baf9b8688ef9247cc656e7d

X for U 2
https://github.com/DCLP/idp.data/commit/5f288c93fcb82998fcf6773c20b985a652edd801
https://github.com/DCLP/idp.data/commit/f59ecf977ff11ed627c1dbdd0a3c6681dbd121da
https://github.com/DCLP/idp.data/commit/e9665c4e63d102ce505c4904da1ef3c1a5f48132

Nome
https://github.com/DCLP/idp.data/commit/7b0f2dae08a4da4efaa0ce7ff07444adfdedf34c

Region
https://github.com/DCLP/idp.data/commit/80e4def813f94ec2fb7444513ea11c2bb86c99fe

X for U 3
https://github.com/DCLP/idp.data/commit/88a60f7571a1344348b58580e5758f2a638dce11

**Comment by Edelweiss** [comment]
Nach dem heutigen commit gibt es nun keine U-Orte mehr.

**Comment by jcowey** [comment]
Splendid.

**Comment by jcowey** [comment]
Closing this as completed
