### ISSUE TITLE
XML does not validate: no authority element in publicationStmt

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#48]
The TEI/EpiDoc schema requires an ```<authority>``` element inside ```<publicationStmt>``` before our series of ```<idno>``` elements, but we don't have one (this omission has long obtained in the HGV metadata as well, but that is outside our remit here). [According to the TEI Guidelines](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-authority.html), the ```<authority>``` element "supplies the name of a person or other agency responsible for making a work available, other than a publisher or distributor."

It would be trivial to add a standard authority statement to all our files, but we need to decide what it should say. I'm therefore assigning to @rla2118 for discussion.

**Comment by jcowey** [comment]
Now dealt with under #108.

**Comment by jcowey** [comment]
#108 now closed, so closing this one too!
