### ISSUE TITLE
invalid XML in <objectDesc>

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#50]
The recently implemented solution for more prosey object description was to introduce an initial typed paragraph for use in display and then to follow it with ```<supportDesc>``` etc. Here's an example:

```xml
<physDesc>
   <objectDesc form="roll">
      <p type="bookForm">papyrus roll (columns: 36, written lines: [34, 35])</p>
      <supportDesc>
         <support>
            <material>papyrus</material>
         </support>
      </supportDesc>
      <layoutDesc>
         <layout columns="36" writtenLines="[34, 35]"/>
      </layoutDesc>
   </objectDesc>
</physDesc>
```

Unfortunately, this example throws a number of validation errors against the EpiDoc schema, all of which are exemplary of similar problems across the entire dataset:

> attribute "type" not allowed on ```<p>```; expected attribute "ana", "change", "copyOf", "corresp", "decls", "exclude", "facs", "n", "next", "part", "prev", "rend", "rendition", "sameAs", "select", "style", "synch", "xml:base", "xml:id", "xml:lang" or "xml:space"
> element "supportDesc" not allowed here; expected the element end-tag or element "ab" or "p"
> element "layoutDesc" not allowed here; expected the element end-tag or element "ab" or "p"

We can probably easily find an alternative solution for using the ```type``` attribute on the ```<p>``` element, which is not allowed in TEI, but the bigger issue is the structural one: TEI expects us to use **either** a series of ```<p>``` or ```<ab>``` elements inside ```<objectDesc>``` **or** the more structural elements like ```<supportDesc>``` and ```<layoutDesc>```, not both.

Assigning it to myself to research an alternative.

**Comment by jcowey** [comment]
List of values for form:

codex
fragment
inscription
loose leaves, bound together
offsets
roll
sheet (sheer)
tablet
unknown
vessel

**Comment by jcowey** [comment]
In the example above:

> value of attribute "form" is invalid; must be an XML name

```XML
<objectDesc form="codex (1 fol.)">
   <p type="bookForm">papyrus codex (1 fol.) (columns: 2, written lines: 20)</p>
   <supportDesc>
      <support>
         <material>papyrus</material>
      </support>
   </supportDesc>
   <layoutDesc>
      <layout columns="2" writtenLines="20"/>
   </layoutDesc>
</objectDesc>
```
e.g. DCLP TM no. [99549](https://github.com/DCLP/idp.data/blob/dclp/DCLP/100/99549.xml)

clean up the values of form columns and written lines. On the basis that all the infomation is in the p tag.

It would now look like

> value of attribute "form" is invalid; must be an XML name

```XML
<objectDesc form="codex">
   <supportDesc>
      <support>
         <material>papyrus</material>
      </support>
   </supportDesc>
   <layoutDesc>
      <layout columns="2" writtenLines="20">
         <p>papyrus codex (1 fol.) (columns: 2, written lines: 20)</p>
      </layout>
   </layoutDesc>
</objectDesc>
```

**Comment by paregorios** [comment]
@jcowey so, do you think we're ready to implement then?

**Comment by jcowey** [comment]
These have been implemented in 
https://github.com/DCLP/idp.data/tree/hd
with the commit
https://github.com/DCLP/idp.data/commit/b2d37ab288441dc74f0cd44c856fbc72c9daa4b7

I would be happy to see this and the other commits 
https://github.com/DCLP/idp.data/commits/hd
of October 2015 folded into our dclp branch
https://github.com/DCLP/idp.data/tree/dclp
once you have had a look and found the changes acceptable.
You will notice that Carmen also added an Authority statement.
Once we make the facsimile commit (planned for Wednesday morning) the files should validate - a prerequisite for building the editor.
If anything else is unclear please let me know.

**Comment by paregorios** [comment]
The referenced commit has greatly improved validation performance and brought our content into a more standard TEI convention with regard to object and layout description; however, a number of validation errors relevant to these sections still seem to obtain. These are:

 * empty ```writtenLines``` attribute (only one case: [TM 102244](https://github.com/DCLP/idp.data/blob/hd/DCLP/103/102244.xml#L29))
 * invalid content in the ```writtenLines``` attribute (scores of cases, of which [TM 129686](https://github.com/DCLP/idp.data/blob/hd/DCLP/130/129686.xml#L28) is exemplary)
 * empty ```columns``` attribute (only one case: [TM 63817](https://github.com/DCLP/idp.data/blob/hd/DCLP/64/63817.xml#L29))
 * invalid content in the ```columns``` attribute (two cases: [TM 67268](https://github.com/DCLP/idp.data/blob/hd/DCLP/68/67268.xml#L28) and [98044](https://github.com/DCLP/idp.data/blob/hd/DCLP/99/98044.xml#L28))

**Comment by Edelweiss** [comment]
* [TM-No. 102244](https://github.com/DCLP/idp.data/blob/hd/DCLP/103/102244.xml#L29) (numbers separated by space for writtenLines)
* [TM-No. 67268](https://github.com/DCLP/idp.data/blob/hd/DCLP/68/67268.xml#L28) and [TM-No. 98044](https://github.com/DCLP/idp.data/blob/hd/DCLP/99/98044.xml#L28) (numbers separated by space for columns)

We didn’t take into account that TEI only allows up to two numbers that are separated by whitespace. We were mislead to believe the list could be infinite. We need a new and valid TEI solution for that.

For columns one solution could be to count the number of columns and write this calculated value instead.

1 2 3 4 would become 4
1 2 5 would become 3

For writtenLines: If an attribute contains more than two values we just keep the biggest and the smallest number in the order of their appearance within the original data.

* [TM-No. 129686](https://github.com/DCLP/idp.data/blob/hd/DCLP/130/129686.xml#L28) (empty writtenLines) This might be owing to a wrong entry in the database. I guess the value »sheet«, which we find for »nr_lines« here, should actually go to the database field »bookform«.
* [TM-No. 63817](https://github.com/DCLP/idp.data/blob/hd/DCLP/64/63817.xml#L29) Here the database entry for »columns« reads »"«.

**Comment by paregorios** [comment]
Sounds good to me!

**Comment by jcowey** [comment]
carry necessary fixes using script fix35

**Comment by Edelweiss** [comment]
[example file old](https://github.com/DCLP/idp.data/blob/dclp/DCLP/103/102244.xml#L23)
```
/TEI/teiHeader/fileDesc/sourceDesc/msDesc/physDesc/objectDesc/p[@type="bookForm"]
```
[example file new](https://github.com/DCLP/idp.data/blob/hd/DCLP/103/102244.xml#L23)
```
/TEI/teiHeader/fileDesc/sourceDesc/msDesc/physDesc/objectDesc/layoutDesc/layout/p
```

**Comment by paregorios** [comment]
[navigator/@81edcc1](https://github.com/DCLP/navigator/commit/81edcc1b4f16a7dba842cf44d001489e933a20cf) is an attempt to address this change. Note that underlying data in some cases may still leave something to be desired, but the files are all validating and that valid content is being serialized into the HTML. The following examples were considered in the preceding comments:

- [555](http://dclp.github.io/dclpxsltbox/output/dclp/1/555.html)
- [63817](http://dclp.github.io/dclpxsltbox/output/dclp/64/63817.html)
- [67268](http://dclp.github.io/dclpxsltbox/output/dclp/68/67268.html)
- [98044](http://dclp.github.io/dclpxsltbox/output/dclp/99/98044.html)
- [99549](http://dclp.github.io/dclpxsltbox/output/dclp/100/99549.html)
- [102244](http://dclp.github.io/dclpxsltbox/output/dclp/103/102244.html)
- [129686](http://dclp.github.io/dclpxsltbox/output/dclp/130/129686.html)

Over to @jcowey, @rla2118, and @HolgerEssler for review.
