### ISSUE TITLE
Collapsing Fragments Field

### ISSUE THREAD

**Issue by rla2118** [DCLP/dclpxsltbox#51]
Can we put Fragments in a collapsible window? It would make examples like this easier to ignore,
http://dclp.github.io/dclpxsltbox/output/dclp/63/62400.html, if one isn't interested in seeing all of the fragment info.

**Comment by HolgerEssler** [comment]
This should be resolved, once #26 is in place.

**Comment by paregorios** [comment]
Blocked by #26

**Comment by paregorios** [comment]
closing as duplicate for #26

**Comment by rla2118** [comment]
I would like to reopen this issue, because it never addressed the original desideratum:

Can we put Fragments in a collapsible window? It would make examples like this easier to ignore,
http://dclp.github.io/dclpxsltbox/output/dclp/63/62400.html, if one isn't interested in seeing all of the fragment info.

**Comment by paregorios** [comment]
Task:

 - [ ] consult with @hcayless on whether there is any current JavaScript in the build that we might be able to use for this purpose.

**Comment by wsalesky** [comment]
@paregorios 
Can't we just use a jquery toggle() function to show/hide this information?

**Comment by paregorios** [comment]
@wsalesky if you have an idea about how to implement (with jquery or otherwise) I'm happy to let you run with this one! :)

**Comment by wsalesky** [comment]
@paregorios 
Sure I can do that. The site already uses jquery, so a simple toggle should do the trick. 

@rla2118 
Can you clarify the behavior you would like to see?
i.e. would you like to see X number of fragments with 'Show all' button? 

Thanks!

**Comment by wsalesky** [comment]
@rla2118 
Can you clarify the behavior you would like to see?
i.e. would you like to see the first 3 number of fragments with 'Show all' button? Something else? 
Thank.

**Comment by paregorios** [comment]
cc @rogerbagnall

**Comment by rla2118** [comment]
Yes, something like that: the first few fragment numbers and then a "show
all" button, which when clicked would roll out all the other numbers.


2017-04-21 21:15 GMT+02:00 Tom Elliott <notifications@github.com>:

**Comment by wsalesky** [comment]
@paregorios where do I make changes to javascript or css files?

**Comment by paregorios** [comment]
@wsalesky I assume that's somewhere in DCLP/navigator repos ... like subdirectories here: https://github.com/DCLP/navigator/tree/master/pn-site

Maybe also @hcayless and/or @ryanfb can provide some guidance ...

**Comment by wsalesky** [comment]
@paregorios That looks right to me. Thanks.

**Comment by wsalesky** [comment]
@paregorios @rla2118  
Ready for review. 

Added a toggle function for records with more then 10 fragments in metadata display. 
**XSLT:** pn-xslt/metadata-dclp.xsl

**New branch:** https://github.com/DCLP/navigator/tree/issue51

**Comment by rla2118** [comment]
@paregorios I'm sorry, but I don't understand where I should look if I want to review this.

**Comment by paregorios** [comment]
@rla2118 I'll alert you when I've posted versions for your review.

**Comment by paregorios** [comment]
@wsalesky this is slick. Is it possible (without too much work) to tweak as follows?

1. Add ellipsis (...) before the ```<span id="fragmentsMetadata">``` when toggle is in the more abbreviated setting (i.e., ```<span id="fragmentsMetadata" style="display: none">```), but don't add it when all fragments are shown. 

2. When all fragments are shown, avoid introducing a line break before ```<span id="fragmentsMetadata">```. I think this happens because ```@style="display``` gets set to ```inline-block```.

**Comment by paregorios** [comment]
NB: I have rebased the issue51 branch against master, so you'll want to do a pull on it.

**Comment by wsalesky** [comment]
Okay, I changed the slideToggle() function to a plain toggle(), less fancy but also less buggy. (https://github.com/jquery/jquery/issues/2071) If you want the fancy animation I can add it back in, it will require slightly more involved JavaScript. 

Also added an ellipsis '..' that should toggle with the fragments.
