### ISSUE TITLE
Change representation in XSLT for "Stigmai"

### ISSUE THREAD

**Issue by cgajjar05** [DCLP/dclpxsltbox#67]
Create or change representation in preview (XSLT) for "Stigmai".

**Comment by paregorios** [comment]
The LitPapText spreadsheet indicates that encodings like the following "work", producing the corresponding outputs. 

```xml
<g type="ano-stigme"/>
<g type="kato-stigme"/>
<g type="mese-stigme"/>
```

```
((ano-stigme))
((kato-stigme))
((mese-stigme))
```

The spreadsheet seems to imagine that somehow this presentation should be altered. @rla2118 @jcowey @HolgerEssler can you clarify?

**Comment by HolgerEssler** [comment]
The decision is to transfer these to 
*low-punctus* for kato-stigme
*middot* for mese-stigme
*high-punctus* for ano-stigme
This will be done by the Würzburg-team.

**Comment by paregorios** [comment]
@HolgerEssler am I to assume that the following XSLT output would be ok? 

```
((low-punctus))
((middot))
((high-punctus))
```

or is something different sought?

**Comment by paregorios** [comment]
per @jcowey @rla2118 middot should be output (as presumably already) as a middle dot, but double-bracketed output for the other two:

```
((low-punctus))
((high-punctus))
```

**Comment by paregorios** [comment]
No XSLT changes are required, but XML encoding needs to be changed for the ```type``` attribute values on ```<g>```.

**Comment by HolgerEssler** [comment]
XML updated and committed as agreed on Apr 5. I am thus closing this issue.
