### ISSUE TITLE
Create or change representation in XSLT for "Dicolon"

### ISSUE THREAD

**Issue by cgajjar05** [DCLP/dclpxsltbox#70]
Create or change representation in preview (XSLT) for "Dicolon".

**Comment by paregorios** [comment]
The LitPapText spreadsheet notes that ```<g type="dicolon"/>``` "already works" in XML and that one sees ```((dicolon))``` in corresponding output. But the spreadsheet seems to imagine that some change will be made to XSLT presentation. @rla2118 @jcowey @HolgerEssler can you clarify?

**Comment by rla2118** [comment]
output = ((dicolon))

**Comment by paregorios** [comment]
thanks @rla2118. No further action needed.
