### ISSUE TITLE
Create or change representation in preview (XSLT) for "Diple obelismene"

### ISSUE THREAD

**Issue by cgajjar05** [DCLP/dclpxsltbox#78]
Create or change representation in preview (XSLT) for "Diple obelismene".

**Comment by paregorios** [comment]
[The LitPapText spreadsheet](https://docs.google.com/spreadsheets/d/1F6_Du8DIjixRD4mnvfpbkcn3E0H2_SfBIztCO6Vl6gQ/edit#gid=1879498412) says that ```<milestone rend="diple-obelismene" unit="undefined"/>``` "works in XML" and that one gets ```((diple-obelismene))``` in HTML output. @rla2118 @jcowey @HolgerEssler is this acceptable result or should we implement something else?

**Comment by rla2118** [comment]
Desired output =   >---

**Comment by HolgerEssler** [comment]
(analogous to paragraphos)

**Comment by paregorios** [comment]
Right, so we want a right-pointing-pointy bracket, followed by three hyphens. Adjusting assignment and labels to make this one available for implementation (cc @wsalesky @leoba @sarcanon).

**Comment by leoba** [comment]
Added a new test `<xsl:when test="@rend = 'diple-obelismene' and @unit='undefined'">` to epidoc-xslt/htm-teimilestone.xsl to give the requested output.

Check 175282.html as the example file.

**Comment by paregorios** [comment]
This change is already merged to dclp branch on epidoc-xslt and it is working as designed.
