### ISSUE TITLE
Create or change representation in XSLT for "Coronis"

### ISSUE THREAD

**Issue by cgajjar05** [DCLP/dclpxsltbox#82]
Create or change representation in preview (XSLT) for "Coronis".

**Comment by paregorios** [comment]
[In the LitPapText Spreadsheet](https://docs.google.com/spreadsheets/d/1F6_Du8DIjixRD4mnvfpbkcn3E0H2_SfBIztCO6Vl6gQ/edit#gid=1879498412), ```<milestone rend="coronis" unit="undefined"/>``` is said to "work in XML" and to produce the output ```((coronis))``` in HTML transform. The question for @rla2118 @jcowey @HolgerEssler is: what do you want to see in HTML output?

**Comment by rla2118** [comment]
Holger, here too what is your preference?  Are we wanting a visual representation of these symbols, or is it OK to present them in words, in this case as ((coronis))?

**Comment by rla2118** [comment]
Desired output = ((coronis))

**Comment by paregorios** [comment]
Great! No further action.
