### ISSUE TITLE
Create or change representation in XSLT for "Diastole"

### ISSUE THREAD

**Issue by cgajjar05** [DCLP/dclpxsltbox#85]
Create or change representation in preview (XSLT) for "Diastole".

**Comment by paregorios** [comment]
[In the LitPapText Spreadsheet](https://docs.google.com/spreadsheets/d/1F6_Du8DIjixRD4mnvfpbkcn3E0H2_SfBIztCO6Vl6gQ/edit#gid=1879498412), ```<g type="diastole"/>``` is said to "work in XML" and to produce the output ```((diastole))``` in HTML transform. The question for @rla2118 @jcowey @HolgerEssler is: what do you want to see in HTML output?

**Comment by rla2118** [comment]
@HolgerEssler Do you want to see the symbol, or are we OK with ((diastole)) ?

**Comment by rla2118** [comment]
Desired output ((diastole))

**Comment by paregorios** [comment]
No further action. Thanks.
