### ISSUE TITLE
Handle "eisthesis" (indent) in XSLT

### ISSUE THREAD

**Issue by cgajjar05** [DCLP/dclpxsltbox#90]
Create or change representation in preview (XSLT) for "eisthesis".

**Comment by paregorios** [comment]
see also "ekthesis" #93

**Comment by paregorios** [comment]
The "LitPapText" spreadsheet (line 29) envisions the following:

XML: ```<lb n="1" rend="eisthesis"/>```

Leiden+ : ```(1, eisthesis)```

and reports that these "work", but XSLT doesn't handle them as desired.

**Comment by paregorios** [comment]
The TEI Guidelines already envision encoding ```rend="indent"``` on verse lines, so we should probably use the same term, rather than a subdiscipline-specific term.

**Comment by paregorios** [comment]
@rla2118 @HolgerEssler @jcowey how should eisthesis be represented in HTML output?

**Comment by paregorios** [comment]
See also [EpiDoc Feature Request 79](https://sourceforge.net/p/epidoc/feature-requests/79/).

**Comment by paregorios** [comment]
consensus via #93 seems to be indent three spaces, but first @wsalesky can you see if we have any texts currently containing ```<lb rend="eisthesis"``` or ```<lb rend="indent"``` in idp.data?

**Comment by wsalesky** [comment]
I found 129 occurrences of `<lb rend="eisthesis">` and 0 for `<lb rend="indent">`

**Comment by paregorios** [comment]
@jcowey @rla2118 @HolgerEssler @rogerbagnall would you like us to make the change from "eisthesis" to "indent" in the idp.data XML, or would you like to do it yourselves?

**Comment by paregorios** [comment]
per conversation with the papyrologists, they would like us to do this data update

**Comment by wsalesky** [comment]
**Changes to data:** converted <lb rend="eisthesis"> to <lb rend="indent">
**Branch:** https://github.com/DCLP/idp.data/tree/issue90

**XML files changed** 
```
	modified:   DCLP/120/119317.xml
	modified:   DCLP/144/143319.xml
	modified:   DCLP/60/59150.xml
	modified:   DCLP/60/59332.xml
	modified:   DCLP/60/59961.xml
	modified:   DCLP/60/59971.xml
	modified:   DCLP/61/60189.xml
	modified:   DCLP/64/63332.xml
	modified:   DCLP/64/63569.xml
	modified:   DCLP/64/63819.xml
	modified:   DCLP/64/63920.xml
	modified:   DCLP/64/63940.xml
	modified:   DCLP/65/64024.xml
	modified:   DCLP/65/64216.xml
	modified:   DCLP/65/64223.xml
	modified:   DCLP/65/64242.xml
	modified:   DCLP/65/64268.xml
	modified:   DCLP/65/64316.xml
	modified:   DCLP/65/64598.xml
	modified:   DCLP/65/64896.xml
	modified:   DCLP/65/64975.xml
	modified:   DCLP/66/65064.xml
	modified:   DCLP/66/65074.xml
	modified:   DCLP/66/65082.xml
	modified:   DCLP/66/65340.xml
	modified:   DCLP/66/65669.xml
	modified:   DCLP/70/69007.xml
	modified:   DCLP/70/69028.xml
```

**Comment by paregorios** [comment]
This issue is resolved. You may need to clear cache and reload to see changes (force CSS loading).
