### ISSUE TITLE
Handle "ekthesis" (outdent) with XSLT

### ISSUE THREAD

**Issue by cgajjar05** [DCLP/dclpxsltbox#93]
The "LitPapText" spreadsheet (line 30) envisions the following:

XML: ```<lb n="2" rend="ekthesis"/>```

Leiden+ : ```(2, ekthesis)```

and reports that these "work", but XSLT doesn't handle them as desired.

**Comment by paregorios** [comment]
See also enthesis #90

**Comment by paregorios** [comment]
The TEI Guidelines already envision encoding ```rend="indent"``` on verse lines, so by analogy we should probably use "[outdent](https://en.wiktionary.org/wiki/outdent)" (a neologism that is nonetheless in wide technical use to reflect this feature of layout).

**Comment by paregorios** [comment]
@rla2118 @HolgerEssler @jcowey how should ekthesis be represented in HTML output?

**Comment by paregorios** [comment]
See also [EpiDoc Feature Request 79](https://sourceforge.net/p/epidoc/feature-requests/79/).

**Comment by wsalesky** [comment]
@rla2118 @HolgerEssler @jcowey 
I can work on this ticket if I can get some feed back on how should ekthesis be represented in HTML output.

**Comment by jcowey** [comment]
@rla2118 @HolgerEssler please you two make the decision about how you want this to appear. Providing real life examples will be very helpful to test against.

**Comment by paregorios** [comment]
cc @rogerbagnall

**Comment by rla2118** [comment]
For "indent," as in line 2 below, I would just tab in a few characters

Cynthia prima suis miserum me cepit ocellis,
   contactum nullis ante cupidinibus.

For "outdent," as in line 1, the same, but in the other direction. 

What do you think, @HolgerEssler ?

**Comment by rla2118** [comment]
Seems that the formatting of the Propertius poem was lost above....  Let's discuss on Wednesday.

**Comment by paregorios** [comment]
@rla2118 if you surround formatted text with paired set of three backticks as I've just done to the Propertius example you supplied above, it will preserve whitespace.

@now the question for @HolgerEssler can be addressed.

**Comment by HolgerEssler** [comment]
I agree with the suggestion by @rla2118.

**Comment by paregorios** [comment]
@wsalesky can you trawl through idp.data to see if we have any ```<lb rend="ekthesis"``` or ```<lb rend="outdent"``` at present? Thx.

**Comment by wsalesky** [comment]
I found 78 hits for `<lb rend="ekthesis">` and 0 for `<lb rend="outdent">`

**Comment by paregorios** [comment]
@jcowey @rla2118 @HolgerEssler @rogerbagnall do you want us to do the cleanup on idp.data, converting ```<lb rend="ekthesis">``` to ```<lb rend="outdent">```? Or would you prefer to do it yourselves?

**Comment by paregorios** [comment]
per conversation with papyrologists, they would like us to undertake this data modification in idp.data/DCLP

**Comment by wsalesky** [comment]
Resoves #93 and #90 display issues. Still need to handle data issues. 

**XSLT changed:**` epidoc-xslt/example-p5-xslt/htm-teilb.xsl`
Added an empty span with css class for tei:lb with a rend attribute. (A span was necessary because a html br element can not have styles directly attached to it.)

**CSS changed:** `navigator/pn-site/css/master.css`
**CSS changed:** `dclpxsltbox/output/css/master.css`
Added styles for the following rend attributes: indent, eisthesis, outdent, ekthesis More can be added as needed. If not one of the above attributes the span is hidden. 

**Branches:** 
https://github.com/DCLP/dclpxsltbox/tree/issue90 (for css changes)
https://github.com/DCLP/navigator/tree/issue90 (for css changes)
https://github.com/DCLP/epidoc-xslt/tree/issue90 (for xslt change)

Example output (from an edited version dclp/120/119323.html): 
<img width="349" alt="screen shot 2017-05-25 at 11 34 47 am" src="https://cloud.githubusercontent.com/assets/1168206/26457451/2fa502c0-413e-11e7-98a2-7d92ee13d393.png">

**HTML files changed:** 
```
	modified:   output/dclp/120/119317.html
	modified:   output/dclp/120/119322.html
	modified:   output/dclp/120/119323.html
	modified:   output/dclp/129/128952.html
	modified:   output/dclp/144/143319.html
	modified:   output/dclp/60/59150.html
	modified:   output/dclp/60/59332.html
	modified:   output/dclp/60/59697.html
	modified:   output/dclp/60/59961.html
	modified:   output/dclp/60/59971.html
	modified:   output/dclp/61/60175.html
	modified:   output/dclp/61/60191.html
	modified:   output/dclp/62/61916.html
	modified:   output/dclp/64/63332.html
	modified:   output/dclp/64/63569.html
	modified:   output/dclp/64/63819.html
	modified:   output/dclp/64/63920.html
	modified:   output/dclp/65/64024.html
	modified:   output/dclp/65/64216.html
	modified:   output/dclp/65/64223.html
	modified:   output/dclp/65/64242.html
	modified:   output/dclp/65/64268.html
	modified:   output/dclp/65/64316.html
	modified:   output/dclp/65/64598.html
	modified:   output/dclp/65/64975.html
	modified:   output/dclp/66/65082.html
	modified:   output/dclp/66/65340.html
	modified:   output/dclp/66/65669.html
	modified:   output/dclp/69/68991.html
	modified:   output/dclp/70/69007.html
	modified:   output/dclp/70/69028.html
```

**Comment by wsalesky** [comment]
**Changes to data:** converted `<lb rend="ekthesis">` to `<lb rend="outdent">`
**Branch:**  https://github.com/DCLP/idp.data/tree/issue93
**Data files updated:** 
```
	modified:   DCLP/120/119322.xml
	modified:   DCLP/120/119323.xml
	modified:   DCLP/60/59150.xml
	modified:   DCLP/60/59332.xml
	modified:   DCLP/60/59697.xml
	modified:   DCLP/61/60175.xml
	modified:   DCLP/61/60191.xml
	modified:   DCLP/62/61916.xml
	modified:   DCLP/66/65340.xml
	modified:   DCLP/69/68991.xml
```

**Comment by paregorios** [comment]
This issue is resolved. You may need to clear cache and reload to see changes (force CSS loading).
